<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>blok.runtime.v1.ErrorCategory</code>
 */
class ErrorCategory
{
    /**
     * Generated from protobuf enum <code>CATEGORY_UNSPECIFIED = 0;</code>
     */
    const CATEGORY_UNSPECIFIED = 0;
    /**
     * input/output schema mismatch
     *
     * Generated from protobuf enum <code>VALIDATION = 1;</code>
     */
    const VALIDATION = 1;
    /**
     * node misconfigured
     *
     * Generated from protobuf enum <code>CONFIGURATION = 2;</code>
     */
    const CONFIGURATION = 2;
    /**
     * external service failed (DB, HTTP, queue)
     *
     * Generated from protobuf enum <code>DEPENDENCY = 3;</code>
     */
    const DEPENDENCY = 3;
    /**
     * Generated from protobuf enum <code>TIMEOUT = 4;</code>
     */
    const TIMEOUT = 4;
    /**
     * auth/authz
     *
     * Generated from protobuf enum <code>PERMISSION = 5;</code>
     */
    const PERMISSION = 5;
    /**
     * Generated from protobuf enum <code>RATE_LIMIT = 6;</code>
     */
    const RATE_LIMIT = 6;
    /**
     * Generated from protobuf enum <code>NOT_FOUND = 7;</code>
     */
    const NOT_FOUND = 7;
    /**
     * Generated from protobuf enum <code>CONFLICT = 8;</code>
     */
    const CONFLICT = 8;
    /**
     * Generated from protobuf enum <code>CANCELLED = 9;</code>
     */
    const CANCELLED = 9;
    /**
     * unexpected SDK-side bug
     *
     * Generated from protobuf enum <code>INTERNAL = 10;</code>
     */
    const INTERNAL = 10;
    /**
     * proto/transport issue
     *
     * Generated from protobuf enum <code>PROTOCOL = 11;</code>
     */
    const PROTOCOL = 11;
    /**
     * user data malformed (not schema validation)
     *
     * Generated from protobuf enum <code>DATA = 12;</code>
     */
    const DATA = 12;

    private static $valueToName = [
        self::CATEGORY_UNSPECIFIED => 'CATEGORY_UNSPECIFIED',
        self::VALIDATION => 'VALIDATION',
        self::CONFIGURATION => 'CONFIGURATION',
        self::DEPENDENCY => 'DEPENDENCY',
        self::TIMEOUT => 'TIMEOUT',
        self::PERMISSION => 'PERMISSION',
        self::RATE_LIMIT => 'RATE_LIMIT',
        self::NOT_FOUND => 'NOT_FOUND',
        self::CONFLICT => 'CONFLICT',
        self::CANCELLED => 'CANCELLED',
        self::INTERNAL => 'INTERNAL',
        self::PROTOCOL => 'PROTOCOL',
        self::DATA => 'DATA',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

