<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.ExecuteResponse</code>
 */
class ExecuteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * The node's primary return value. Bytes-encoded JSON.
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    protected $data = '';
    /**
     * Optional content-type override (default "application/json").
     *
     * Generated from protobuf field <code>string content_type = 3;</code>
     */
    protected $content_type = '';
    /**
     * Set iff !success. Always populated on failure (see NodeError).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.NodeError error = 4;</code>
     */
    protected $error = null;
    /**
     * Vars the node wants persisted (merged into ctx.vars on the runner side).
     * Optional — most nodes leave this empty and rely on workflow-level set_var.
     * Bytes-encoded JSON map<string, any>.
     *
     * Generated from protobuf field <code>bytes vars_delta = 5;</code>
     */
    protected $vars_delta = '';
    /**
     * Tail of logs captured during execution.
     *
     * Generated from protobuf field <code>repeated .blok.runtime.v1.LogLine logs = 6;</code>
     */
    private $logs;
    /**
     * Resource usage during this call. Populated when capture_metrics=true.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.Metrics metrics = 7;</code>
     */
    protected $metrics = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type string $data
     *           The node's primary return value. Bytes-encoded JSON.
     *     @type string $content_type
     *           Optional content-type override (default "application/json").
     *     @type \Blok\Runtime\V1\NodeError $error
     *           Set iff !success. Always populated on failure (see NodeError).
     *     @type string $vars_delta
     *           Vars the node wants persisted (merged into ctx.vars on the runner side).
     *           Optional — most nodes leave this empty and rely on workflow-level set_var.
     *           Bytes-encoded JSON map<string, any>.
     *     @type \Blok\Runtime\V1\LogLine[] $logs
     *           Tail of logs captured during execution.
     *     @type \Blok\Runtime\V1\Metrics $metrics
     *           Resource usage during this call. Populated when capture_metrics=true.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess(bool $var)
    {
        $this->success = $var;

        return $this;
    }

    /**
     * The node's primary return value. Bytes-encoded JSON.
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * The node's primary return value. Bytes-encoded JSON.
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->data = $var;

        return $this;
    }

    /**
     * Optional content-type override (default "application/json").
     *
     * Generated from protobuf field <code>string content_type = 3;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Optional content-type override (default "application/json").
     *
     * Generated from protobuf field <code>string content_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->content_type = $var;

        return $this;
    }

    /**
     * Set iff !success. Always populated on failure (see NodeError).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.NodeError error = 4;</code>
     * @return \Blok\Runtime\V1\NodeError|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Set iff !success. Always populated on failure (see NodeError).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.NodeError error = 4;</code>
     * @param \Blok\Runtime\V1\NodeError $var
     * @return $this
     */
    public function setError(\Blok\Runtime\V1\NodeError|null $var)
    {
        $this->error = $var;

        return $this;
    }

    /**
     * Vars the node wants persisted (merged into ctx.vars on the runner side).
     * Optional — most nodes leave this empty and rely on workflow-level set_var.
     * Bytes-encoded JSON map<string, any>.
     *
     * Generated from protobuf field <code>bytes vars_delta = 5;</code>
     * @return string
     */
    public function getVarsDelta()
    {
        return $this->vars_delta;
    }

    /**
     * Vars the node wants persisted (merged into ctx.vars on the runner side).
     * Optional — most nodes leave this empty and rely on workflow-level set_var.
     * Bytes-encoded JSON map<string, any>.
     *
     * Generated from protobuf field <code>bytes vars_delta = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVarsDelta(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->vars_delta = $var;

        return $this;
    }

    /**
     * Tail of logs captured during execution.
     *
     * Generated from protobuf field <code>repeated .blok.runtime.v1.LogLine logs = 6;</code>
     * @return RepeatedField<\Blok\Runtime\V1\LogLine>
     */
    public function getLogs()
    {
        return $this->logs;
    }

    /**
     * Tail of logs captured during execution.
     *
     * Generated from protobuf field <code>repeated .blok.runtime.v1.LogLine logs = 6;</code>
     * @param \Blok\Runtime\V1\LogLine[] $var
     * @return $this
     */
    public function setLogs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Blok\Runtime\V1\LogLine::class);
        $this->logs = $arr;

        return $this;
    }

    /**
     * Resource usage during this call. Populated when capture_metrics=true.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.Metrics metrics = 7;</code>
     * @return \Blok\Runtime\V1\Metrics|null
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    public function hasMetrics()
    {
        return isset($this->metrics);
    }

    public function clearMetrics()
    {
        unset($this->metrics);
    }

    /**
     * Resource usage during this call. Populated when capture_metrics=true.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.Metrics metrics = 7;</code>
     * @param \Blok\Runtime\V1\Metrics $var
     * @return $this
     */
    public function setMetrics(\Blok\Runtime\V1\Metrics|null $var)
    {
        $this->metrics = $var;

        return $this;
    }

}

