<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.ExecuteRequest</code>
 */
class ExecuteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Identification: which node, what type, what version.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.NodeRef node = 1;</code>
     */
    protected $node = null;
    /**
     * The node's own resolved inputs. Already mapped (js/, ${...} resolved).
     * Bytes-encoded JSON: SDKs JSON-decode lazily. NEVER wrapped in {inputs:...}.
     *
     * Generated from protobuf field <code>bytes inputs = 2;</code>
     */
    protected $inputs = '';
    /**
     * Where in the workflow this node sits.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.StepInfo step = 3;</code>
     */
    protected $step = null;
    /**
     * The originating workflow trigger (read-only context for nodes).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.TriggerInfo trigger = 4;</code>
     */
    protected $trigger = null;
    /**
     * Mutable state: previous step output, persistent vars, env mirror.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.RuntimeState state = 5;</code>
     */
    protected $state = null;
    /**
     * Identity of the parent workflow run.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.WorkflowInfo workflow = 6;</code>
     */
    protected $workflow = null;
    /**
     * Per-call options (deadline, streaming opt-in).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.ExecuteOptions options = 7;</code>
     */
    protected $options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Blok\Runtime\V1\NodeRef $node
     *           Identification: which node, what type, what version.
     *     @type string $inputs
     *           The node's own resolved inputs. Already mapped (js/, ${...} resolved).
     *           Bytes-encoded JSON: SDKs JSON-decode lazily. NEVER wrapped in {inputs:...}.
     *     @type \Blok\Runtime\V1\StepInfo $step
     *           Where in the workflow this node sits.
     *     @type \Blok\Runtime\V1\TriggerInfo $trigger
     *           The originating workflow trigger (read-only context for nodes).
     *     @type \Blok\Runtime\V1\RuntimeState $state
     *           Mutable state: previous step output, persistent vars, env mirror.
     *     @type \Blok\Runtime\V1\WorkflowInfo $workflow
     *           Identity of the parent workflow run.
     *     @type \Blok\Runtime\V1\ExecuteOptions $options
     *           Per-call options (deadline, streaming opt-in).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Identification: which node, what type, what version.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.NodeRef node = 1;</code>
     * @return \Blok\Runtime\V1\NodeRef|null
     */
    public function getNode()
    {
        return $this->node;
    }

    public function hasNode()
    {
        return isset($this->node);
    }

    public function clearNode()
    {
        unset($this->node);
    }

    /**
     * Identification: which node, what type, what version.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.NodeRef node = 1;</code>
     * @param \Blok\Runtime\V1\NodeRef $var
     * @return $this
     */
    public function setNode(\Blok\Runtime\V1\NodeRef|null $var)
    {
        $this->node = $var;

        return $this;
    }

    /**
     * The node's own resolved inputs. Already mapped (js/, ${...} resolved).
     * Bytes-encoded JSON: SDKs JSON-decode lazily. NEVER wrapped in {inputs:...}.
     *
     * Generated from protobuf field <code>bytes inputs = 2;</code>
     * @return string
     */
    public function getInputs()
    {
        return $this->inputs;
    }

    /**
     * The node's own resolved inputs. Already mapped (js/, ${...} resolved).
     * Bytes-encoded JSON: SDKs JSON-decode lazily. NEVER wrapped in {inputs:...}.
     *
     * Generated from protobuf field <code>bytes inputs = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInputs(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->inputs = $var;

        return $this;
    }

    /**
     * Where in the workflow this node sits.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.StepInfo step = 3;</code>
     * @return \Blok\Runtime\V1\StepInfo|null
     */
    public function getStep()
    {
        return $this->step;
    }

    public function hasStep()
    {
        return isset($this->step);
    }

    public function clearStep()
    {
        unset($this->step);
    }

    /**
     * Where in the workflow this node sits.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.StepInfo step = 3;</code>
     * @param \Blok\Runtime\V1\StepInfo $var
     * @return $this
     */
    public function setStep(\Blok\Runtime\V1\StepInfo|null $var)
    {
        $this->step = $var;

        return $this;
    }

    /**
     * The originating workflow trigger (read-only context for nodes).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.TriggerInfo trigger = 4;</code>
     * @return \Blok\Runtime\V1\TriggerInfo|null
     */
    public function getTrigger()
    {
        return $this->trigger;
    }

    public function hasTrigger()
    {
        return isset($this->trigger);
    }

    public function clearTrigger()
    {
        unset($this->trigger);
    }

    /**
     * The originating workflow trigger (read-only context for nodes).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.TriggerInfo trigger = 4;</code>
     * @param \Blok\Runtime\V1\TriggerInfo $var
     * @return $this
     */
    public function setTrigger(\Blok\Runtime\V1\TriggerInfo|null $var)
    {
        $this->trigger = $var;

        return $this;
    }

    /**
     * Mutable state: previous step output, persistent vars, env mirror.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.RuntimeState state = 5;</code>
     * @return \Blok\Runtime\V1\RuntimeState|null
     */
    public function getState()
    {
        return $this->state;
    }

    public function hasState()
    {
        return isset($this->state);
    }

    public function clearState()
    {
        unset($this->state);
    }

    /**
     * Mutable state: previous step output, persistent vars, env mirror.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.RuntimeState state = 5;</code>
     * @param \Blok\Runtime\V1\RuntimeState $var
     * @return $this
     */
    public function setState(\Blok\Runtime\V1\RuntimeState|null $var)
    {
        $this->state = $var;

        return $this;
    }

    /**
     * Identity of the parent workflow run.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.WorkflowInfo workflow = 6;</code>
     * @return \Blok\Runtime\V1\WorkflowInfo|null
     */
    public function getWorkflow()
    {
        return $this->workflow;
    }

    public function hasWorkflow()
    {
        return isset($this->workflow);
    }

    public function clearWorkflow()
    {
        unset($this->workflow);
    }

    /**
     * Identity of the parent workflow run.
     *
     * Generated from protobuf field <code>.blok.runtime.v1.WorkflowInfo workflow = 6;</code>
     * @param \Blok\Runtime\V1\WorkflowInfo $var
     * @return $this
     */
    public function setWorkflow(\Blok\Runtime\V1\WorkflowInfo|null $var)
    {
        $this->workflow = $var;

        return $this;
    }

    /**
     * Per-call options (deadline, streaming opt-in).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.ExecuteOptions options = 7;</code>
     * @return \Blok\Runtime\V1\ExecuteOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Per-call options (deadline, streaming opt-in).
     *
     * Generated from protobuf field <code>.blok.runtime.v1.ExecuteOptions options = 7;</code>
     * @param \Blok\Runtime\V1\ExecuteOptions $var
     * @return $this
     */
    public function setOptions(\Blok\Runtime\V1\ExecuteOptions|null $var)
    {
        $this->options = $var;

        return $this;
    }

}

