<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.ExecuteEvent</code>
 */
class ExecuteEvent extends \Google\Protobuf\Internal\Message
{
    protected $event;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Blok\Runtime\V1\NodeStarted $started
     *     @type \Blok\Runtime\V1\LogLine $log
     *     @type \Blok\Runtime\V1\Progress $progress
     *     @type \Blok\Runtime\V1\PartialResult $partial
     *     @type \Blok\Runtime\V1\ExecuteResponse $final
     *           last frame; closes the stream
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.NodeStarted started = 1;</code>
     * @return \Blok\Runtime\V1\NodeStarted|null
     */
    public function getStarted()
    {
        return $this->readOneof(1);
    }

    public function hasStarted()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.NodeStarted started = 1;</code>
     * @param \Blok\Runtime\V1\NodeStarted $var
     * @return $this
     */
    public function setStarted(\Blok\Runtime\V1\NodeStarted|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.LogLine log = 2;</code>
     * @return \Blok\Runtime\V1\LogLine|null
     */
    public function getLog()
    {
        return $this->readOneof(2);
    }

    public function hasLog()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.LogLine log = 2;</code>
     * @param \Blok\Runtime\V1\LogLine $var
     * @return $this
     */
    public function setLog(\Blok\Runtime\V1\LogLine|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.Progress progress = 3;</code>
     * @return \Blok\Runtime\V1\Progress|null
     */
    public function getProgress()
    {
        return $this->readOneof(3);
    }

    public function hasProgress()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.Progress progress = 3;</code>
     * @param \Blok\Runtime\V1\Progress $var
     * @return $this
     */
    public function setProgress(\Blok\Runtime\V1\Progress|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.PartialResult partial = 4;</code>
     * @return \Blok\Runtime\V1\PartialResult|null
     */
    public function getPartial()
    {
        return $this->readOneof(4);
    }

    public function hasPartial()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.PartialResult partial = 4;</code>
     * @param \Blok\Runtime\V1\PartialResult $var
     * @return $this
     */
    public function setPartial(\Blok\Runtime\V1\PartialResult|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * last frame; closes the stream
     *
     * Generated from protobuf field <code>.blok.runtime.v1.ExecuteResponse final = 5;</code>
     * @return \Blok\Runtime\V1\ExecuteResponse|null
     */
    public function getFinal()
    {
        return $this->readOneof(5);
    }

    public function hasFinal()
    {
        return $this->hasOneof(5);
    }

    /**
     * last frame; closes the stream
     *
     * Generated from protobuf field <code>.blok.runtime.v1.ExecuteResponse final = 5;</code>
     * @param \Blok\Runtime\V1\ExecuteResponse $var
     * @return $this
     */
    public function setFinal(\Blok\Runtime\V1\ExecuteResponse|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getEvent()
    {
        return $this->whichOneof("event");
    }

}

