<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.ExecuteOptions</code>
 */
class ExecuteOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * hard cutoff (also enforced via gRPC deadline)
     *
     * Generated from protobuf field <code>int64 deadline_ms = 1;</code>
     */
    protected $deadline_ms = 0;
    /**
     * hint: caller wants ExecuteStream events
     *
     * Generated from protobuf field <code>bool stream_logs = 2;</code>
     */
    protected $stream_logs = false;
    /**
     * Generated from protobuf field <code>bool capture_metrics = 3;</code>
     */
    protected $capture_metrics = false;
    /**
     * Reserved for future routing/affinity hints without bumping schema.
     *
     * Generated from protobuf field <code>map<string, string> hints = 15;</code>
     */
    private $hints;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $deadline_ms
     *           hard cutoff (also enforced via gRPC deadline)
     *     @type bool $stream_logs
     *           hint: caller wants ExecuteStream events
     *     @type bool $capture_metrics
     *     @type array|\Google\Protobuf\Internal\MapField $hints
     *           Reserved for future routing/affinity hints without bumping schema.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * hard cutoff (also enforced via gRPC deadline)
     *
     * Generated from protobuf field <code>int64 deadline_ms = 1;</code>
     * @return int|string
     */
    public function getDeadlineMs()
    {
        return $this->deadline_ms;
    }

    /**
     * hard cutoff (also enforced via gRPC deadline)
     *
     * Generated from protobuf field <code>int64 deadline_ms = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeadlineMs(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->deadline_ms = $var;

        return $this;
    }

    /**
     * hint: caller wants ExecuteStream events
     *
     * Generated from protobuf field <code>bool stream_logs = 2;</code>
     * @return bool
     */
    public function getStreamLogs()
    {
        return $this->stream_logs;
    }

    /**
     * hint: caller wants ExecuteStream events
     *
     * Generated from protobuf field <code>bool stream_logs = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setStreamLogs(bool $var)
    {
        $this->stream_logs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool capture_metrics = 3;</code>
     * @return bool
     */
    public function getCaptureMetrics()
    {
        return $this->capture_metrics;
    }

    /**
     * Generated from protobuf field <code>bool capture_metrics = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setCaptureMetrics(bool $var)
    {
        $this->capture_metrics = $var;

        return $this;
    }

    /**
     * Reserved for future routing/affinity hints without bumping schema.
     *
     * Generated from protobuf field <code>map<string, string> hints = 15;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHints()
    {
        return $this->hints;
    }

    /**
     * Reserved for future routing/affinity hints without bumping schema.
     *
     * Generated from protobuf field <code>map<string, string> hints = 15;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHints(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hints = $arr;

        return $this;
    }

}

