<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.HealthResponse</code>
 */
class HealthResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.blok.runtime.v1.HealthResponse.Status status = 1;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string sdk_version = 2;</code>
     */
    protected $sdk_version = '';
    /**
     * Generated from protobuf field <code>repeated string registered_nodes = 3;</code>
     */
    private $registered_nodes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type string $sdk_version
     *     @type string[] $registered_nodes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.HealthResponse.Status status = 1;</code>
     * @return int one of the values in {@see \Blok\Runtime\V1\HealthResponse\Status}
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.HealthResponse.Status status = 1;</code>
     * @param int $var one of the values in {@see \Blok\Runtime\V1\HealthResponse\Status}
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkEnum($var, \Blok\Runtime\V1\HealthResponse\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sdk_version = 2;</code>
     * @return string
     */
    public function getSdkVersion()
    {
        return $this->sdk_version;
    }

    /**
     * Generated from protobuf field <code>string sdk_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sdk_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string registered_nodes = 3;</code>
     * @return RepeatedField<string>
     */
    public function getRegisteredNodes()
    {
        return $this->registered_nodes;
    }

    /**
     * Generated from protobuf field <code>repeated string registered_nodes = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setRegisteredNodes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->registered_nodes = $arr;

        return $this;
    }

}

