<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.ListNodesResponse</code>
 */
class ListNodesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .blok.runtime.v1.NodeDescriptor nodes = 1;</code>
     */
    private $nodes;
    /**
     * "blok-python3"
     *
     * Generated from protobuf field <code>string sdk_name = 2;</code>
     */
    protected $sdk_name = '';
    /**
     * Generated from protobuf field <code>string sdk_version = 3;</code>
     */
    protected $sdk_version = '';
    /**
     * "1.0.0"
     *
     * Generated from protobuf field <code>string proto_version = 4;</code>
     */
    protected $proto_version = '';
    /**
     * Optional runtime capabilities this SDK advertises (ADR 0014). Additive:
     * an SDK that leaves it empty is assumed to support only the base contract,
     * and the runner degrades accordingly — never a hard failure.
     * Known values:
     *   "blob-v1" — the SDK resolves a claim-check sentinel
     *               {"$blokBlob":{"id","bytes","codec"}} appearing in place of
     *               `ExecuteRequest.inputs` by reading `<BLOK_BLOB_DIR>/<id>`.
     *               Advertise it ONLY when BLOK_BLOB_DIR is set and readable —
     *               the runner sends refs solely to runtimes that claim it.
     *
     * Generated from protobuf field <code>repeated string capabilities = 5;</code>
     */
    private $capabilities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Blok\Runtime\V1\NodeDescriptor[] $nodes
     *     @type string $sdk_name
     *           "blok-python3"
     *     @type string $sdk_version
     *     @type string $proto_version
     *           "1.0.0"
     *     @type string[] $capabilities
     *           Optional runtime capabilities this SDK advertises (ADR 0014). Additive:
     *           an SDK that leaves it empty is assumed to support only the base contract,
     *           and the runner degrades accordingly — never a hard failure.
     *           Known values:
     *             "blob-v1" — the SDK resolves a claim-check sentinel
     *                         {"$blokBlob":{"id","bytes","codec"}} appearing in place of
     *                         `ExecuteRequest.inputs` by reading `<BLOK_BLOB_DIR>/<id>`.
     *                         Advertise it ONLY when BLOK_BLOB_DIR is set and readable —
     *                         the runner sends refs solely to runtimes that claim it.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .blok.runtime.v1.NodeDescriptor nodes = 1;</code>
     * @return RepeatedField<\Blok\Runtime\V1\NodeDescriptor>
     */
    public function getNodes()
    {
        return $this->nodes;
    }

    /**
     * Generated from protobuf field <code>repeated .blok.runtime.v1.NodeDescriptor nodes = 1;</code>
     * @param \Blok\Runtime\V1\NodeDescriptor[] $var
     * @return $this
     */
    public function setNodes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Blok\Runtime\V1\NodeDescriptor::class);
        $this->nodes = $arr;

        return $this;
    }

    /**
     * "blok-python3"
     *
     * Generated from protobuf field <code>string sdk_name = 2;</code>
     * @return string
     */
    public function getSdkName()
    {
        return $this->sdk_name;
    }

    /**
     * "blok-python3"
     *
     * Generated from protobuf field <code>string sdk_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sdk_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sdk_version = 3;</code>
     * @return string
     */
    public function getSdkVersion()
    {
        return $this->sdk_version;
    }

    /**
     * Generated from protobuf field <code>string sdk_version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sdk_version = $var;

        return $this;
    }

    /**
     * "1.0.0"
     *
     * Generated from protobuf field <code>string proto_version = 4;</code>
     * @return string
     */
    public function getProtoVersion()
    {
        return $this->proto_version;
    }

    /**
     * "1.0.0"
     *
     * Generated from protobuf field <code>string proto_version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProtoVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->proto_version = $var;

        return $this;
    }

    /**
     * Optional runtime capabilities this SDK advertises (ADR 0014). Additive:
     * an SDK that leaves it empty is assumed to support only the base contract,
     * and the runner degrades accordingly — never a hard failure.
     * Known values:
     *   "blob-v1" — the SDK resolves a claim-check sentinel
     *               {"$blokBlob":{"id","bytes","codec"}} appearing in place of
     *               `ExecuteRequest.inputs` by reading `<BLOK_BLOB_DIR>/<id>`.
     *               Advertise it ONLY when BLOK_BLOB_DIR is set and readable —
     *               the runner sends refs solely to runtimes that claim it.
     *
     * Generated from protobuf field <code>repeated string capabilities = 5;</code>
     * @return RepeatedField<string>
     */
    public function getCapabilities()
    {
        return $this->capabilities;
    }

    /**
     * Optional runtime capabilities this SDK advertises (ADR 0014). Additive:
     * an SDK that leaves it empty is assumed to support only the base contract,
     * and the runner degrades accordingly — never a hard failure.
     * Known values:
     *   "blob-v1" — the SDK resolves a claim-check sentinel
     *               {"$blokBlob":{"id","bytes","codec"}} appearing in place of
     *               `ExecuteRequest.inputs` by reading `<BLOK_BLOB_DIR>/<id>`.
     *               Advertise it ONLY when BLOK_BLOB_DIR is set and readable —
     *               the runner sends refs solely to runtimes that claim it.
     *
     * Generated from protobuf field <code>repeated string capabilities = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setCapabilities(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->capabilities = $arr;

        return $this;
    }

}

