<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.Metrics</code>
 */
class Metrics extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double duration_ms = 1;</code>
     */
    protected $duration_ms = 0.0;
    /**
     * Generated from protobuf field <code>double cpu_ms = 2;</code>
     */
    protected $cpu_ms = 0.0;
    /**
     * Generated from protobuf field <code>int64 memory_bytes = 3;</code>
     */
    protected $memory_bytes = 0;
    /**
     * Generated from protobuf field <code>int64 request_bytes = 4;</code>
     */
    protected $request_bytes = 0;
    /**
     * Generated from protobuf field <code>int64 response_bytes = 5;</code>
     */
    protected $response_bytes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $duration_ms
     *     @type float $cpu_ms
     *     @type int|string $memory_bytes
     *     @type int|string $request_bytes
     *     @type int|string $response_bytes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double duration_ms = 1;</code>
     * @return float
     */
    public function getDurationMs()
    {
        return $this->duration_ms;
    }

    /**
     * Generated from protobuf field <code>double duration_ms = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationMs(float $var)
    {
        $this->duration_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double cpu_ms = 2;</code>
     * @return float
     */
    public function getCpuMs()
    {
        return $this->cpu_ms;
    }

    /**
     * Generated from protobuf field <code>double cpu_ms = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setCpuMs(float $var)
    {
        $this->cpu_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 memory_bytes = 3;</code>
     * @return int|string
     */
    public function getMemoryBytes()
    {
        return $this->memory_bytes;
    }

    /**
     * Generated from protobuf field <code>int64 memory_bytes = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemoryBytes(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->memory_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 request_bytes = 4;</code>
     * @return int|string
     */
    public function getRequestBytes()
    {
        return $this->request_bytes;
    }

    /**
     * Generated from protobuf field <code>int64 request_bytes = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestBytes(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->request_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 response_bytes = 5;</code>
     * @return int|string
     */
    public function getResponseBytes()
    {
        return $this->response_bytes;
    }

    /**
     * Generated from protobuf field <code>int64 response_bytes = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResponseBytes(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->response_bytes = $var;

        return $this;
    }

}

