<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.NodeDescriptor</code>
 */
class NodeDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * JSON Schema (drives OpenAPI/Studio/LLMs)
     *
     * Generated from protobuf field <code>bytes input_schema_json = 3;</code>
     */
    protected $input_schema_json = '';
    /**
     * Generated from protobuf field <code>bytes output_schema_json = 4;</code>
     */
    protected $output_schema_json = '';
    /**
     * Generated from protobuf field <code>repeated string tags = 5;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $description
     *     @type string $input_schema_json
     *           JSON Schema (drives OpenAPI/Studio/LLMs)
     *     @type string $output_schema_json
     *     @type string[] $tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * JSON Schema (drives OpenAPI/Studio/LLMs)
     *
     * Generated from protobuf field <code>bytes input_schema_json = 3;</code>
     * @return string
     */
    public function getInputSchemaJson()
    {
        return $this->input_schema_json;
    }

    /**
     * JSON Schema (drives OpenAPI/Studio/LLMs)
     *
     * Generated from protobuf field <code>bytes input_schema_json = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInputSchemaJson(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->input_schema_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes output_schema_json = 4;</code>
     * @return string
     */
    public function getOutputSchemaJson()
    {
        return $this->output_schema_json;
    }

    /**
     * Generated from protobuf field <code>bytes output_schema_json = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOutputSchemaJson(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->output_schema_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 5;</code>
     * @return RepeatedField<string>
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setTags(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

