<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.NodeError</code>
 */
class NodeError extends \Google\Protobuf\Internal\Message
{
    /**
     * === Identity ===
     *
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>.blok.runtime.v1.ErrorCategory category = 2;</code>
     */
    protected $category = 0;
    /**
     * Generated from protobuf field <code>.blok.runtime.v1.ErrorSeverity severity = 3;</code>
     */
    protected $severity = 0;
    /**
     * === Origin (auto-filled by SDK) ===
     *
     * Generated from protobuf field <code>string node = 4;</code>
     */
    protected $node = '';
    /**
     * "blok-python3"
     *
     * Generated from protobuf field <code>string sdk = 5;</code>
     */
    protected $sdk = '';
    /**
     * Generated from protobuf field <code>string sdk_version = 6;</code>
     */
    protected $sdk_version = '';
    /**
     * "runtime.python3"
     *
     * Generated from protobuf field <code>string runtime_kind = 7;</code>
     */
    protected $runtime_kind = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp at = 8;</code>
     */
    protected $at = null;
    /**
     * === Human-readable ===
     *
     * Generated from protobuf field <code>string message = 9;</code>
     */
    protected $message = '';
    /**
     * multi-paragraph context
     *
     * Generated from protobuf field <code>string description = 10;</code>
     */
    protected $description = '';
    /**
     * suggested next step
     *
     * Generated from protobuf field <code>string remediation = 11;</code>
     */
    protected $remediation = '';
    /**
     * Generated from protobuf field <code>string doc_url = 12;</code>
     */
    protected $doc_url = '';
    /**
     * === Causality ===
     *
     * Generated from protobuf field <code>repeated .blok.runtime.v1.NodeError causes = 13;</code>
     */
    private $causes;
    /**
     * Generated from protobuf field <code>string stack = 14;</code>
     */
    protected $stack = '';
    /**
     * Generated from protobuf field <code>bytes context_snapshot_json = 15;</code>
     */
    protected $context_snapshot_json = '';
    /**
     * === Compatibility / retry hints ===
     *
     * Generated from protobuf field <code>int32 http_status = 16;</code>
     */
    protected $http_status = 0;
    /**
     * Generated from protobuf field <code>bool retryable = 17;</code>
     */
    protected $retryable = false;
    /**
     * Generated from protobuf field <code>int64 retry_after_ms = 18;</code>
     */
    protected $retry_after_ms = 0;
    /**
     * === Category-specific structured details ===
     * Bytes-encoded JSON. Surfaces to GlobalError.json on the runner side.
     *
     * Generated from protobuf field <code>bytes details_json = 19;</code>
     */
    protected $details_json = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *           === Identity ===
     *     @type int $category
     *     @type int $severity
     *     @type string $node
     *           === Origin (auto-filled by SDK) ===
     *     @type string $sdk
     *           "blok-python3"
     *     @type string $sdk_version
     *     @type string $runtime_kind
     *           "runtime.python3"
     *     @type \Google\Protobuf\Timestamp $at
     *     @type string $message
     *           === Human-readable ===
     *     @type string $description
     *           multi-paragraph context
     *     @type string $remediation
     *           suggested next step
     *     @type string $doc_url
     *     @type \Blok\Runtime\V1\NodeError[] $causes
     *           === Causality ===
     *     @type string $stack
     *     @type string $context_snapshot_json
     *     @type int $http_status
     *           === Compatibility / retry hints ===
     *     @type bool $retryable
     *     @type int|string $retry_after_ms
     *     @type string $details_json
     *           === Category-specific structured details ===
     *           Bytes-encoded JSON. Surfaces to GlobalError.json on the runner side.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * === Identity ===
     *
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * === Identity ===
     *
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.ErrorCategory category = 2;</code>
     * @return int one of the values in {@see \Blok\Runtime\V1\ErrorCategory}
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.ErrorCategory category = 2;</code>
     * @param int $var one of the values in {@see \Blok\Runtime\V1\ErrorCategory}
     * @return $this
     */
    public function setCategory(int $var)
    {
        GPBUtil::checkEnum($var, \Blok\Runtime\V1\ErrorCategory::class);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.ErrorSeverity severity = 3;</code>
     * @return int one of the values in {@see \Blok\Runtime\V1\ErrorSeverity}
     */
    public function getSeverity()
    {
        return $this->severity;
    }

    /**
     * Generated from protobuf field <code>.blok.runtime.v1.ErrorSeverity severity = 3;</code>
     * @param int $var one of the values in {@see \Blok\Runtime\V1\ErrorSeverity}
     * @return $this
     */
    public function setSeverity(int $var)
    {
        GPBUtil::checkEnum($var, \Blok\Runtime\V1\ErrorSeverity::class);
        $this->severity = $var;

        return $this;
    }

    /**
     * === Origin (auto-filled by SDK) ===
     *
     * Generated from protobuf field <code>string node = 4;</code>
     * @return string
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     * === Origin (auto-filled by SDK) ===
     *
     * Generated from protobuf field <code>string node = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->node = $var;

        return $this;
    }

    /**
     * "blok-python3"
     *
     * Generated from protobuf field <code>string sdk = 5;</code>
     * @return string
     */
    public function getSdk()
    {
        return $this->sdk;
    }

    /**
     * "blok-python3"
     *
     * Generated from protobuf field <code>string sdk = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSdk(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sdk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sdk_version = 6;</code>
     * @return string
     */
    public function getSdkVersion()
    {
        return $this->sdk_version;
    }

    /**
     * Generated from protobuf field <code>string sdk_version = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sdk_version = $var;

        return $this;
    }

    /**
     * "runtime.python3"
     *
     * Generated from protobuf field <code>string runtime_kind = 7;</code>
     * @return string
     */
    public function getRuntimeKind()
    {
        return $this->runtime_kind;
    }

    /**
     * "runtime.python3"
     *
     * Generated from protobuf field <code>string runtime_kind = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRuntimeKind(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->runtime_kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp at = 8;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getAt()
    {
        return $this->at;
    }

    public function hasAt()
    {
        return isset($this->at);
    }

    public function clearAt()
    {
        unset($this->at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp at = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setAt(\Google\Protobuf\Timestamp|null $var)
    {
        $this->at = $var;

        return $this;
    }

    /**
     * === Human-readable ===
     *
     * Generated from protobuf field <code>string message = 9;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * === Human-readable ===
     *
     * Generated from protobuf field <code>string message = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->message = $var;

        return $this;
    }

    /**
     * multi-paragraph context
     *
     * Generated from protobuf field <code>string description = 10;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * multi-paragraph context
     *
     * Generated from protobuf field <code>string description = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * suggested next step
     *
     * Generated from protobuf field <code>string remediation = 11;</code>
     * @return string
     */
    public function getRemediation()
    {
        return $this->remediation;
    }

    /**
     * suggested next step
     *
     * Generated from protobuf field <code>string remediation = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setRemediation(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->remediation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string doc_url = 12;</code>
     * @return string
     */
    public function getDocUrl()
    {
        return $this->doc_url;
    }

    /**
     * Generated from protobuf field <code>string doc_url = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDocUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->doc_url = $var;

        return $this;
    }

    /**
     * === Causality ===
     *
     * Generated from protobuf field <code>repeated .blok.runtime.v1.NodeError causes = 13;</code>
     * @return RepeatedField<\Blok\Runtime\V1\NodeError>
     */
    public function getCauses()
    {
        return $this->causes;
    }

    /**
     * === Causality ===
     *
     * Generated from protobuf field <code>repeated .blok.runtime.v1.NodeError causes = 13;</code>
     * @param \Blok\Runtime\V1\NodeError[] $var
     * @return $this
     */
    public function setCauses(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Blok\Runtime\V1\NodeError::class);
        $this->causes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stack = 14;</code>
     * @return string
     */
    public function getStack()
    {
        return $this->stack;
    }

    /**
     * Generated from protobuf field <code>string stack = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setStack(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->stack = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes context_snapshot_json = 15;</code>
     * @return string
     */
    public function getContextSnapshotJson()
    {
        return $this->context_snapshot_json;
    }

    /**
     * Generated from protobuf field <code>bytes context_snapshot_json = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setContextSnapshotJson(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->context_snapshot_json = $var;

        return $this;
    }

    /**
     * === Compatibility / retry hints ===
     *
     * Generated from protobuf field <code>int32 http_status = 16;</code>
     * @return int
     */
    public function getHttpStatus()
    {
        return $this->http_status;
    }

    /**
     * === Compatibility / retry hints ===
     *
     * Generated from protobuf field <code>int32 http_status = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setHttpStatus(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->http_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool retryable = 17;</code>
     * @return bool
     */
    public function getRetryable()
    {
        return $this->retryable;
    }

    /**
     * Generated from protobuf field <code>bool retryable = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setRetryable(bool $var)
    {
        $this->retryable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 retry_after_ms = 18;</code>
     * @return int|string
     */
    public function getRetryAfterMs()
    {
        return $this->retry_after_ms;
    }

    /**
     * Generated from protobuf field <code>int64 retry_after_ms = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRetryAfterMs(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->retry_after_ms = $var;

        return $this;
    }

    /**
     * === Category-specific structured details ===
     * Bytes-encoded JSON. Surfaces to GlobalError.json on the runner side.
     *
     * Generated from protobuf field <code>bytes details_json = 19;</code>
     * @return string
     */
    public function getDetailsJson()
    {
        return $this->details_json;
    }

    /**
     * === Category-specific structured details ===
     * Bytes-encoded JSON. Surfaces to GlobalError.json on the runner side.
     *
     * Generated from protobuf field <code>bytes details_json = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setDetailsJson(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->details_json = $var;

        return $this;
    }

}

