<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.NodeStarted</code>
 */
class NodeStarted extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp at = 1;</code>
     */
    protected $at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp at = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getAt()
    {
        return $this->at;
    }

    public function hasAt()
    {
        return isset($this->at);
    }

    public function clearAt()
    {
        unset($this->at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp at = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setAt(\Google\Protobuf\Timestamp|null $var)
    {
        $this->at = $var;

        return $this;
    }

}

