<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.PartialResult</code>
 */
class PartialResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes snapshot_json = 1;</code>
     */
    protected $snapshot_json = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $snapshot_json
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes snapshot_json = 1;</code>
     * @return string
     */
    public function getSnapshotJson()
    {
        return $this->snapshot_json;
    }

    /**
     * Generated from protobuf field <code>bytes snapshot_json = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSnapshotJson(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->snapshot_json = $var;

        return $this;
    }

}

