<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.Progress</code>
 */
class Progress extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double percent = 1;</code>
     */
    protected $percent = 0.0;
    /**
     * Generated from protobuf field <code>string phase = 2;</code>
     */
    protected $phase = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $percent
     *     @type string $phase
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double percent = 1;</code>
     * @return float
     */
    public function getPercent()
    {
        return $this->percent;
    }

    /**
     * Generated from protobuf field <code>double percent = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setPercent(float $var)
    {
        $this->percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phase = 2;</code>
     * @return string
     */
    public function getPhase()
    {
        return $this->phase;
    }

    /**
     * Generated from protobuf field <code>string phase = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhase(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->phase = $var;

        return $this;
    }

}

