<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.RuntimeState</code>
 */
class RuntimeState extends \Google\Protobuf\Internal\Message
{
    /**
     * Output of the previous step. Named explicitly so LLM-authored nodes stop
     * confusing it with vars. Bytes-encoded JSON.
     *
     * Generated from protobuf field <code>bytes previous_output = 1;</code>
     */
    protected $previous_output = '';
    /**
     * Workflow-scoped persistent storage (set_var: true on prior steps).
     * Bytes-encoded JSON map<string, any>.
     *
     * Generated from protobuf field <code>bytes vars = 2;</code>
     */
    protected $vars = '';
    /**
     * String→string env mirror.
     *
     * Generated from protobuf field <code>map<string, string> env = 3;</code>
     */
    private $env;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $previous_output
     *           Output of the previous step. Named explicitly so LLM-authored nodes stop
     *           confusing it with vars. Bytes-encoded JSON.
     *     @type string $vars
     *           Workflow-scoped persistent storage (set_var: true on prior steps).
     *           Bytes-encoded JSON map<string, any>.
     *     @type array|\Google\Protobuf\Internal\MapField $env
     *           String→string env mirror.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Output of the previous step. Named explicitly so LLM-authored nodes stop
     * confusing it with vars. Bytes-encoded JSON.
     *
     * Generated from protobuf field <code>bytes previous_output = 1;</code>
     * @return string
     */
    public function getPreviousOutput()
    {
        return $this->previous_output;
    }

    /**
     * Output of the previous step. Named explicitly so LLM-authored nodes stop
     * confusing it with vars. Bytes-encoded JSON.
     *
     * Generated from protobuf field <code>bytes previous_output = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPreviousOutput(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->previous_output = $var;

        return $this;
    }

    /**
     * Workflow-scoped persistent storage (set_var: true on prior steps).
     * Bytes-encoded JSON map<string, any>.
     *
     * Generated from protobuf field <code>bytes vars = 2;</code>
     * @return string
     */
    public function getVars()
    {
        return $this->vars;
    }

    /**
     * Workflow-scoped persistent storage (set_var: true on prior steps).
     * Bytes-encoded JSON map<string, any>.
     *
     * Generated from protobuf field <code>bytes vars = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVars(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->vars = $var;

        return $this;
    }

    /**
     * String→string env mirror.
     *
     * Generated from protobuf field <code>map<string, string> env = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getEnv()
    {
        return $this->env;
    }

    /**
     * String→string env mirror.
     *
     * Generated from protobuf field <code>map<string, string> env = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setEnv(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->env = $arr;

        return $this;
    }

}

