<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.StepInfo</code>
 */
class StepInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * step name in workflow
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * 0-based index in current branch
     *
     * Generated from protobuf field <code>int32 index = 2;</code>
     */
    protected $index = 0;
    /**
     * total steps in current branch
     *
     * Generated from protobuf field <code>int32 total = 3;</code>
     */
    protected $total = 0;
    /**
     * 0 = top-level; 1+ = nested in flow node (if-else)
     *
     * Generated from protobuf field <code>int32 depth = 4;</code>
     */
    protected $depth = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           step name in workflow
     *     @type int $index
     *           0-based index in current branch
     *     @type int $total
     *           total steps in current branch
     *     @type int $depth
     *           0 = top-level; 1+ = nested in flow node (if-else)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * step name in workflow
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * step name in workflow
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * 0-based index in current branch
     *
     * Generated from protobuf field <code>int32 index = 2;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * 0-based index in current branch
     *
     * Generated from protobuf field <code>int32 index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * total steps in current branch
     *
     * Generated from protobuf field <code>int32 total = 3;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * total steps in current branch
     *
     * Generated from protobuf field <code>int32 total = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

    /**
     * 0 = top-level; 1+ = nested in flow node (if-else)
     *
     * Generated from protobuf field <code>int32 depth = 4;</code>
     * @return int
     */
    public function getDepth()
    {
        return $this->depth;
    }

    /**
     * 0 = top-level; 1+ = nested in flow node (if-else)
     *
     * Generated from protobuf field <code>int32 depth = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDepth(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->depth = $var;

        return $this;
    }

}

