<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blok/runtime/v1/runtime.proto

namespace Blok\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>blok.runtime.v1.TriggerInfo</code>
 */
class TriggerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Snapshot of the trigger that started the workflow. Read-only for nodes.
     *
     * Generated from protobuf field <code>bytes body = 1;</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>map<string, string> headers = 2;</code>
     */
    private $headers;
    /**
     * Generated from protobuf field <code>map<string, string> params = 3;</code>
     */
    private $params;
    /**
     * Generated from protobuf field <code>map<string, string> query = 4;</code>
     */
    private $query;
    /**
     * Generated from protobuf field <code>map<string, string> cookies = 5;</code>
     */
    private $cookies;
    /**
     * Generated from protobuf field <code>string method = 6;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>string url = 7;</code>
     */
    protected $url = '';
    /**
     * Generated from protobuf field <code>string base_url = 8;</code>
     */
    protected $base_url = '';
    /**
     * "http" | "worker" | "cron" | ...
     *
     * Generated from protobuf field <code>string trigger_kind = 9;</code>
     */
    protected $trigger_kind = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $body
     *           Snapshot of the trigger that started the workflow. Read-only for nodes.
     *     @type array|\Google\Protobuf\Internal\MapField $headers
     *     @type array|\Google\Protobuf\Internal\MapField $params
     *     @type array|\Google\Protobuf\Internal\MapField $query
     *     @type array|\Google\Protobuf\Internal\MapField $cookies
     *     @type string $method
     *     @type string $url
     *     @type string $base_url
     *     @type string $trigger_kind
     *           "http" | "worker" | "cron" | ...
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blok\Runtime\V1\Runtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Snapshot of the trigger that started the workflow. Read-only for nodes.
     *
     * Generated from protobuf field <code>bytes body = 1;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Snapshot of the trigger that started the workflow. Read-only for nodes.
     *
     * Generated from protobuf field <code>bytes body = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBody(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> headers = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>map<string, string> headers = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->headers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> params = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Generated from protobuf field <code>map<string, string> params = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParams(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> query = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Generated from protobuf field <code>map<string, string> query = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setQuery(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->query = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> cookies = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCookies()
    {
        return $this->cookies;
    }

    /**
     * Generated from protobuf field <code>map<string, string> cookies = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCookies(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cookies = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 6;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 7;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string base_url = 8;</code>
     * @return string
     */
    public function getBaseUrl()
    {
        return $this->base_url;
    }

    /**
     * Generated from protobuf field <code>string base_url = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->base_url = $var;

        return $this;
    }

    /**
     * "http" | "worker" | "cron" | ...
     *
     * Generated from protobuf field <code>string trigger_kind = 9;</code>
     * @return string
     */
    public function getTriggerKind()
    {
        return $this->trigger_kind;
    }

    /**
     * "http" | "worker" | "cron" | ...
     *
     * Generated from protobuf field <code>string trigger_kind = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTriggerKind(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->trigger_kind = $var;

        return $this;
    }

}

