# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from blok.runtime.v1 import runtime_pb2 as blok_dot_runtime_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in blok/runtime/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeRuntimeStub(object):
    """=============================================================================
    Service
    =============================================================================

    NodeRuntime is the contract every Blok SDK exposes. One service handles
    three responsibilities:
    1. Run a node (Execute / ExecuteStream)
    2. Tell the runner which nodes it can run (ListNodes)
    3. Tell the runner if it is alive (Health)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/blok.runtime.v1.NodeRuntime/Execute',
                request_serializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.ExecuteStream = channel.unary_stream(
                '/blok.runtime.v1.NodeRuntime/ExecuteStream',
                request_serializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/blok.runtime.v1.NodeRuntime/Health',
                request_serializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.HealthRequest.SerializeToString,
                response_deserializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/blok.runtime.v1.NodeRuntime/ListNodes',
                request_serializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ListNodesResponse.FromString,
                _registered_method=True)


class NodeRuntimeServicer(object):
    """=============================================================================
    Service
    =============================================================================

    NodeRuntime is the contract every Blok SDK exposes. One service handles
    three responsibilities:
    1. Run a node (Execute / ExecuteStream)
    2. Tell the runner which nodes it can run (ListNodes)
    3. Tell the runner if it is alive (Health)
    """

    def Execute(self, request, context):
        """Run a node and return its result. Unary, deadline-driven.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStream(self, request, context):
        """Run a node and stream events back as it executes (logs, progress, partial
        results, then a final ExecuteResponse). Optional capability — SDKs that
        don't implement it should return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check (wire-compatible with grpc.health.v1.Health/Check).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Discover registered nodes and their schemas (drives Studio + OpenAPI gen).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.FromString,
                    response_serializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteResponse.SerializeToString,
            ),
            'ExecuteStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteStream,
                    request_deserializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.FromString,
                    response_serializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.HealthRequest.FromString,
                    response_serializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.HealthResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ListNodesRequest.FromString,
                    response_serializer=blok_dot_runtime_dot_v1_dot_runtime__pb2.ListNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blok.runtime.v1.NodeRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blok.runtime.v1.NodeRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeRuntime(object):
    """=============================================================================
    Service
    =============================================================================

    NodeRuntime is the contract every Blok SDK exposes. One service handles
    three responsibilities:
    1. Run a node (Execute / ExecuteStream)
    2. Tell the runner which nodes it can run (ListNodes)
    3. Tell the runner if it is alive (Health)
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blok.runtime.v1.NodeRuntime/Execute',
            blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.SerializeToString,
            blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blok.runtime.v1.NodeRuntime/ExecuteStream',
            blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteRequest.SerializeToString,
            blok_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blok.runtime.v1.NodeRuntime/Health',
            blok_dot_runtime_dot_v1_dot_runtime__pb2.HealthRequest.SerializeToString,
            blok_dot_runtime_dot_v1_dot_runtime__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blok.runtime.v1.NodeRuntime/ListNodes',
            blok_dot_runtime_dot_v1_dot_runtime__pb2.ListNodesRequest.SerializeToString,
            blok_dot_runtime_dot_v1_dot_runtime__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
