prepare:
	echo VITE_WORKFLOWS_PATH=${PWD}/triggers/http/workflows > ${PWD}/core/runner/.env.local
	echo VITE_NODES_PATH=${PWD}/triggers/http/src/nodes >> ${PWD}/core/runner/.env.local

cli-dev:
	pnpm --filter blokctl -r run dev

# =============================================================================
# Proto codegen
# =============================================================================
#
# `make proto` regenerates SDK gRPC stubs from
# `proto/blok/runtime/v1/runtime.proto`. Each SDK uses its language-native
# toolchain so generated artifacts match language conventions.
#
# Prerequisites:
#   - buf            (https://buf.build) for lint/breaking-change checks
#   - protoc         (https://grpc.io/docs/protoc-installation)
#   - language SDKs  (cargo, go, python3, java/maven, dotnet, php, ruby)

PROTO_DIR := proto
PROTO_FILE := $(PROTO_DIR)/blok/runtime/v1/runtime.proto

.PHONY: proto proto-lint proto-breaking proto-rust proto-go proto-python proto-java proto-csharp proto-php proto-ruby proto-clean

proto: proto-lint proto-rust proto-go proto-python proto-java proto-csharp proto-php proto-ruby  ## Regenerate gRPC stubs for all SDKs

proto-lint:  ## Lint proto files with buf
	buf lint

proto-breaking:  ## Check for breaking changes against the previous git tag
	buf breaking --against '.git#tag=$(shell git describe --tags --abbrev=0 2>/dev/null || echo HEAD~1)'

proto-rust:  ## Sync proto into the Rust SDK; tonic-build generates stubs at compile time
	@mkdir -p sdks/rust/proto/blok/runtime/v1
	cp $(PROTO_FILE) sdks/rust/proto/blok/runtime/v1/runtime.proto
	@echo "Proto synced. Stubs are generated by tonic-build during 'cargo build'."
	@echo "Build with: cd sdks/rust && cargo build --features grpc"

proto-go:  ## Sync proto into Go SDK + regenerate stubs (uses Python's bundled protoc)
	@mkdir -p sdks/go/proto/blok/runtime/v1
	cp $(PROTO_FILE) sdks/go/proto/blok/runtime/v1/runtime.proto
	@mkdir -p sdks/go/genpb
	@if ! command -v protoc-gen-go >/dev/null; then \
		echo "Installing protoc-gen-go + protoc-gen-go-grpc…"; \
		go install google.golang.org/protobuf/cmd/protoc-gen-go@latest; \
		go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest; \
	fi
	@cd sdks/go && PATH="$$HOME/go/bin:$$PATH" python3 -m grpc_tools.protoc \
		-I proto \
		--go_out=genpb --go_opt=paths=source_relative \
		--go-grpc_out=genpb --go-grpc_opt=paths=source_relative \
		proto/blok/runtime/v1/runtime.proto
	@echo "Go stubs regenerated. Build with: cd sdks/go && go build ./..."

proto-python:  ## Sync proto into Python SDK + regenerate stubs
	@mkdir -p sdks/python3/proto/blok/runtime/v1
	cp $(PROTO_FILE) sdks/python3/proto/blok/runtime/v1/runtime.proto
	@mkdir -p sdks/python3/blok/runtime/v1
	@touch sdks/python3/blok/runtime/__init__.py
	@touch sdks/python3/blok/runtime/v1/__init__.py
	cd sdks/python3 && python3 -m grpc_tools.protoc \
		-I proto \
		--python_out=. \
		--grpc_python_out=. \
		proto/blok/runtime/v1/runtime.proto
	@echo "Python stubs regenerated. Install grpcio first: pip install grpcio>=1.60 grpcio-tools>=1.60 protobuf>=4.25"

proto-java:  ## (Re)generate Java stubs (handled by protobuf-maven-plugin)
	@echo "Java stubs are generated by protobuf-maven-plugin during 'mvn compile'."
	@echo "Build the Java SDK to regenerate: cd sdks/java && mvn compile"

proto-csharp:  ## (Re)generate C# stubs (handled by Grpc.Tools at build time)
	@echo "C# stubs are generated by Grpc.Tools during 'dotnet build'."
	@echo "Build the C# SDK to regenerate: cd sdks/csharp && dotnet build"

proto-php:  ## Regenerate PHP stubs
	@mkdir -p sdks/php/src/Genpb
	protoc \
		--proto_path=$(PROTO_DIR) \
		--php_out=sdks/php/src/Genpb \
		--grpc_out=sdks/php/src/Genpb \
		--plugin=protoc-gen-grpc=$(shell which grpc_php_plugin) \
		$(PROTO_FILE)

proto-ruby:  ## Regenerate Ruby stubs
	@mkdir -p sdks/ruby/lib/blok/genpb
	grpc_tools_ruby_protoc \
		--proto_path=$(PROTO_DIR) \
		--ruby_out=sdks/ruby/lib/blok/genpb \
		--grpc_out=sdks/ruby/lib/blok/genpb \
		$(PROTO_FILE)

proto-clean:  ## Remove all generated proto stubs
	rm -rf sdks/go/genpb
	rm -rf sdks/python3/blok/genpb
	rm -rf sdks/php/src/Genpb
	rm -rf sdks/ruby/lib/blok/genpb