prepare:
	echo VITE_WORKFLOWS_PATH=${PWD}/triggers/http/workflows > ${PWD}/core/runner/.env.local
	echo VITE_NODES_PATH=${PWD}/triggers/http/src/nodes >> ${PWD}/core/runner/.env.local

cli-dev:
	pnpm --filter blokctl -r run dev

# =============================================================================
# Proto codegen
# =============================================================================
#
# `make proto` regenerates SDK gRPC stubs from
# `proto/blok/runtime/v1/runtime.proto`. Each SDK uses its language-native
# toolchain so generated artifacts match language conventions.
#
# Prerequisites:
#   - buf            (https://buf.build) for lint/breaking-change checks
#   - protoc         (https://grpc.io/docs/protoc-installation)
#   - language SDKs  (cargo, go, python3, java/maven, dotnet, php, ruby)

PROTO_DIR := proto
PROTO_FILE := $(PROTO_DIR)/blok/runtime/v1/runtime.proto

.PHONY: proto proto-lint proto-breaking proto-rust proto-go proto-python proto-java proto-csharp proto-php proto-ruby proto-clean

proto: proto-lint proto-rust proto-go proto-python proto-java proto-csharp proto-php proto-ruby  ## Regenerate gRPC stubs for all SDKs

proto-lint:  ## Lint proto files with buf
	buf lint

proto-breaking:  ## Check for breaking changes against the previous git tag
	buf breaking --against '.git#tag=$(shell git describe --tags --abbrev=0 2>/dev/null || echo HEAD~1)'

proto-rust:  ## (Re)generate Rust stubs (handled by tonic-build at compile time)
	@echo "Rust stubs are generated by tonic-build at compile time."
	@echo "Build the Rust SDK to regenerate: cd sdks/rust && cargo build --features grpc"

proto-go:  ## Regenerate Go stubs
	@mkdir -p sdks/go/genpb
	protoc \
		--proto_path=$(PROTO_DIR) \
		--go_out=sdks/go/genpb --go_opt=paths=source_relative \
		--go-grpc_out=sdks/go/genpb --go-grpc_opt=paths=source_relative \
		$(PROTO_FILE)

proto-python:  ## Regenerate Python stubs
	@mkdir -p sdks/python3/blok/genpb
	python3 -m grpc_tools.protoc \
		--proto_path=$(PROTO_DIR) \
		--python_out=sdks/python3/blok/genpb \
		--grpc_python_out=sdks/python3/blok/genpb \
		$(PROTO_FILE)

proto-java:  ## (Re)generate Java stubs (handled by protobuf-maven-plugin)
	@echo "Java stubs are generated by protobuf-maven-plugin during 'mvn compile'."
	@echo "Build the Java SDK to regenerate: cd sdks/java && mvn compile"

proto-csharp:  ## (Re)generate C# stubs (handled by Grpc.Tools at build time)
	@echo "C# stubs are generated by Grpc.Tools during 'dotnet build'."
	@echo "Build the C# SDK to regenerate: cd sdks/csharp && dotnet build"

proto-php:  ## Regenerate PHP stubs
	@mkdir -p sdks/php/src/Genpb
	protoc \
		--proto_path=$(PROTO_DIR) \
		--php_out=sdks/php/src/Genpb \
		--grpc_out=sdks/php/src/Genpb \
		--plugin=protoc-gen-grpc=$(shell which grpc_php_plugin) \
		$(PROTO_FILE)

proto-ruby:  ## Regenerate Ruby stubs
	@mkdir -p sdks/ruby/lib/blok/genpb
	grpc_tools_ruby_protoc \
		--proto_path=$(PROTO_DIR) \
		--ruby_out=sdks/ruby/lib/blok/genpb \
		--grpc_out=sdks/ruby/lib/blok/genpb \
		$(PROTO_FILE)

proto-clean:  ## Remove all generated proto stubs
	rm -rf sdks/go/genpb
	rm -rf sdks/python3/blok/genpb
	rm -rf sdks/php/src/Genpb
	rm -rf sdks/ruby/lib/blok/genpb