name = "World Countries"
description = "Workflow description"
version = "1.0.0"

[trigger.http]
method = "GET"
path = "/countries"
accept = "application/json"

[[steps]]
id = "get-countries-api"
use = "@blokjs/api-call"
type = "module"

[steps.inputs]
url = "https://countriesnow.space/api/v0.1/countries/capital"
method = "GET"
responseType = "application/json"

  [steps.inputs.headers]
  Content-Type = "application/json"
