{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blok.secretName" . }}
  labels:
    {{- include "blok.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.keys }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
