import { createInertiaApp } from "@inertiajs/svelte";
// The runtime route table behind `route()` — regenerated by `bun run gen:types`.
import "./blok-routes.js";
import { listenForFlash } from "./flash-toast.js";

listenForFlash();

// v3 `pages` shorthand: `@inertiajs/vite` compiles it into the `resolve` glob,
// and the adapter supplies `setup` (mount, or hydrate after SSR) itself.
createInertiaApp({
	pages: "./pages",
	title: (title) => (title ? `${title} — __BLOK_SPA_NAME__` : "__BLOK_SPA_NAME__"),
	progress: { color: "#4b5563" },
});
