import { createInertiaApp } from "@inertiajs/svelte";
// The runtime route table behind `route()` — regenerated by `bun run gen:types`.
import "./blok-routes.js";
import { listenForFlash } from "./flash-toast.js";
// The Blok design system: tokens, layout and components in plain CSS.
import "./styles/blok.css";
import { initTheme, installFavicon } from "./styles/theme.js";

initTheme();
installFavicon();
listenForFlash();

// v3 `pages` shorthand: `@inertiajs/vite` compiles it into the `resolve` glob,
// and the adapter supplies `setup` (mount, or hydrate after SSR) itself.
createInertiaApp({
	// No `title:` here on purpose: @inertiajs/svelte has no <Head> and its
	// head manager hard-codes the title resolver to identity, so the option
	// is dead config. Svelte pages build their own <svelte:head> title from
	// `src/title.ts` instead.
	pages: "./pages",
	progress: { color: "#2bcd71" },
});
