// Code generated by blokctl. DO NOT EDIT.
//
// Default no-op shim. `blokctl dev` regenerates this in
// .blok/runtimes/rust/src/user_nodes with the user nodes scaffolded under
// runtimes/rust/nodes. Committed so the SDK compiles without codegen — e.g. the
// cross-runtime CI build, which has no user nodes.
use blok::registry::NodeRegistry;

/// Registers nodes scaffolded under runtimes/rust/nodes. No-op in the SDK tree.
pub fn register_user_nodes(_registry: &mut NodeRegistry) {}
