import { randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
	InMemoryInteractionStore,
	InteractionAuthorizationError,
	InteractionConflictError,
	InteractionResumeCoordinator,
	MemorySessionStore,
} from "@blokjs/runner";
import type {
	AgentSessionEvent,
	InteractionPayload,
	InteractionRecord,
	InteractionStore,
	PolicyRequest,
	SessionEventInput,
	SessionJsonValue,
	SessionState,
	SessionStore,
} from "@blokjs/shared";
import { AgentSessionContractError, InteractionContractError, SessionConcurrencyError } from "@blokjs/shared";
import {
	type Metadata,
	Server,
	ServerCredentials,
	type ServerUnaryCall,
	type ServerWritableStream,
	type ServiceError,
	type sendUnaryData,
	status,
} from "@grpc/grpc-js";
import type { z } from "zod";
import {
	CONTROL_PLANE_CONTRACT_VERSION,
	CONTROL_PLANE_DEFAULT_PAGE_SIZE,
	CONTROL_PLANE_MAX_EVENT_BYTES,
	CONTROL_PLANE_MAX_METADATA_ENTRIES,
	CONTROL_PLANE_MAX_METADATA_VALUE_LENGTH,
	CONTROL_PLANE_MAX_REQUEST_BYTES,
	CONTROL_PLANE_MAX_RESPONSE_BYTES,
	CONTROL_PLANE_OPERATIONS,
	CONTROL_PLANE_SUPPORTED_VERSIONS,
	type CancelRequest,
	type CancellationTarget,
	type ControlPlaneCapabilities,
	ControlPlaneContractError,
	type ControlPlaneEndpoint,
	type CreateSessionRequest,
	type ResumeRequest,
	type SessionResponse,
	type StartWorkflowRequest,
	type SteerTurnRequest,
	type StreamEventsRequest,
	type SubmitTurnRequest,
	type TurnResponse,
	type WorkflowResponse,
	answerInteractionRequestSchema,
	assertJsonSize,
	cancelRequestSchema,
	createSessionRequestSchema,
	ensureSupportedVersion,
	eventByteSize,
	forkSessionRequestSchema,
	openSessionRequestSchema,
	parseInteractionAnswerPayload,
	parseRequest,
	resumeRequestSchema,
	startWorkflowRequestSchema,
	steerTurnRequestSchema,
	streamEventsRequestSchema,
	submitTurnRequestSchema,
} from "./contracts";
import {
	type ProtoCapabilitiesResponse,
	type ProtoEventEnvelope,
	type ProtoHealthRequest,
	type ProtoHealthResponse,
	type ProtoRequestEnvelope,
	type ProtoResponseEnvelope,
	type ProtoStreamEventsRequest,
	getHarnessControlPlaneService,
} from "./proto";

type UnaryCall = ServerUnaryCall<ProtoRequestEnvelope, ProtoResponseEnvelope>;
type StreamCall = ServerWritableStream<ProtoStreamEventsRequest, ProtoEventEnvelope>;
type UnaryCallback = sendUnaryData<ProtoResponseEnvelope>;

export interface TurnExecutionInput {
	readonly sessionId: string;
	readonly turnId: string;
	readonly content: SessionJsonValue;
	readonly signal: AbortSignal;
}

export interface WorkflowExecutionInput {
	readonly sessionId: string;
	readonly workflowRunId: string;
	readonly workflowName: string;
	readonly input: SessionJsonValue | undefined;
	readonly signal: AbortSignal;
}

export interface TurnExecutionResult {
	readonly content: SessionJsonValue;
}

export interface WorkflowExecutionResult {
	readonly output?: SessionJsonValue;
}

export interface HarnessControlPlaneServerOptions {
	readonly sessionStore?: SessionStore;
	readonly interactionStore?: InteractionStore;
	/** Defaults to 127.0.0.1:0; fixed unauthenticated public ports are never used. */
	readonly listenAddress?: string;
	/** An opaque host-owned credential. A cryptographically random token is generated by default. */
	readonly token?: string;
	readonly principalId?: string;
	readonly closeStoreOnStop?: boolean;
	readonly executionReady?: boolean | (() => boolean | Promise<boolean>);
	readonly executeTurn?: (input: TurnExecutionInput) => Promise<TurnExecutionResult | undefined>;
	readonly steerTurn?: (input: TurnExecutionInput & { readonly content: SessionJsonValue }) => Promise<void>;
	readonly executeWorkflow?: (input: WorkflowExecutionInput) => Promise<WorkflowExecutionResult | undefined>;
	readonly reauthorizeInteraction?: (request: PolicyRequest) => void | Promise<void>;
	readonly resumeInteraction?: (input: {
		readonly interaction: InteractionRecord;
		readonly answer: InteractionPayload | undefined;
		readonly sessionId: string;
	}) => void | Promise<void>;
}

interface ActiveOperation {
	readonly kind: Exclude<CancellationTarget, "session">;
	readonly targetId: string;
	readonly sessionId: string;
	readonly controller: AbortController;
	readonly deadlineTimer?: ReturnType<typeof setTimeout>;
}

export interface HarnessControlPlaneServerHandle extends ControlPlaneEndpoint {
	readonly server: Server;
	stop(): Promise<void>;
	capabilities(): ControlPlaneCapabilities;
}

function protoFileExists(): string {
	const here = path.dirname(fileURLToPath(import.meta.url));
	return path.resolve(here, "../proto/blok/harness/control/v1/control.proto");
}

function valueFromMetadata(metadata: Metadata, key: string): string | undefined {
	const value = metadata.get(key)[0];
	if (typeof value === "string") return value;
	if (Buffer.isBuffer(value)) return value.toString("utf8");
	return undefined;
}

function sameSecret(left: string, right: string): boolean {
	const leftBytes = Buffer.from(left);
	const rightBytes = Buffer.from(right);
	return leftBytes.length === rightBytes.length && timingSafeEqual(leftBytes, rightBytes);
}

function jsonBuffer(value: unknown, maxBytes: number, label: string): Buffer {
	assertJsonSize(value, maxBytes, label);
	return Buffer.from(JSON.stringify(value), "utf8");
}

function parseJsonBuffer(buffer: unknown, maxBytes: number, label: string): unknown {
	if (!Buffer.isBuffer(buffer) && !(buffer instanceof Uint8Array))
		throw new ControlPlaneContractError(`${label} is not bytes`);
	const bytes = Buffer.from(buffer);
	if (bytes.byteLength > maxBytes) throw new ControlPlaneContractError(`${label} exceeds ${maxBytes} bytes`);
	if (bytes.byteLength === 0) return {};
	try {
		return JSON.parse(bytes.toString("utf8")) as unknown;
	} catch {
		throw new ControlPlaneContractError(`${label} is not valid JSON`);
	}
}

function requestId(request: ProtoRequestEnvelope): string {
	if (typeof request.requestId !== "string" || request.requestId.length === 0 || request.requestId.length > 256)
		throw new ControlPlaneContractError("request_id must be a non-empty string of at most 256 characters");
	return request.requestId;
}

function sequence(value: string | number | undefined, label: string): number {
	const result = Number(value ?? 0);
	if (!Number.isSafeInteger(result) || result < 0) throw new ControlPlaneContractError(`${label} is invalid`);
	return result;
}

function protocolError(error: unknown): ServiceError {
	const message = error instanceof Error ? error.message : "control-plane request failed";
	let code = status.INTERNAL;
	if (error !== null && typeof error === "object" && typeof (error as { code?: unknown }).code === "number")
		code = (error as { code: number }).code;
	if (
		error instanceof ControlPlaneContractError ||
		error instanceof AgentSessionContractError ||
		error instanceof InteractionContractError
	)
		code = status.INVALID_ARGUMENT;
	if (error instanceof SessionConcurrencyError || error instanceof InteractionConflictError) code = status.ABORTED;
	if (error instanceof InteractionAuthorizationError) code = status.PERMISSION_DENIED;
	if (error instanceof ControlPlaneNotFoundError) code = status.NOT_FOUND;
	if (error instanceof ControlPlaneTooLargeError) code = status.RESOURCE_EXHAUSTED;
	const result = new Error(message) as ServiceError;
	result.code = code;
	const stableCode =
		error !== null && typeof error === "object" && typeof (error as { code?: unknown }).code === "string"
			? (error as { code: string }).code
			: (status[code] ?? "CONTROL_PLANE_ERROR");
	result.details = `${stableCode}: ${message}`;
	return result;
}

class ControlPlaneNotFoundError extends Error {
	readonly code = "CONTROL_PLANE_NOT_FOUND";
}

class ControlPlaneTooLargeError extends Error {
	readonly code = "CONTROL_PLANE_MESSAGE_TOO_LARGE";
}

function eventInput(
	sessionId: string,
	kind: SessionEventInput["kind"],
	actor: SessionEventInput["actor"],
	payload: SessionJsonValue,
	requestIdValue: string,
	turnId?: string,
): SessionEventInput {
	return {
		contractVersion: "1",
		schemaVersion: 1,
		id: randomUUID(),
		sessionId,
		...(turnId ? { turnId } : {}),
		kind,
		visibility: kind.startsWith("message.") || kind === "steering.received" ? "model-visible" : "operational",
		actor,
		occurredAt: new Date().toISOString(),
		idempotencyKey: `${requestIdValue}:${kind}`,
		payload,
	};
}

function actor(principalId: string): SessionEventInput["actor"] {
	return { kind: "user", id: principalId };
}

function serviceErrorResponse(error: unknown, callback: UnaryCallback): void {
	callback(protocolError(error));
}

export class HarnessControlPlaneServer implements HarnessControlPlaneServerHandle {
	readonly server: Server;
	readonly address: string;
	port: number;
	readonly token: string;
	readonly contractVersion = CONTROL_PLANE_CONTRACT_VERSION;

	private readonly sessionStore: SessionStore;
	private readonly interactionStore: InteractionStore;
	private readonly options: HarnessControlPlaneServerOptions;
	private readonly serverInstanceId = randomUUID();
	private readonly active = new Map<string, ActiveOperation>();
	private readonly appendQueues = new Map<string, Promise<void>>();
	private started = false;
	private storeReady = false;

	private constructor(
		options: HarnessControlPlaneServerOptions,
		server: Server,
		address: string,
		port: number,
		token: string,
	) {
		this.options = options;
		this.server = server;
		this.address = address;
		this.port = port;
		this.token = token;
		this.sessionStore = options.sessionStore ?? new MemorySessionStore();
		this.interactionStore = options.interactionStore ?? new InMemoryInteractionStore();
		this.registerService();
	}

	static async start(options: HarnessControlPlaneServerOptions = {}): Promise<HarnessControlPlaneServer> {
		const listenAddress = options.listenAddress ?? "127.0.0.1:0";
		const server = new Server();
		const token = options.token ?? randomBytes(32).toString("base64url");
		const host = listenAddress.slice(0, Math.max(0, listenAddress.lastIndexOf(":"))) || "127.0.0.1";
		const instance = new HarnessControlPlaneServer(options, server, host, 0, token);
		const port = await new Promise<number>((resolve, reject) => {
			server.bindAsync(listenAddress, ServerCredentials.createInsecure(), (error, boundPort) => {
				if (error) reject(error);
				else resolve(boundPort);
			});
		});
		instance.port = port;
		await instance.sessionStore.migrate();
		instance.storeReady = true;
		instance.started = true;
		return instance;
	}

	capabilities(): ControlPlaneCapabilities {
		return {
			contractVersion: CONTROL_PLANE_CONTRACT_VERSION,
			supportedVersions: [...CONTROL_PLANE_SUPPORTED_VERSIONS],
			operations: CONTROL_PLANE_OPERATIONS,
			maxRequestBytes: CONTROL_PLANE_MAX_REQUEST_BYTES,
			maxResponseBytes: CONTROL_PLANE_MAX_RESPONSE_BYTES,
			maxEventBytes: CONTROL_PLANE_MAX_EVENT_BYTES,
			supportsCursorResume: true,
			supportsAuthentication: true,
			supportsDeadlines: true,
			supportsCancellation: true,
		};
	}

	endpoint(): ControlPlaneEndpoint {
		return { address: this.address, port: this.port, token: this.token, contractVersion: this.contractVersion };
	}

	async stop(): Promise<void> {
		if (!this.started) return;
		for (const operation of this.active.values()) operation.controller.abort("server stopped");
		this.active.clear();
		await new Promise<void>((resolve) => this.server.tryShutdown(() => resolve()));
		if (this.options.closeStoreOnStop) await this.sessionStore.close?.();
		this.started = false;
	}

	private registerService(): void {
		this.server.addService(getHarnessControlPlaneService(), {
			GetCapabilities: (
				_call: ServerUnaryCall<unknown, ProtoCapabilitiesResponse>,
				callback: (error: ServiceError | null, response?: ProtoCapabilitiesResponse) => void,
			) => {
				try {
					this.authorize(_call.metadata);
					callback(null, this.capabilitiesWire());
				} catch (error) {
					callback(protocolError(error));
				}
			},
			Health: (
				call: ServerUnaryCall<ProtoHealthRequest, ProtoHealthResponse>,
				callback: (error: ServiceError | null, response?: ProtoHealthResponse) => void,
			) => {
				this.health(call, callback, false);
			},
			Readiness: (
				call: ServerUnaryCall<ProtoHealthRequest, ProtoHealthResponse>,
				callback: (error: ServiceError | null, response?: ProtoHealthResponse) => void,
			) => {
				this.health(call, callback, true);
			},
			CreateSession: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "create-session", (request, principal) => this.createSession(request, principal)),
			OpenSession: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "open-session", (request) => this.openSession(request)),
			ForkSession: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "fork-session", (request, principal) => this.forkSession(request, principal)),
			InspectSession: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "inspect-session", (request) => this.inspectSession(request)),
			SubmitTurn: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "submit-turn", (request, principal) => this.submitTurn(request, principal)),
			SteerTurn: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "steer-turn", (request, principal) => this.steer(request, principal)),
			StartWorkflow: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "start-workflow", (request, principal) => this.startWorkflow(request, principal)),
			StreamEvents: (call: StreamCall) => this.streamEvents(call),
			AnswerInteraction: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "answer-interaction", (request, principal) =>
					this.answerInteraction(request, principal),
				),
			ResolveApproval: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "resolve-approval", (request, principal) =>
					this.answerInteraction(request, principal),
				),
			Cancel: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "cancel", (request, principal) => this.cancel(request, principal)),
			Resume: (call: UnaryCall, callback: UnaryCallback) =>
				this.unary(call, callback, "resume", (request, principal) => this.resume(request, principal)),
		} as unknown as Parameters<Server["addService"]>[1]);
	}

	private capabilitiesWire(): ProtoCapabilitiesResponse {
		const capabilities = this.capabilities();
		return {
			contractVersion: capabilities.contractVersion,
			supportedVersions: [...capabilities.supportedVersions],
			operations: [...capabilities.operations],
			maxRequestBytes: capabilities.maxRequestBytes,
			maxResponseBytes: capabilities.maxResponseBytes,
			maxEventBytes: capabilities.maxEventBytes,
			supportsCursorResume: true,
			supportsAuthentication: true,
			supportsDeadlines: true,
			supportsCancellation: true,
		};
	}

	private health(
		call: ServerUnaryCall<ProtoHealthRequest, ProtoHealthResponse>,
		callback: (error: ServiceError | null, response?: ProtoHealthResponse) => void,
		readiness: boolean,
	): void {
		void Promise.resolve()
			.then(() => this.authorize(call.metadata))
			.then(() => this.executionReady())
			.then((executionReady) => {
				const ready = this.storeReady && executionReady;
				callback(null, {
					contractVersion: CONTROL_PLANE_CONTRACT_VERSION,
					serverInstanceId: this.serverInstanceId,
					processAlive: true,
					storeReady: this.storeReady,
					executionReady,
					status: readiness ? (ready ? "SERVING" : "NOT_SERVING") : "SERVING",
					message: readiness && !ready ? "control-plane dependencies are not ready" : "control-plane is alive",
				});
			})
			.catch((error: unknown) => callback(protocolError(error)));
	}

	private async executionReady(): Promise<boolean> {
		const value = this.options.executionReady ?? true;
		return typeof value === "function" ? await value() : value;
	}

	private authorize(metadata: Metadata): string {
		const authorization = valueFromMetadata(metadata, "authorization");
		const supplied = authorization?.startsWith("Bearer ")
			? authorization.slice("Bearer ".length)
			: valueFromMetadata(metadata, "x-blok-harness-token");
		if (!supplied || !sameSecret(supplied, this.token)) {
			const error = new Error("control-plane authentication required") as ServiceError;
			error.code = status.UNAUTHENTICATED;
			throw error;
		}
		return valueFromMetadata(metadata, "x-blok-principal-id") ?? this.options.principalId ?? "local-client";
	}

	private unary(
		call: UnaryCall,
		callback: UnaryCallback,
		operation: Parameters<typeof parseRequest>[2],
		handler: (request: ProtoRequestEnvelope, principal: string) => Promise<unknown>,
	): void {
		void (async () => {
			const principal = this.authorize(call.metadata);
			const decoded = this.decodeEnvelope(call.request);
			const value = await handler(decoded, principal);
			callback(null, this.response(decoded, value));
		})().catch((error: unknown) => serviceErrorResponse(error, callback));
	}

	private decodeEnvelope(request: ProtoRequestEnvelope): ProtoRequestEnvelope {
		ensureSupportedVersion(request.contractVersion);
		requestId(request);
		if (request.metadata && Object.keys(request.metadata).length > CONTROL_PLANE_MAX_METADATA_ENTRIES)
			throw new ControlPlaneTooLargeError("request metadata has too many entries");
		for (const [key, value] of Object.entries(request.metadata ?? {})) {
			if (
				key.length > CONTROL_PLANE_MAX_METADATA_VALUE_LENGTH ||
				value.length > CONTROL_PLANE_MAX_METADATA_VALUE_LENGTH
			)
				throw new ControlPlaneTooLargeError("request metadata contains an oversized value");
		}
		if (request.deadlineUnixMs && Number(request.deadlineUnixMs) > 0 && Number(request.deadlineUnixMs) < Date.now()) {
			const error = new Error("control-plane request deadline exceeded") as ServiceError;
			error.code = status.DEADLINE_EXCEEDED;
			throw error;
		}
		parseJsonBuffer(request.payloadJson, CONTROL_PLANE_MAX_REQUEST_BYTES, "request payload");
		return request;
	}

	private payload<T>(
		request: ProtoRequestEnvelope,
		schema: z.ZodType<T>,
		operation: Parameters<typeof parseRequest>[2],
	): T {
		return parseRequest(
			schema,
			parseJsonBuffer(request.payloadJson, CONTROL_PLANE_MAX_REQUEST_BYTES, "request payload"),
			operation,
		);
	}

	private response(request: ProtoRequestEnvelope, value: unknown): ProtoResponseEnvelope {
		const payloadJson = jsonBuffer(value, CONTROL_PLANE_MAX_RESPONSE_BYTES, "response payload");
		return {
			contractVersion: CONTROL_PLANE_CONTRACT_VERSION,
			requestId: request.requestId,
			status: "ok",
			code: "OK",
			message: "",
			payloadJson,
			lastSequence: "0",
		};
	}

	private async withAppendQueue<T>(sessionId: string, operation: () => Promise<T>): Promise<T> {
		const previous = this.appendQueues.get(sessionId) ?? Promise.resolve();
		let release!: () => void;
		const current = new Promise<void>((resolve) => {
			release = resolve;
		});
		const queued = previous.then(() => current);
		this.appendQueues.set(sessionId, queued);
		await previous;
		try {
			return await operation();
		} finally {
			release();
			if (this.appendQueues.get(sessionId) === queued) this.appendQueues.delete(sessionId);
		}
	}

	private async append(sessionId: string, events: readonly SessionEventInput[]): Promise<readonly AgentSessionEvent[]> {
		return this.withAppendQueue(sessionId, async () => {
			const state = await this.sessionStore.fold(sessionId);
			const result = await this.sessionStore.append({ sessionId, expectedSequence: state.lastSequence, events });
			return result.events;
		});
	}

	private async requireSession(sessionId: string): Promise<SessionState> {
		const page = await this.sessionStore.read(sessionId, { afterSequence: 0, limit: 1 });
		if (page.lastSequence === 0) throw new ControlPlaneNotFoundError(`session ${sessionId} was not found`);
		return this.sessionStore.fold(sessionId);
	}

	private async requireOpenSession(sessionId: string): Promise<SessionState> {
		const state = await this.requireSession(sessionId);
		if (state.closed) throw new ControlPlaneContractError(`session ${sessionId} is closed`);
		return state;
	}

	private async createSession(request: ProtoRequestEnvelope, principal: string): Promise<SessionResponse> {
		const input = this.payload<CreateSessionRequest>(request, createSessionRequestSchema, "create-session");
		const sessionId = input.sessionId ?? randomUUID();
		const existing = await this.sessionStore.read(sessionId, { afterSequence: 0, limit: 1 });
		if (existing.lastSequence > 0) throw new SessionConcurrencyError(`session ${sessionId} already exists`);
		await this.append(sessionId, [
			eventInput(
				sessionId,
				"session.created",
				actor(principal),
				{
					principalId: principal,
					metadata: input.metadata ?? {},
				},
				request.requestId,
			),
		]);
		return { sessionId, created: true, state: await this.sessionStore.fold(sessionId) };
	}

	private async openSession(request: ProtoRequestEnvelope): Promise<SessionResponse> {
		const input = this.payload(request, openSessionRequestSchema, "open-session");
		return { sessionId: input.sessionId, state: await this.requireSession(input.sessionId) };
	}

	private async forkSession(request: ProtoRequestEnvelope, principal: string): Promise<SessionResponse> {
		const input = this.payload(request, forkSessionRequestSchema, "fork-session");
		await this.requireSession(input.parentSessionId);
		const sessionId = input.sessionId ?? randomUUID();
		const fork = await this.sessionStore.fork(input.parentSessionId, input.parentSequence, sessionId);
		await this.append(sessionId, [
			eventInput(
				sessionId,
				"session.created",
				actor(principal),
				{
					forked: true,
					parentSessionId: input.parentSessionId,
					parentSequence: input.parentSequence,
				},
				request.requestId,
			),
		]);
		return {
			sessionId,
			forkedFrom: { sessionId: fork.parentSessionId, sequence: fork.parentSequence },
			state: await this.sessionStore.fold(sessionId),
		};
	}

	private async inspectSession(request: ProtoRequestEnvelope): Promise<SessionResponse> {
		const input = this.payload(request, openSessionRequestSchema, "inspect-session");
		return { sessionId: input.sessionId, state: await this.requireSession(input.sessionId) };
	}

	private async submitTurn(request: ProtoRequestEnvelope, principal: string): Promise<TurnResponse> {
		const input = this.payload<SubmitTurnRequest>(request, submitTurnRequestSchema, "submit-turn");
		const sessionId = request.sessionId;
		if (!sessionId) throw new ControlPlaneContractError("submit-turn requires session_id");
		await this.requireOpenSession(sessionId);
		const turnId = input.turnId ?? randomUUID();
		await this.append(sessionId, [
			eventInput(sessionId, "turn.started", actor(principal), { turnId }, request.requestId, turnId),
			eventInput(sessionId, "message.user", actor(principal), input.content, `${request.requestId}:message`, turnId),
		]);
		this.startTurnExecution(sessionId, turnId, input.content, request.deadlineUnixMs);
		return { sessionId, turnId, accepted: true };
	}

	private startTurnExecution(
		sessionId: string,
		turnId: string,
		content: SessionJsonValue,
		deadlineUnixMs: string,
	): void {
		if (!this.options.executeTurn) return;
		const controller = new AbortController();
		const deadline = Number(deadlineUnixMs);
		const deadlineTimer =
			deadline > 0
				? setTimeout(() => controller.abort("turn deadline exceeded"), Math.max(0, deadline - Date.now()))
				: undefined;
		this.active.set(`turn:${turnId}`, { kind: "turn", targetId: turnId, sessionId, controller, deadlineTimer });
		void this.options
			.executeTurn({ sessionId, turnId, content, signal: controller.signal })
			.then(async (result) => {
				if (controller.signal.aborted) return;
				const events: SessionEventInput[] = [];
				if (result?.content !== undefined)
					events.push(
						eventInput(
							sessionId,
							"message.assistant",
							{ kind: "agent", id: "agent-kernel" },
							result.content,
							`turn:${turnId}:assistant`,
							turnId,
						),
					);
				events.push(
					eventInput(
						sessionId,
						"turn.completed",
						{ kind: "agent", id: "agent-kernel" },
						{ status: "completed" },
						`turn:${turnId}:completed`,
						turnId,
					),
				);
				await this.append(sessionId, events);
			})
			.catch(async (error: unknown) => {
				if (controller.signal.aborted) return;
				await this.append(sessionId, [
					eventInput(
						sessionId,
						"turn.completed",
						{ kind: "agent", id: "agent-kernel" },
						{
							status: "failed",
							error: error instanceof Error ? error.message : "turn failed",
						},
						`turn:${turnId}:failed`,
						turnId,
					),
				]);
			})
			.finally(() => {
				if (deadlineTimer) clearTimeout(deadlineTimer);
				this.active.delete(`turn:${turnId}`);
			});
	}

	private async steer(request: ProtoRequestEnvelope, principal: string): Promise<TurnResponse> {
		const input = this.payload<SteerTurnRequest>(request, steerTurnRequestSchema, "steer-turn");
		const sessionId = request.sessionId;
		if (!sessionId) throw new ControlPlaneContractError("steer-turn requires session_id");
		await this.requireOpenSession(sessionId);
		await this.append(sessionId, [
			eventInput(sessionId, "steering.received", actor(principal), input.content, request.requestId, input.turnId),
		]);
		if (this.options.steerTurn)
			await this.options.steerTurn({
				sessionId,
				turnId: input.turnId,
				content: input.content,
				signal: this.active.get(`turn:${input.turnId}`)?.controller.signal ?? new AbortController().signal,
			});
		return { sessionId, turnId: input.turnId, accepted: true };
	}

	private async startWorkflow(request: ProtoRequestEnvelope, principal: string): Promise<WorkflowResponse> {
		const input = this.payload<StartWorkflowRequest>(request, startWorkflowRequestSchema, "start-workflow");
		const sessionId = request.sessionId;
		if (!sessionId) throw new ControlPlaneContractError("start-workflow requires session_id");
		await this.requireOpenSession(sessionId);
		const workflowRunId = input.workflowRunId ?? randomUUID();
		await this.append(sessionId, [
			eventInput(
				sessionId,
				"workflow.run.started",
				actor(principal),
				{
					workflowRunId,
					workflowName: input.workflowName,
					...(input.input === undefined ? {} : { input: input.input }),
				},
				request.requestId,
			),
		]);
		if (this.options.executeWorkflow)
			this.startWorkflowExecution(sessionId, workflowRunId, input, request.deadlineUnixMs);
		return { sessionId, workflowRunId, accepted: true };
	}

	private startWorkflowExecution(
		sessionId: string,
		workflowRunId: string,
		input: StartWorkflowRequest,
		deadlineUnixMs: string,
	): void {
		const controller = new AbortController();
		const deadline = Number(deadlineUnixMs);
		const deadlineTimer =
			deadline > 0
				? setTimeout(() => controller.abort("workflow deadline exceeded"), Math.max(0, deadline - Date.now()))
				: undefined;
		this.active.set(`workflow:${workflowRunId}`, {
			kind: "workflow",
			targetId: workflowRunId,
			sessionId,
			controller,
			deadlineTimer,
		});
		void this.options
			.executeWorkflow?.({
				sessionId,
				workflowRunId,
				workflowName: input.workflowName,
				input: input.input,
				signal: controller.signal,
			})
			.then(async (result) => {
				if (controller.signal.aborted) return;
				await this.append(sessionId, [
					eventInput(
						sessionId,
						"workflow.run.completed",
						{ kind: "workflow", id: input.workflowName },
						{
							workflowRunId,
							...(result?.output === undefined ? {} : { output: result.output }),
						},
						`workflow:${workflowRunId}:completed`,
					),
				]);
			})
			.catch(async (error: unknown) => {
				if (controller.signal.aborted) return;
				await this.append(sessionId, [
					eventInput(
						sessionId,
						"workflow.run.failed",
						{ kind: "workflow", id: input.workflowName },
						{
							workflowRunId,
							error: error instanceof Error ? error.message : "workflow failed",
						},
						`workflow:${workflowRunId}:failed`,
					),
				]);
			})
			.finally(() => {
				if (deadlineTimer) clearTimeout(deadlineTimer);
				this.active.delete(`workflow:${workflowRunId}`);
			});
	}

	private async answerInteraction(
		request: ProtoRequestEnvelope,
		principal: string,
	): Promise<{ interactionId: string; status: string; sequence: number }> {
		const input = this.payload(request, answerInteractionRequestSchema, "answer-interaction");
		const answer = parseInteractionAnswerPayload(input.answer);
		const record = await this.interactionStore.answer({
			id: input.interactionId,
			principalId: principal,
			sequence: input.sequence,
			answer,
			deny: input.deny,
		});
		if (request.sessionId)
			await this.append(request.sessionId, [
				eventInput(
					request.sessionId,
					"approval.resolved",
					actor(principal),
					{
						approvalId: record.id,
						interactionId: record.id,
						status: record.status,
						sequence: record.sequence,
					},
					request.requestId,
				),
			]);
		return { interactionId: record.id, status: record.status, sequence: record.sequence };
	}

	private async resume(
		request: ProtoRequestEnvelope,
		principal: string,
	): Promise<{ interactionId: string; resumed: true; sequence: number }> {
		const input = this.payload<ResumeRequest>(request, resumeRequestSchema, "resume");
		const coordinator = new InteractionResumeCoordinator(
			this.interactionStore,
			async (policyRequest: PolicyRequest) => {
				await this.options.reauthorizeInteraction?.(policyRequest);
			},
		);
		let resumed: InteractionRecord | undefined;
		await coordinator.resume(
			{ id: input.interactionId, principalId: principal, sequence: input.sequence },
			async ({ interaction, answer }: { interaction: InteractionRecord; answer: unknown }) => {
				resumed = interaction;
				await this.options.resumeInteraction?.({
					interaction,
					answer: parseInteractionAnswerPayload(answer),
					sessionId: request.sessionId,
				});
			},
		);
		if (!resumed) throw new Error("interaction resume did not produce a record");
		if (request.sessionId)
			await this.append(request.sessionId, [
				eventInput(
					request.sessionId,
					"approval.resolved",
					actor(principal),
					{
						approvalId: resumed.id,
						interactionId: resumed.id,
						status: "resumed",
						sequence: resumed.sequence,
					},
					request.requestId,
				),
			]);
		return { interactionId: resumed.id, resumed: true, sequence: resumed.sequence };
	}

	private async cancel(
		request: ProtoRequestEnvelope,
		principal: string,
	): Promise<{ cancelled: true; target: CancellationTarget; targetId?: string }> {
		const input = this.payload<CancelRequest>(request, cancelRequestSchema, "cancel");
		const targetId = input.targetId ?? request.sessionId;
		if (input.target !== "session" && !targetId) throw new ControlPlaneContractError("cancel target_id is required");
		const entries = [...this.active.entries()].filter(([, operation]) =>
			input.target === "session"
				? operation.sessionId === targetId
				: operation.kind === input.target &&
					(targetId === undefined || operation.targetId === targetId) &&
					(!request.sessionId || operation.sessionId === request.sessionId),
		);
		for (const [key, operation] of entries) {
			operation.controller.abort(input.reason ?? `cancelled by ${principal}`);
			this.active.delete(key);
		}
		if (input.target === "session" && targetId) {
			await this.requireSession(targetId);
			await this.append(targetId, [
				eventInput(
					targetId,
					"session.closed",
					actor(principal),
					{ reason: input.reason ?? "cancelled" },
					request.requestId,
				),
			]);
		} else if (targetId && request.sessionId) {
			await this.requireSession(request.sessionId);
			if (input.target === "turn") {
				await this.append(request.sessionId, [
					eventInput(
						request.sessionId,
						"turn.completed",
						actor(principal),
						{ status: "cancelled", reason: input.reason ?? "cancelled" },
						request.requestId,
						targetId,
					),
				]);
			} else {
				await this.append(request.sessionId, [
					eventInput(
						request.sessionId,
						"workflow.run.failed",
						actor(principal),
						{ workflowRunId: targetId, status: "cancelled", reason: input.reason ?? "cancelled" },
						request.requestId,
					),
				]);
			}
		}
		return { cancelled: true, target: input.target, ...(targetId ? { targetId } : {}) };
	}

	private streamEvents(call: StreamCall): void {
		let stopped = false;
		let timer: ReturnType<typeof setTimeout> | undefined;
		const stop = (): void => {
			stopped = true;
			if (timer) clearTimeout(timer);
		};
		call.on("cancelled", stop);
		call.on("error", stop);
		void (async () => {
			this.authorize(call.metadata);
			const request = call.request;
			ensureSupportedVersion(request.contractVersion);
			requestId(request as unknown as ProtoRequestEnvelope);
			const input: StreamEventsRequest = parseRequest(
				streamEventsRequestSchema,
				{
					sessionId: request.sessionId,
					afterSequence: sequence(request.afterSequence, "after_sequence"),
					limit: request.limit || CONTROL_PLANE_DEFAULT_PAGE_SIZE,
					follow: request.follow,
				},
				"stream-events",
			);
			await this.requireSession(input.sessionId);
			let cursor = input.afterSequence ?? 0;
			let replayed = true;
			let previous = cursor;
			const deadline = Number(request.deadlineUnixMs ?? 0);
			const pump = async (): Promise<void> => {
				if (stopped) return;
				const page = await this.sessionStore.read(input.sessionId, {
					afterSequence: cursor,
					limit: input.limit ?? CONTROL_PLANE_DEFAULT_PAGE_SIZE,
				});
				const batchReplayed = replayed;
				for (const event of page.events) {
					if (event.sequence <= previous) continue;
					if (event.sequence !== previous + 1) throw new ControlPlaneContractError("event stream sequence gap");
					if (eventByteSize(event) > CONTROL_PLANE_MAX_EVENT_BYTES)
						throw new ControlPlaneTooLargeError("event exceeds the maximum size");
					call.write(this.eventWire(event, batchReplayed));
					previous = event.sequence;
					cursor = event.sequence;
				}
				replayed = false;
				if (!input.follow || stopped) {
					call.end();
					stop();
					return;
				}
				if (deadline > 0 && deadline <= Date.now()) {
					const error = new Error("control-plane stream deadline exceeded") as ServiceError;
					error.code = status.DEADLINE_EXCEEDED;
					call.destroy(error);
					stop();
					return;
				}
				timer = setTimeout(
					() =>
						void pump().catch((error: unknown) => {
							call.destroy(protocolError(error));
							stop();
						}),
					50,
				);
			};
			await pump();
		})().catch((error: unknown) => {
			call.destroy(protocolError(error));
			stop();
		});
	}

	private eventWire(event: AgentSessionEvent, replayed: boolean): ProtoEventEnvelope {
		return {
			contractVersion: CONTROL_PLANE_CONTRACT_VERSION,
			sessionId: event.sessionId,
			sequence: String(event.sequence),
			eventId: event.id,
			turnId: event.turnId ?? "",
			kind: event.kind,
			visibility: event.visibility,
			payloadJson: jsonBuffer(event.payload, CONTROL_PLANE_MAX_EVENT_BYTES, "event payload"),
			occurredAt: event.occurredAt,
			replayed,
			terminal:
				event.kind === "session.closed" ||
				event.kind === "turn.completed" ||
				event.kind === "workflow.run.completed" ||
				event.kind === "workflow.run.failed",
		};
	}
}

export { protoFileExists };
