// Code generated by blokctl. DO NOT EDIT.
//
// Default no-op shim. `blokctl dev` regenerates this in
// .blok/runtimes/csharp/src/Blok.Core with the user nodes scaffolded under
// runtimes/csharp/nodes. Committed so the SDK compiles without codegen — e.g.
// the cross-runtime CI build, which has no user nodes.
using Blok.Core.Node;

namespace Blok.Core;

/// <summary>
/// Registers user nodes scaffolded under runtimes/csharp/nodes.
/// </summary>
public static class UserNodeRegistry
{
    public static void RegisterUserNodes(NodeRegistry registry) { }
}
