// Code generated by blokctl. DO NOT EDIT.
//
// Default no-op shim. `blokctl dev` regenerates this in
// .blok/runtimes/java/src/main/java/com/blok/blok with the user nodes
// scaffolded under runtimes/java/nodes. Committed so the SDK compiles without
// codegen — e.g. the cross-runtime CI build, which has no user nodes.
package com.blok.blok;

import com.blok.blok.node.NodeRegistry;

public final class UserNodeRegistry {

    private UserNodeRegistry() {
    }

    /** Registers nodes scaffolded under runtimes/java/nodes. */
    public static void registerUserNodes(NodeRegistry registry) {
    }
}
