[supervisord]
nodaemon=true

[program:http_trigger]
command=bun run src/triggers/http/index.ts
directory=/app
environment=PORT="4000",HOST="0.0.0.0"
autostart=true
autorestart=true
stderr_logfile=/var/log/http_trigger.err.log
stdout_logfile=/var/log/http_trigger.out.log
