// AUTO-GENERATED by `blokctl gen app-types` — do not edit by hand.
import { registerRoutes } from "@blokjs/inertia-client";

registerRoutes({
	"orders.index": { url: "/orders", method: "get", component: "Orders/Index" },
	"orders.show": { url: "/orders/:id", method: "get", component: "Orders/Show" },
});
