// AUTO-GENERATED by `blokctl gen app-types` — do not edit by hand.
//
// Committed here so the example reads as a finished project; regenerate it with
//   cd ../backend && blokctl gen app-types --pages-only --out ../frontend/src
import "@blokjs/inertia-client";
import "@inertiajs/core";

declare module "@blokjs/inertia-client" {
	interface Pages {
		"Orders/Index": {
			auth: { id: string; email: string };
			orders: { id: string; sku: string; total: number }[];
		};
		"Orders/Show": {
			auth: { id: string; email: string };
			order: { id: string; sku: string; total: number };
		};
	}

	interface Routes {
		"orders.index": { method: "get"; path: "/orders"; component: "Orders/Index" };
		"orders.show": { params: { id: string }; method: "get"; path: "/orders/:id"; component: "Orders/Show" };
	}
}

declare module "@inertiajs/core" {
	interface InertiaConfig {
		sharedPageProps: { appName: string };
		flashDataType: Record<string, unknown>;
		errorValueType: string;
	}
}
