/**
 * @packageDocumentation
 * @deprecated Prefer `@blokjs/core`. These primitives (Context, mapper,
 * NodeBase, error envelopes, …) are re-exported from `@blokjs/core/runtime`, so
 * a project only needs the one package (#374/#378). `@blokjs/shared` stays
 * published as a back-compat alias — existing imports keep working unchanged —
 * but new code should import from `@blokjs/core`.
 */
import BlokError, {
	type BlokErrorOpts,
	DEFAULT_HTTP_STATUS,
	DEFAULT_RETRYABLE,
	ErrorCategory,
	ErrorSeverity,
	isNonRetryableError,
	isNonRetryableStepError,
	isNonRetryableValidationError,
	markNonRetryableStepError,
	type NodeErrorPayload,
	WORKFLOW_INPUT_VALIDATION,
	WorkflowInputValidationError,
	type WorkflowInputValidationInfo,
	type WorkflowInputValidationIssue,
} from "./BlokError";
import {
	CAPABILITY_CLASSIFICATIONS,
	CAPABILITY_DETERMINISM,
	CAPABILITY_EFFECTS,
	CAPABILITY_IDEMPOTENCY,
	CAPABILITY_MANIFEST_VERSION,
	CAPABILITY_MATURITY,
	type CapabilityClassification,
	type CapabilityDeterminism,
	type CapabilityEffect,
	type CapabilityIdempotency,
	type CapabilityManifestAssessment,
	CapabilityManifestError,
	type CapabilityManifestStatus,
	type CapabilityManifestV1,
	type CapabilityMaturity,
	type CapabilityResourceBounds,
	assessCapabilityManifest,
	parseCapabilityManifest,
	requireAgentEligibleManifest,
	serializeCapabilityManifest,
} from "./CapabilityManifest";
export {
	WASI_COMPONENT_CAPABILITIES,
	WASI_COMPONENT_CONTRACT_VERSION,
	WASI_COMPONENT_MANIFEST_VERSION,
	WASI_COMPONENT_MEDIA_TYPE,
	WASI_COMPONENT_WASI_VERSION,
	WASI_COMPONENT_WIT_PACKAGE,
	WASI_COMPONENT_WIT_VERSION,
	WASI_COMPONENT_WIT_WORLD,
	WasiComponentArtifactSchema,
	WasiComponentErrorSchema,
	WasiComponentExecutionRequestSchema,
	WasiComponentExecutionResponseSchema,
	WasiComponentLimitsSchema,
	WasiComponentManifestSchema,
	WasiComponentNodeSchema,
	WasiComponentWorldSchema,
	parseWasiComponentManifest,
	serializeWasiComponentManifest,
} from "./WasiComponentContracts";
export type {
	WasiComponentArtifact,
	WasiComponentExecutionRequest,
	WasiComponentExecutionResponse,
	WasiComponentLimits,
	WasiComponentManifestV1,
	WasiComponentNode,
	WasiComponentReadiness,
	WasiComponentWorld,
} from "./WasiComponentContracts";
import GlobalError from "./GlobalError";
import GlobalLogger from "./GlobalLogger";
import { Metrics, type MetricsType } from "./Metrics";
import NodeBase from "./NodeBase";
export {
	JAVASCRIPT_RUNTIMES,
	JavaScriptRuntimeSchema,
	JavaScriptRuntimeSelectionSchema,
	PackageManagerSchema,
	PACKAGE_MANAGERS,
	RUNTIME_KINDS,
	RuntimeCapabilityManifestSchema,
	RuntimeKindInputSchema,
	RuntimeKindSchema,
	normalizeJavaScriptRuntime,
	normalizeRuntimeKind,
	runtimeKindForJavaScriptRuntime,
} from "./RuntimeContracts";
export type {
	JavaScriptRuntime,
	JavaScriptRuntimeSelection,
	PackageManager,
	RuntimeCapabilityManifest,
	RuntimeDiagnostic,
	RuntimeKind,
	RuntimeKindInput,
	RuntimeNormalization,
} from "./RuntimeContracts";
export {
	CapabilityAuthorityError,
	CapabilityAuthoritySchema,
	CapabilityFragmentValueSchema,
	assertCapabilityAuthoritySubset,
	intersectCapabilityAuthorities,
	isCapabilityAuthoritySubset,
	parseCapabilityAuthority,
} from "./PermissionAlgebra";
export type { CapabilityAuthority } from "./PermissionAlgebra";
import Trigger from "./Trigger";
// These `types/*` modules are `type X = {...}; export default X;` — a type
// alias, not a runtime value (unlike `Trigger` above, a real class). Bun's
// per-file source loader (`bun -e import(...)`, in-monorepo scripts,
// bundler source-aliasing) can't see into the target file to know that; a
// plain value `import`/`export` of these names round-trips through a
// synthesized re-export that Bun rejects with "export default cannot be
// used with export *". `import type` here (and `type` on the corresponding
// `export { }` entries below) makes the type-only-ness explicit so no
// runtime binding is ever synthesized. See #702.
import type ConfigContext from "./types/ConfigContext";
import type ConnectionContext from "./types/ConnectionContext";
import type Context from "./types/Context";
import type EnvContext from "./types/EnvContext";
import type ErrorContext from "./types/ErrorContext";
import type FunctionContext from "./types/FunctionContext";
import type LoggerContext from "./types/LoggerContext";
import type NodeConfigContext from "./types/NodeConfigContext";
import type RequestContext from "./types/RequestContext";
import { RESPOND_BRAND, type RespondEnvelope, isRespondEnvelope } from "./types/RespondEnvelope";
import type ResponseContext from "./types/ResponseContext";
import type StateContext from "./types/StateContext";
import type Step from "./types/Step";
import type StreamContext from "./types/StreamContext";
import type VarsContext from "./types/VarsContext";
import mapper from "./utils/Mapper";
import { MapperResolutionError } from "./utils/MapperResolutionError";
import MemoryUsage from "./utils/MemoryUsage";
import { NamedMissingStateError } from "./utils/NamedMissingStateError";
import { type StructuralRef, type StructuralTpl, isStructuralRef, isStructuralTpl, lowerRefs } from "./utils/lowerRefs";
export {
	AGENT_CAPABILITY_CONTRACT_VERSION,
	CAPABILITY_MAX_ID_LENGTH,
	CAPABILITY_MAX_LIST_ITEMS,
	CAPABILITY_MAX_OUTPUT_CHUNK_BYTES,
	CAPABILITY_MAX_PATH_LENGTH,
	CapabilityContractError,
	CapabilityOwnerSchema,
	WorkspacePathRefSchema,
	assertAuthorized,
	assertOwned,
	capabilityScope,
	parseCapabilityAuthorization,
	parseCapabilityOwner,
	parseWorkspacePathRef,
} from "./CapabilityContracts";
export type {
	CapabilityAuthorizationPort,
	CapabilityOwner,
	CapabilityRequestContext,
	WorkspacePathRef,
} from "./CapabilityContracts";
export {
	GIT_CAPABILITY_CONTRACT_VERSION,
	GIT_DESTRUCTIVE_OPERATIONS,
	GIT_OPERATIONS,
	GIT_MAX_BRANCH_NAME_LENGTH,
	GIT_MAX_CHANGED_FILES,
	assertGitOperationAllowed,
	assertGitOwner,
	assertGitPolicyAllowed,
	gitCapabilityScope,
	parseGitDiffEvidence,
	parseGitDirtyState,
	parseGitOperation,
	parseGitRepositoryIdentity,
	parseGitWorktreeCreateRequest,
	parseGitWorktreeIdentity,
	workspacePathForGit,
} from "./GitCapabilityContracts";
export type {
	GitCapability,
	GitCapabilityRequest,
	GitChangeStatus,
	GitDiffEvidence,
	GitDiffFile,
	GitDirtyState,
	GitDestructiveOperation,
	GitOperation,
	GitRepositoryIdentity,
	GitRevisionIdentity,
	GitWorktreeCreateRequest,
	GitWorktreeCleanupRequest,
	GitWorktreeIdentity,
} from "./GitCapabilityContracts";
export {
	PROCESS_CAPABILITY_CONTRACT_VERSION,
	PROCESS_CAPABILITY_IDS,
	PROCESS_DEFAULT_LIMITS,
	assertBoundedOutputChunk,
	assertProcessOwner,
	assertProcessPolicyAllowed,
	assertProcessStartResult,
	parseProcessCancellationRequest,
	parseProcessHandle,
	parseProcessOutput,
	parseProcessOutputChunk,
	parseProcessOrphanCleanupRequest,
	parseProcessResult,
	parseProcessSpec,
	processCapabilityId,
	processCapabilityScope,
	processWorkspaceCwd,
} from "./ProcessCapabilityContracts";
export type {
	ExecutableProcessSpec,
	NetworkDestination,
	ProcessCapability,
	ProcessCapabilityId,
	ProcessCancellationRequest,
	ProcessEnvironmentBinding,
	ProcessHandle,
	ProcessHandleRequest,
	ProcessLifecycleStatus,
	ProcessNetworkPolicy,
	ProcessOrphanCleanupRequest,
	ProcessOutputChunk,
	ProcessOutputSnapshot,
	ProcessResourceLimits,
	ProcessResult,
	ProcessStartResult,
	ProcessSpec,
	ProcessSpecBase,
	ProcessStartRequest,
	ShellStringProcessSpec,
} from "./ProcessCapabilityContracts";
export type {
	AuditEventBase,
	AuditRedactionState,
	AuditSink,
	ExecutionOrigin,
	InteractionAttribution,
	InteractionRequest,
	InteractionSuspension,
	InteractionSuspensionPort,
	PolicyContext,
	PolicyDecision,
	PolicyDecisionKind,
	PolicyEvaluationResult,
	PolicyLayer,
	PolicyLayerName,
	PolicyProvider,
	PolicyRequest,
	PolicyRuleMatch,
	PostExecutionAuditEvent,
	PreExecutionAuditEvent,
	PrincipalIdentity,
	RequestedCapabilityScope,
	SandboxAttestation,
	SessionIdentity,
	StepIdentity,
	TurnIdentity,
	WorkflowIdentity,
} from "./PolicyContracts";
export type {
	AgentCompletionContract,
	AgentStepContract,
	ApprovalContract,
	AssertionGateContract,
	EvidenceGateContract,
	EvidenceGateRequirement,
	OutputTrust,
	TrustedEvidence,
} from "./EnforcementContracts";
export {
	ENFORCEMENT_CONTRACT_VERSION,
	EnforcementViolationError,
} from "./EnforcementContracts";
export type {
	EnforcementProfile,
	EnforcementProfileContract,
	EnforcementProfileSemantics,
} from "./EnforcementProfileContracts";
export {
	ENFORCEMENT_PROFILE_CONTRACT_VERSION,
	ENFORCEMENT_PROFILE_SEMANTICS,
	ENFORCEMENT_PROFILES,
	EnforcementProfileContractError,
	EnforcementProfileContractSchema,
	EnforcementProfileSchema,
	enforcementProfileSemantics,
	parseEnforcementProfile,
	parseEnforcementProfileContract,
	serializeEnforcementProfileContract,
} from "./EnforcementProfileContracts";
export type {
	BindingActorIdentity,
	BindingScalar,
	EnforcementOverrideAuthorization,
	EnforcementOverrideEvent,
	EnforcementOverrideScope,
	PinnedCapabilityManifestIdentity,
	PinnedModelConfigurationIdentity,
	PinnedNodeIdentity,
	PinnedPolicyIdentity,
	PinnedRuntimeIdentity,
	PinnedWorkflowRunContract,
	RepositoryIdentity,
	TrustedWorkflowSource,
	WorkflowBindingInputs,
	WorkflowBindingRule,
	WorkflowBindingRules,
	WorkflowBindingSelector,
	WorkflowReference,
	WorkflowRuntimeKind,
	WorkflowSourceKind,
} from "./WorkflowBindingContracts";
export {
	ENFORCEMENT_OVERRIDE_EVENT_VERSION,
	WORKFLOW_BINDING_CONTRACT_VERSION,
	WORKFLOW_BINDING_MAX_ATTRIBUTES,
	WORKFLOW_BINDING_MAX_CONTRACT_BYTES,
	WORKFLOW_BINDING_MAX_LABELS,
	WORKFLOW_BINDING_MAX_NODES,
	WORKFLOW_BINDING_MAX_PATHS,
	WORKFLOW_BINDING_MAX_RULES,
	WORKFLOW_BINDING_MAX_SCOPE_ITEMS,
	WORKFLOW_BINDING_MAX_STRING_LENGTH,
	WORKFLOW_BINDING_MAX_RUNTIMES,
	WORKFLOW_RUN_CONTRACT_VERSION,
	EnforcementOverrideEventSchema,
	EnforcementOverrideScopeSchema,
	PinnedWorkflowRunContractSchema,
	WorkflowBindingContractError,
	WorkflowBindingInputsSchema,
	WorkflowBindingRuleSchema,
	WorkflowBindingRulesSchema,
	WorkflowBindingSelectorSchema,
	isEnforcementProfile,
	parseEnforcementOverrideEvent,
	parsePinnedWorkflowRunContract,
	parseWorkflowBindingInputs,
	parseWorkflowBindingRule,
	parseWorkflowBindingRules,
	parseWorkflowBindingSelector,
	serializeEnforcementOverrideEvent,
	serializePinnedWorkflowRunContract,
	serializeWorkflowBindingInputs,
	serializeWorkflowBindingRule,
	serializeWorkflowBindingRules,
	WORKFLOW_RUNTIME_KINDS,
	WORKFLOW_SOURCE_KINDS,
} from "./WorkflowBindingContracts";
export type {
	SecretLease,
	SecretRef,
	SecretRequest,
	SecretResolutionAuditEvent,
	SecretResolutionFailure,
	SecretResolver,
} from "./SecretContracts";
export type {
	InteractionPayload,
	InteractionAnswer,
	InteractionRecord,
	InteractionStatus,
	InteractionStore,
} from "./InteractionContracts";
export type {
	ApprovalRequirement,
	ArtifactIdentity,
	ArtifactVersionIdentity,
	CompletionContract,
	CompletionRequirement,
	EvidenceArtifactIdentity,
	EvidenceCheck,
	EvidenceCheckOutcome,
	EvidenceKind,
	EvidencePayload,
	EvidenceProducerIdentity,
	EvidenceProducerKind,
	EvidenceProvenanceIdentity,
	EvidenceRecord,
	EvidenceRequirement,
	EvidenceVerificationMethod,
	EvidenceVerificationResult,
	EvidenceVerificationStatus,
	EvidenceVerifierIdentity,
	EvidenceVerifierKind,
} from "./EvidenceContracts";
export {
	ApprovalRequirementSchema,
	ArtifactIdentitySchema,
	ArtifactVersionIdentitySchema,
	CompletionContractSchema,
	CompletionRequirementSchema,
	EvidenceCheckSchema,
	EvidenceContractError,
	EvidenceProducerIdentitySchema,
	EvidenceProvenanceIdentitySchema,
	EvidenceRecordSchema,
	EvidenceRequirementSchema,
	EvidencePayloadSchema,
	EvidenceTraceIdentitySchema,
	EvidenceVerificationResultSchema,
	EvidenceVerifierIdentitySchema,
	EVIDENCE_CHECK_OUTCOMES,
	EVIDENCE_CONTRACT_VERSION,
	EVIDENCE_MAX_CHECKS,
	EVIDENCE_MAX_PAYLOAD_DEPTH,
	EVIDENCE_MAX_PAYLOAD_ITEMS,
	EVIDENCE_MAX_RECORD_BYTES,
	EVIDENCE_MAX_REQUIREMENTS,
	EVIDENCE_MAX_STRING_LENGTH,
	EVIDENCE_PRODUCER_KINDS,
	EVIDENCE_VERIFICATION_METHODS,
	EVIDENCE_VERIFICATION_STATUSES,
	EVIDENCE_VERIFIER_KINDS,
	parseCompletionContract,
	parseEvidencePayload,
	parseEvidenceRecord,
	rejectModelEvidence,
	serializeCompletionContract,
	serializeEvidenceRecord,
} from "./EvidenceContracts";
export type {
	EffectRetryEvidence,
	EffectRetryEvidenceOutcome,
	JoinBranchObligation,
	JoinBranchResult,
	JoinBranchStatus,
	JoinContract,
	JoinJsonSchema,
	JoinOutputDeclaration,
	JoinResult,
	RetryResumeEffect,
	RetryResumeIdempotencyContract,
	RetryResumeIdempotencyMode,
} from "./JoinContracts";
export {
	EffectRetryEvidenceSchema,
	JOIN_CONTRACT_VERSION,
	JOIN_MAX_BRANCHES,
	JOIN_MAX_CONTRACT_BYTES,
	JOIN_MAX_OUTPUTS,
	JOIN_MAX_SCHEMA_DEPTH,
	JoinBranchObligationSchema,
	JoinContractError,
	JoinContractSchema,
	JoinOutputDeclarationSchema,
	RETRY_RESUME_IDEMPOTENCY_CONTRACT_VERSION,
	RETRY_RESUME_MAX_ATTEMPTS,
	RETRY_RESUME_MAX_EVIDENCE,
	RETRY_RESUME_MAX_RESUMES,
	RetryResumeContractError,
	RetryResumeIdempotencyContractSchema,
	assertEffectRetryEvidence,
	assertJoinSatisfied,
	parseEffectRetryEvidence,
	parseJoinContract,
	parseRetryResumeIdempotencyContract,
	serializeJoinContract,
} from "./JoinContracts";
export {
	INTERACTION_MAX_LINEAGE_DEPTH,
	INTERACTION_MAX_LINEAGE_PATH,
	INTERACTION_MAX_PAYLOAD_BYTES,
	INTERACTION_MAX_PAYLOAD_DEPTH,
	INTERACTION_MAX_PAYLOAD_ITEMS,
	INTERACTION_MAX_STRING_LENGTH,
	INTERACTION_REDACTED_VALUE,
	INTERACTION_VERSION,
	InteractionContractError,
	fingerprintInteractionPayload,
	immutableInteractionSnapshot,
	parseInteractionAnswer,
	parseInteractionPayload,
	redactInteractionDecision,
	redactInteractionPayload,
	redactInteractionRequest,
	redactInteractionString,
} from "./InteractionContracts";
export type {
	AuthoritativeSourceReadRequest,
	AuthoritativeSourceReader,
	AuthoritativeSourceSnapshot,
	GraphError,
	GraphErrorCategory,
	GraphFreshness,
	GraphFreshnessState,
	GraphFreshnessRequest,
	GraphImpactRequest,
	GraphIndexFile,
	GraphIndexRequest,
	GraphIndexResponse,
	GraphIndexSource,
	GraphLocation,
	GraphProvenance,
	GraphProvider,
	GraphQueryOptions,
	GraphQueryResponse,
	GraphRange,
	GraphRelation,
	GraphRelationDirection,
	GraphRelationKind,
	GraphRelationRequest,
	GraphRepositoryIdentity,
	GraphResultState,
	GraphResultStatus,
	GraphScope,
	GraphSearchHit,
	GraphSearchKind,
	GraphSearchRequest,
	GraphSymbol,
	GraphSymbolKind,
	GraphSymbolRequest,
	GraphWorktreeIdentity,
} from "./GraphContracts";
export {
	GRAPH_CONTRACT_VERSION,
	GRAPH_FRESHNESS_STATES,
	GRAPH_INDEX_SOURCES,
	GRAPH_MAX_DEPTH,
	GRAPH_MAX_FILES_PER_INDEX,
	GRAPH_MAX_INDEX_BYTES,
	GRAPH_MAX_ITEMS,
	GRAPH_MAX_PATH_LENGTH,
	GRAPH_MAX_RESPONSE_BYTES,
	GRAPH_MAX_STRING_LENGTH,
	GRAPH_RELATION_DIRECTIONS,
	GRAPH_RELATION_KINDS,
	GRAPH_RESULT_STATES,
	GRAPH_SEARCH_KINDS,
	GRAPH_SYMBOL_KINDS,
	AuthoritativeSourceReadRequestSchema,
	AuthoritativeSourceSnapshotSchema,
	GraphContractError,
	GraphErrorSchema,
	GraphFreshnessSchema,
	GraphFreshnessRequestSchema,
	GraphImpactRequestSchema,
	GraphIndexFileSchema,
	GraphIndexRequestSchema,
	GraphLocationSchema,
	GraphProvenanceSchema,
	GraphRangeSchema,
	GraphRelationSchema,
	GraphRelationRequestSchema,
	GraphRepositoryIdentitySchema,
	GraphResultStatusSchema,
	GraphScopeSchema,
	GraphSearchHitSchema,
	GraphSearchRequestSchema,
	GraphSymbolSchema,
	GraphSymbolRequestSchema,
	GraphWorktreeIdentitySchema,
	parseAuthoritativeSourceReadRequest,
	parseGraphImpactRequest,
	parseGraphFreshnessRequest,
	parseGraphIndexRequest,
	parseGraphIndexResponse,
	parseGraphQueryResponse,
	parseGraphRelationRequest,
	parseGraphScope,
	parseGraphSearchRequest,
	parseGraphSymbolRequest,
	serializeGraphContract,
} from "./GraphContracts";
export type {
	AgentSessionActorKind,
	AgentSessionEvent,
	AgentSessionEventKind,
	AgentSessionEventVisibility,
	SessionEvent,
	AgentSessionEventKind as SessionEventKind,
	AgentSessionEventVisibility as SessionEventVisibility,
	AgentSessionActorKind as SessionActorKind,
	SessionActor,
	SessionJsonValue,
	SessionEventInput,
	SessionCursor,
	SessionEventPage,
	CorruptSessionTail,
	SessionSnapshot,
	SessionFork,
	SessionMessage,
	SessionState,
	SessionFoldOptions,
	AppendSessionEventsInput,
	AppendSessionEventsResult,
	SessionRetentionOptions,
	SessionStore,
	ArtifactReference,
} from "./AgentSessionContracts";
export {
	AGENT_SESSION_CONTRACT_VERSION,
	AGENT_SESSION_SCHEMA_VERSION,
	AGENT_SESSION_MAX_EVENT_BYTES,
	AGENT_SESSION_MAX_PAYLOAD_DEPTH,
	AGENT_SESSION_MAX_PAYLOAD_ITEMS,
	AGENT_SESSION_MAX_STRING_LENGTH,
	AGENT_SESSION_MAX_EVENTS_PER_APPEND,
	AGENT_SESSION_MAX_PAGE_SIZE,
	AGENT_SESSION_MAX_SNAPSHOT_BYTES,
	AGENT_SESSION_EVENT_KINDS,
	AgentSessionContractError,
	SessionConcurrencyError,
	SessionCorruptTailError,
	ArtifactReferenceSchema,
	SessionJsonValueSchema,
	SessionActorSchema,
	SessionEventSchema,
	SessionEventInputSchema,
	parseArtifactReference,
	parseSessionEvent,
	parseSessionEventInput,
	serializeSessionEvent,
	parseSessionCursor,
	cursorForSequence,
	immutableSessionSnapshot,
	fingerprintSessionEvent,
	foldSessionEvents,
} from "./AgentSessionContracts";

export {
	CAPABILITY_MANIFEST_VERSION,
	CAPABILITY_EFFECTS,
	CAPABILITY_CLASSIFICATIONS,
	CAPABILITY_DETERMINISM,
	CAPABILITY_IDEMPOTENCY,
	CAPABILITY_MATURITY,
	CapabilityManifestError,
	parseCapabilityManifest,
	serializeCapabilityManifest,
	assessCapabilityManifest,
	requireAgentEligibleManifest,
	type CapabilityEffect,
	type CapabilityClassification,
	type CapabilityDeterminism,
	type CapabilityIdempotency,
	type CapabilityMaturity,
	type CapabilityResourceBounds,
	type CapabilityManifestV1,
	type CapabilityManifestStatus,
	type CapabilityManifestAssessment,
	NodeBase,
	type Context,
	type RequestContext,
	type ResponseContext,
	RESPOND_BRAND,
	type RespondEnvelope,
	isRespondEnvelope,
	type EnvContext,
	type ErrorContext,
	type LoggerContext,
	type ConfigContext,
	type ConnectionContext,
	type StreamContext,
	Trigger,
	type NodeConfigContext,
	type FunctionContext,
	type StateContext,
	type VarsContext,
	type Step,
	GlobalLogger,
	GlobalError,
	BlokError,
	type BlokErrorOpts,
	type NodeErrorPayload,
	ErrorCategory,
	ErrorSeverity,
	DEFAULT_HTTP_STATUS,
	DEFAULT_RETRYABLE,
	isNonRetryableValidationError,
	// #679 — the ONE non-retryable matcher plus the marker the runner uses to
	// hand its verdict to the transports, so step-level and job-level retry can
	// never disagree.
	isNonRetryableError,
	markNonRetryableStepError,
	isNonRetryableStepError,
	WORKFLOW_INPUT_VALIDATION,
	WorkflowInputValidationError,
	type WorkflowInputValidationInfo,
	type WorkflowInputValidationIssue,
	Metrics,
	MemoryUsage,
	type MetricsType,
	mapper,
	MapperResolutionError,
	NamedMissingStateError,
	lowerRefs,
	// The lowering pass's OWN predicates — exported so the normalizer's
	// post-lowering total invariant (#707) tests the identical rule instead of
	// a second hand-written copy that could drift from what `lowerRefs` lowers.
	isStructuralRef,
	isStructuralTpl,
	type StructuralRef,
	type StructuralTpl,
};
