// Code generated by blokctl. DO NOT EDIT.
//
// Default no-op shim. `blokctl dev` regenerates this in
// .blok/runtimes/go/cmd/server with the user nodes scaffolded under
// runtimes/go/nodes. Committed so the SDK compiles without codegen — e.g. the
// cross-runtime CI build, which has no user nodes.
package main

import blok "github.com/nickincloud/blok-go"

// registerUserNodes registers nodes scaffolded under runtimes/go/nodes.
func registerUserNodes(registry *blok.NodeRegistry) {}
