// Blok Runtime v1 — the wire contract between the TypeScript runner and SDK
// servers (Python, Go, Rust, Java, C#, PHP, Ruby).
//
// Single source of truth for cross-language interop. Generated stubs in each
// SDK are derived from this file via `make proto`.
//
// Stability: `blok.runtime.v1` is additive-only. CI runs `buf breaking` to
// reject backward-incompatible changes. Breaking changes go to `v2`, served
// alongside `v1` during migration.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.0
// source: blok/runtime/v1/runtime.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeRuntime_Execute_FullMethodName       = "/blok.runtime.v1.NodeRuntime/Execute"
	NodeRuntime_ExecuteStream_FullMethodName = "/blok.runtime.v1.NodeRuntime/ExecuteStream"
	NodeRuntime_Health_FullMethodName        = "/blok.runtime.v1.NodeRuntime/Health"
	NodeRuntime_ListNodes_FullMethodName     = "/blok.runtime.v1.NodeRuntime/ListNodes"
)

// NodeRuntimeClient is the client API for NodeRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeRuntime is the contract every Blok SDK exposes. One service handles
// three responsibilities:
//  1. Run a node (Execute / ExecuteStream)
//  2. Tell the runner which nodes it can run (ListNodes)
//  3. Tell the runner if it is alive (Health)
type NodeRuntimeClient interface {
	// Run a node and return its result. Unary, deadline-driven.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Run a node and stream events back as it executes (logs, progress, partial
	// results, then a final ExecuteResponse). Optional capability — SDKs that
	// don't implement it should return UNIMPLEMENTED.
	ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteEvent], error)
	// Health check (wire-compatible with grpc.health.v1.Health/Check).
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Discover registered nodes and their schemas (drives Studio + OpenAPI gen).
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type nodeRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeRuntimeClient(cc grpc.ClientConnInterface) NodeRuntimeClient {
	return &nodeRuntimeClient{cc}
}

func (c *nodeRuntimeClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, NodeRuntime_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeClient) ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeRuntime_ServiceDesc.Streams[0], NodeRuntime_ExecuteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeRuntime_ExecuteStreamClient = grpc.ServerStreamingClient[ExecuteEvent]

func (c *nodeRuntimeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NodeRuntime_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRuntimeClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, NodeRuntime_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeRuntimeServer is the server API for NodeRuntime service.
// All implementations must embed UnimplementedNodeRuntimeServer
// for forward compatibility.
//
// NodeRuntime is the contract every Blok SDK exposes. One service handles
// three responsibilities:
//  1. Run a node (Execute / ExecuteStream)
//  2. Tell the runner which nodes it can run (ListNodes)
//  3. Tell the runner if it is alive (Health)
type NodeRuntimeServer interface {
	// Run a node and return its result. Unary, deadline-driven.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Run a node and stream events back as it executes (logs, progress, partial
	// results, then a final ExecuteResponse). Optional capability — SDKs that
	// don't implement it should return UNIMPLEMENTED.
	ExecuteStream(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteEvent]) error
	// Health check (wire-compatible with grpc.health.v1.Health/Check).
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Discover registered nodes and their schemas (drives Studio + OpenAPI gen).
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	mustEmbedUnimplementedNodeRuntimeServer()
}

// UnimplementedNodeRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeRuntimeServer struct{}

func (UnimplementedNodeRuntimeServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedNodeRuntimeServer) ExecuteStream(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteEvent]) error {
	return status.Error(codes.Unimplemented, "method ExecuteStream not implemented")
}
func (UnimplementedNodeRuntimeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedNodeRuntimeServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedNodeRuntimeServer) mustEmbedUnimplementedNodeRuntimeServer() {}
func (UnimplementedNodeRuntimeServer) testEmbeddedByValue()                     {}

// UnsafeNodeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeRuntimeServer will
// result in compilation errors.
type UnsafeNodeRuntimeServer interface {
	mustEmbedUnimplementedNodeRuntimeServer()
}

func RegisterNodeRuntimeServer(s grpc.ServiceRegistrar, srv NodeRuntimeServer) {
	// If the following call panics, it indicates UnimplementedNodeRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeRuntime_ServiceDesc, srv)
}

func _NodeRuntime_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntime_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntime_ExecuteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeRuntimeServer).ExecuteStream(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeRuntime_ExecuteStreamServer = grpc.ServerStreamingServer[ExecuteEvent]

func _NodeRuntime_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntime_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRuntime_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRuntimeServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRuntime_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRuntimeServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeRuntime_ServiceDesc is the grpc.ServiceDesc for NodeRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blok.runtime.v1.NodeRuntime",
	HandlerType: (*NodeRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _NodeRuntime_Execute_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _NodeRuntime_Health_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _NodeRuntime_ListNodes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStream",
			Handler:       _NodeRuntime_ExecuteStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blok/runtime/v1/runtime.proto",
}
