// Blok Runtime v1 — the wire contract between the TypeScript runner and SDK
// servers (Python, Go, Rust, Java, C#, PHP, Ruby).
//
// Single source of truth for cross-language interop. Generated stubs in each
// SDK are derived from this file via `make proto`.
//
// Stability: `blok.runtime.v1` is additive-only. CI runs `buf breaking` to
// reject backward-incompatible changes. Breaking changes go to `v2`, served
// alongside `v1` during migration.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: blok/runtime/v1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCategory int32

const (
	ErrorCategory_CATEGORY_UNSPECIFIED ErrorCategory = 0
	ErrorCategory_VALIDATION           ErrorCategory = 1 // input/output schema mismatch
	ErrorCategory_CONFIGURATION        ErrorCategory = 2 // node misconfigured
	ErrorCategory_DEPENDENCY           ErrorCategory = 3 // external service failed (DB, HTTP, queue)
	ErrorCategory_TIMEOUT              ErrorCategory = 4
	ErrorCategory_PERMISSION           ErrorCategory = 5 // auth/authz
	ErrorCategory_RATE_LIMIT           ErrorCategory = 6
	ErrorCategory_NOT_FOUND            ErrorCategory = 7
	ErrorCategory_CONFLICT             ErrorCategory = 8
	ErrorCategory_CANCELLED            ErrorCategory = 9
	ErrorCategory_INTERNAL             ErrorCategory = 10 // unexpected SDK-side bug
	ErrorCategory_PROTOCOL             ErrorCategory = 11 // proto/transport issue
	ErrorCategory_DATA                 ErrorCategory = 12 // user data malformed (not schema validation)
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0:  "CATEGORY_UNSPECIFIED",
		1:  "VALIDATION",
		2:  "CONFIGURATION",
		3:  "DEPENDENCY",
		4:  "TIMEOUT",
		5:  "PERMISSION",
		6:  "RATE_LIMIT",
		7:  "NOT_FOUND",
		8:  "CONFLICT",
		9:  "CANCELLED",
		10: "INTERNAL",
		11: "PROTOCOL",
		12: "DATA",
	}
	ErrorCategory_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"VALIDATION":           1,
		"CONFIGURATION":        2,
		"DEPENDENCY":           3,
		"TIMEOUT":              4,
		"PERMISSION":           5,
		"RATE_LIMIT":           6,
		"NOT_FOUND":            7,
		"CONFLICT":             8,
		"CANCELLED":            9,
		"INTERNAL":             10,
		"PROTOCOL":             11,
		"DATA":                 12,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_blok_runtime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_blok_runtime_v1_runtime_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type ErrorSeverity int32

const (
	ErrorSeverity_SEVERITY_UNSPECIFIED ErrorSeverity = 0
	ErrorSeverity_INFO                 ErrorSeverity = 1 // expected, recoverable
	ErrorSeverity_WARN                 ErrorSeverity = 2 // anomalous but workflow continues
	ErrorSeverity_ERROR                ErrorSeverity = 3 // node failed; default
	ErrorSeverity_FATAL                ErrorSeverity = 4 // workflow should abort regardless of try/catch
)

// Enum value maps for ErrorSeverity.
var (
	ErrorSeverity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
		4: "FATAL",
	}
	ErrorSeverity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"INFO":                 1,
		"WARN":                 2,
		"ERROR":                3,
		"FATAL":                4,
	}
)

func (x ErrorSeverity) Enum() *ErrorSeverity {
	p := new(ErrorSeverity)
	*p = x
	return p
}

func (x ErrorSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_blok_runtime_v1_runtime_proto_enumTypes[1].Descriptor()
}

func (ErrorSeverity) Type() protoreflect.EnumType {
	return &file_blok_runtime_v1_runtime_proto_enumTypes[1]
}

func (x ErrorSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorSeverity.Descriptor instead.
func (ErrorSeverity) EnumDescriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_blok_runtime_v1_runtime_proto_enumTypes[2].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_blok_runtime_v1_runtime_proto_enumTypes[2]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{18, 0}
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification: which node, what type, what version.
	Node *NodeRef `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// The node's own resolved inputs. Already mapped (js/, ${...} resolved).
	// Bytes-encoded JSON: SDKs JSON-decode lazily. NEVER wrapped in {inputs:...}.
	Inputs []byte `protobuf:"bytes,2,opt,name=inputs,proto3" json:"inputs,omitempty"`
	// Where in the workflow this node sits.
	Step *StepInfo `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	// The originating workflow trigger (read-only context for nodes).
	Trigger *TriggerInfo `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// Mutable state: previous step output, persistent vars, env mirror.
	State *RuntimeState `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// Identity of the parent workflow run.
	Workflow *WorkflowInfo `protobuf:"bytes,6,opt,name=workflow,proto3" json:"workflow,omitempty"`
	// Per-call options (deadline, streaming opt-in).
	Options       *ExecuteOptions `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetNode() *NodeRef {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ExecuteRequest) GetInputs() []byte {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecuteRequest) GetStep() *StepInfo {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *ExecuteRequest) GetTrigger() *TriggerInfo {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *ExecuteRequest) GetState() *RuntimeState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ExecuteRequest) GetWorkflow() *WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *ExecuteRequest) GetOptions() *ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type NodeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // e.g. "tutorial-store"
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`       // "runtime.python3"
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // optional pin, e.g. "1.0.0"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRef) Reset() {
	*x = NodeRef{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRef) ProtoMessage() {}

func (x *NodeRef) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRef.ProtoReflect.Descriptor instead.
func (*NodeRef) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StepInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // step name in workflow
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // 0-based index in current branch
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"` // total steps in current branch
	Depth         int32                  `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"` // 0 = top-level; 1+ = nested in flow node (if-else)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepInfo) Reset() {
	*x = StepInfo{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepInfo) ProtoMessage() {}

func (x *StepInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepInfo.ProtoReflect.Descriptor instead.
func (*StepInfo) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *StepInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StepInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StepInfo) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type TriggerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot of the trigger that started the workflow. Read-only for nodes.
	Body          []byte            `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"` // raw bytes; encoding signaled in headers
	Headers       map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Params        map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Query         map[string]string `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cookies       map[string]string `protobuf:"bytes,5,rep,name=cookies,proto3" json:"cookies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Method        string            `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Url           string            `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	BaseUrl       string            `protobuf:"bytes,8,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	TriggerKind   string            `protobuf:"bytes,9,opt,name=trigger_kind,json=triggerKind,proto3" json:"trigger_kind,omitempty"` // "http" | "worker" | "cron" | ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerInfo) Reset() {
	*x = TriggerInfo{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerInfo) ProtoMessage() {}

func (x *TriggerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerInfo.ProtoReflect.Descriptor instead.
func (*TriggerInfo) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerInfo) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TriggerInfo) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TriggerInfo) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *TriggerInfo) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *TriggerInfo) GetCookies() map[string]string {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *TriggerInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TriggerInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TriggerInfo) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *TriggerInfo) GetTriggerKind() string {
	if x != nil {
		return x.TriggerKind
	}
	return ""
}

type RuntimeState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output of the previous step. Named explicitly so LLM-authored nodes stop
	// confusing it with vars. Bytes-encoded JSON.
	PreviousOutput []byte `protobuf:"bytes,1,opt,name=previous_output,json=previousOutput,proto3" json:"previous_output,omitempty"`
	// Workflow-scoped persistent storage (set_var: true on prior steps).
	// Bytes-encoded JSON map<string, any>.
	Vars []byte `protobuf:"bytes,2,opt,name=vars,proto3" json:"vars,omitempty"`
	// String→string env mirror.
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeState) Reset() {
	*x = RuntimeState{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeState) ProtoMessage() {}

func (x *RuntimeState) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeState.ProtoReflect.Descriptor instead.
func (*RuntimeState) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeState) GetPreviousOutput() []byte {
	if x != nil {
		return x.PreviousOutput
	}
	return nil
}

func (x *RuntimeState) GetVars() []byte {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *RuntimeState) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type WorkflowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInfo) Reset() {
	*x = WorkflowInfo{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInfo) ProtoMessage() {}

func (x *WorkflowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInfo.ProtoReflect.Descriptor instead.
func (*WorkflowInfo) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowInfo) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkflowInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkflowInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type ExecuteOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeadlineMs     int64                  `protobuf:"varint,1,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"` // hard cutoff (also enforced via gRPC deadline)
	StreamLogs     bool                   `protobuf:"varint,2,opt,name=stream_logs,json=streamLogs,proto3" json:"stream_logs,omitempty"` // hint: caller wants ExecuteStream events
	CaptureMetrics bool                   `protobuf:"varint,3,opt,name=capture_metrics,json=captureMetrics,proto3" json:"capture_metrics,omitempty"`
	// Reserved for future routing/affinity hints without bumping schema.
	Hints         map[string]string `protobuf:"bytes,15,rep,name=hints,proto3" json:"hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOptions) Reset() {
	*x = ExecuteOptions{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOptions) ProtoMessage() {}

func (x *ExecuteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOptions.ProtoReflect.Descriptor instead.
func (*ExecuteOptions) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteOptions) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *ExecuteOptions) GetStreamLogs() bool {
	if x != nil {
		return x.StreamLogs
	}
	return false
}

func (x *ExecuteOptions) GetCaptureMetrics() bool {
	if x != nil {
		return x.CaptureMetrics
	}
	return false
}

func (x *ExecuteOptions) GetHints() map[string]string {
	if x != nil {
		return x.Hints
	}
	return nil
}

type ExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// The node's primary return value. Bytes-encoded JSON.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Optional content-type override (default "application/json").
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Set iff !success. Always populated on failure (see NodeError).
	Error *NodeError `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Vars the node wants persisted (merged into ctx.vars on the runner side).
	// Optional — most nodes leave this empty and rely on workflow-level set_var.
	// Bytes-encoded JSON map<string, any>.
	VarsDelta []byte `protobuf:"bytes,5,opt,name=vars_delta,json=varsDelta,proto3" json:"vars_delta,omitempty"`
	// Tail of logs captured during execution.
	Logs []*LogLine `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	// Resource usage during this call. Populated when capture_metrics=true.
	Metrics       *Metrics `protobuf:"bytes,7,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteResponse) GetError() *NodeError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecuteResponse) GetVarsDelta() []byte {
	if x != nil {
		return x.VarsDelta
	}
	return nil
}

func (x *ExecuteResponse) GetLogs() []*LogLine {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ExecuteResponse) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ExecuteEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteEvent_Started
	//	*ExecuteEvent_Log
	//	*ExecuteEvent_Progress
	//	*ExecuteEvent_Partial
	//	*ExecuteEvent_Final
	Event         isExecuteEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteEvent) GetEvent() isExecuteEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteEvent) GetStarted() *NodeStarted {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *ExecuteEvent) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *ExecuteEvent) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ExecuteEvent) GetPartial() *PartialResult {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Partial); ok {
			return x.Partial
		}
	}
	return nil
}

func (x *ExecuteEvent) GetFinal() *ExecuteResponse {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Final); ok {
			return x.Final
		}
	}
	return nil
}

type isExecuteEvent_Event interface {
	isExecuteEvent_Event()
}

type ExecuteEvent_Started struct {
	Started *NodeStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type ExecuteEvent_Log struct {
	Log *LogLine `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type ExecuteEvent_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type ExecuteEvent_Partial struct {
	Partial *PartialResult `protobuf:"bytes,4,opt,name=partial,proto3,oneof"`
}

type ExecuteEvent_Final struct {
	Final *ExecuteResponse `protobuf:"bytes,5,opt,name=final,proto3,oneof"` // last frame; closes the stream
}

func (*ExecuteEvent_Started) isExecuteEvent_Event() {}

func (*ExecuteEvent_Log) isExecuteEvent_Event() {}

func (*ExecuteEvent_Progress) isExecuteEvent_Event() {}

func (*ExecuteEvent_Partial) isExecuteEvent_Event() {}

func (*ExecuteEvent_Final) isExecuteEvent_Event() {}

type NodeStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStarted) Reset() {
	*x = NodeStarted{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStarted) ProtoMessage() {}

func (x *NodeStarted) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStarted.ProtoReflect.Descriptor instead.
func (*NodeStarted) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *NodeStarted) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       float64                `protobuf:"fixed64,1,opt,name=percent,proto3" json:"percent,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *Progress) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Progress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type PartialResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotJson  []byte                 `protobuf:"bytes,1,opt,name=snapshot_json,json=snapshotJson,proto3" json:"snapshot_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialResult) Reset() {
	*x = PartialResult{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialResult) ProtoMessage() {}

func (x *PartialResult) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialResult.ProtoReflect.Descriptor instead.
func (*PartialResult) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *PartialResult) GetSnapshotJson() []byte {
	if x != nil {
		return x.SnapshotJson
	}
	return nil
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // "debug" | "info" | "warn" | "error"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *LogLine) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type NodeError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// === Identity ===
	Code     string        `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // STABLE machine identifier (e.g. "POSTGRES_CONNECT_TIMEOUT")
	Category ErrorCategory `protobuf:"varint,2,opt,name=category,proto3,enum=blok.runtime.v1.ErrorCategory" json:"category,omitempty"`
	Severity ErrorSeverity `protobuf:"varint,3,opt,name=severity,proto3,enum=blok.runtime.v1.ErrorSeverity" json:"severity,omitempty"`
	// === Origin (auto-filled by SDK) ===
	Node        string                 `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Sdk         string                 `protobuf:"bytes,5,opt,name=sdk,proto3" json:"sdk,omitempty"` // "blok-python3"
	SdkVersion  string                 `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	RuntimeKind string                 `protobuf:"bytes,7,opt,name=runtime_kind,json=runtimeKind,proto3" json:"runtime_kind,omitempty"` // "runtime.python3"
	At          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=at,proto3" json:"at,omitempty"`
	// === Human-readable ===
	Message     string `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`          // one-sentence summary
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"` // multi-paragraph context
	Remediation string `protobuf:"bytes,11,opt,name=remediation,proto3" json:"remediation,omitempty"` // suggested next step
	DocUrl      string `protobuf:"bytes,12,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	// === Causality ===
	Causes              []*NodeError `protobuf:"bytes,13,rep,name=causes,proto3" json:"causes,omitempty"`
	Stack               string       `protobuf:"bytes,14,opt,name=stack,proto3" json:"stack,omitempty"`
	ContextSnapshotJson []byte       `protobuf:"bytes,15,opt,name=context_snapshot_json,json=contextSnapshotJson,proto3" json:"context_snapshot_json,omitempty"`
	// === Compatibility / retry hints ===
	HttpStatus   int32 `protobuf:"varint,16,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	Retryable    bool  `protobuf:"varint,17,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RetryAfterMs int64 `protobuf:"varint,18,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	// === Category-specific structured details ===
	// Bytes-encoded JSON. Surfaces to GlobalError.json on the runner side.
	DetailsJson   []byte `protobuf:"bytes,19,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeError) Reset() {
	*x = NodeError{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeError) ProtoMessage() {}

func (x *NodeError) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeError.ProtoReflect.Descriptor instead.
func (*NodeError) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *NodeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NodeError) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_CATEGORY_UNSPECIFIED
}

func (x *NodeError) GetSeverity() ErrorSeverity {
	if x != nil {
		return x.Severity
	}
	return ErrorSeverity_SEVERITY_UNSPECIFIED
}

func (x *NodeError) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeError) GetSdk() string {
	if x != nil {
		return x.Sdk
	}
	return ""
}

func (x *NodeError) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *NodeError) GetRuntimeKind() string {
	if x != nil {
		return x.RuntimeKind
	}
	return ""
}

func (x *NodeError) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *NodeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NodeError) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *NodeError) GetDocUrl() string {
	if x != nil {
		return x.DocUrl
	}
	return ""
}

func (x *NodeError) GetCauses() []*NodeError {
	if x != nil {
		return x.Causes
	}
	return nil
}

func (x *NodeError) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

func (x *NodeError) GetContextSnapshotJson() []byte {
	if x != nil {
		return x.ContextSnapshotJson
	}
	return nil
}

func (x *NodeError) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *NodeError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *NodeError) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *NodeError) GetDetailsJson() []byte {
	if x != nil {
		return x.DetailsJson
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{14}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeDescriptor      `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	SdkName       string                 `protobuf:"bytes,2,opt,name=sdk_name,json=sdkName,proto3" json:"sdk_name,omitempty"` // "blok-python3"
	SdkVersion    string                 `protobuf:"bytes,3,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	ProtoVersion  string                 `protobuf:"bytes,4,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"` // "1.0.0"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *ListNodesResponse) GetNodes() []*NodeDescriptor {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetSdkName() string {
	if x != nil {
		return x.SdkName
	}
	return ""
}

func (x *ListNodesResponse) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ListNodesResponse) GetProtoVersion() string {
	if x != nil {
		return x.ProtoVersion
	}
	return ""
}

type NodeDescriptor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchemaJson  []byte                 `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"` // JSON Schema (drives OpenAPI/Studio/LLMs)
	OutputSchemaJson []byte                 `protobuf:"bytes,4,opt,name=output_schema_json,json=outputSchemaJson,proto3" json:"output_schema_json,omitempty"`
	Tags             []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeDescriptor) Reset() {
	*x = NodeDescriptor{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDescriptor) ProtoMessage() {}

func (x *NodeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDescriptor.ProtoReflect.Descriptor instead.
func (*NodeDescriptor) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *NodeDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NodeDescriptor) GetInputSchemaJson() []byte {
	if x != nil {
		return x.InputSchemaJson
	}
	return nil
}

func (x *NodeDescriptor) GetOutputSchemaJson() []byte {
	if x != nil {
		return x.OutputSchemaJson
	}
	return nil
}

func (x *NodeDescriptor) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=blok.runtime.v1.HealthResponse_Status" json:"status,omitempty"`
	SdkVersion      string                 `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	RegisteredNodes []string               `protobuf:"bytes,3,rep,name=registered_nodes,json=registeredNodes,proto3" json:"registered_nodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *HealthResponse) GetRegisteredNodes() []string {
	if x != nil {
		return x.RegisteredNodes
	}
	return nil
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    float64                `protobuf:"fixed64,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CpuMs         float64                `protobuf:"fixed64,2,opt,name=cpu_ms,json=cpuMs,proto3" json:"cpu_ms,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	RequestBytes  int64                  `protobuf:"varint,4,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	ResponseBytes int64                  `protobuf:"varint,5,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_blok_runtime_v1_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_blok_runtime_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *Metrics) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Metrics) GetCpuMs() float64 {
	if x != nil {
		return x.CpuMs
	}
	return 0
}

func (x *Metrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Metrics) GetRequestBytes() int64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *Metrics) GetResponseBytes() int64 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

var File_blok_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_blok_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1dblok/runtime/v1/runtime.proto\x12\x0fblok.runtime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x02\n" +
	"\x0eExecuteRequest\x12,\n" +
	"\x04node\x18\x01 \x01(\v2\x18.blok.runtime.v1.NodeRefR\x04node\x12\x16\n" +
	"\x06inputs\x18\x02 \x01(\fR\x06inputs\x12-\n" +
	"\x04step\x18\x03 \x01(\v2\x19.blok.runtime.v1.StepInfoR\x04step\x126\n" +
	"\atrigger\x18\x04 \x01(\v2\x1c.blok.runtime.v1.TriggerInfoR\atrigger\x123\n" +
	"\x05state\x18\x05 \x01(\v2\x1d.blok.runtime.v1.RuntimeStateR\x05state\x129\n" +
	"\bworkflow\x18\x06 \x01(\v2\x1d.blok.runtime.v1.WorkflowInfoR\bworkflow\x129\n" +
	"\aoptions\x18\a \x01(\v2\x1f.blok.runtime.v1.ExecuteOptionsR\aoptions\"K\n" +
	"\aNodeRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"`\n" +
	"\bStepInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\"\x81\x05\n" +
	"\vTriggerInfo\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12C\n" +
	"\aheaders\x18\x02 \x03(\v2).blok.runtime.v1.TriggerInfo.HeadersEntryR\aheaders\x12@\n" +
	"\x06params\x18\x03 \x03(\v2(.blok.runtime.v1.TriggerInfo.ParamsEntryR\x06params\x12=\n" +
	"\x05query\x18\x04 \x03(\v2'.blok.runtime.v1.TriggerInfo.QueryEntryR\x05query\x12C\n" +
	"\acookies\x18\x05 \x03(\v2).blok.runtime.v1.TriggerInfo.CookiesEntryR\acookies\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x19\n" +
	"\bbase_url\x18\b \x01(\tR\abaseUrl\x12!\n" +
	"\ftrigger_kind\x18\t \x01(\tR\vtriggerKind\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fCookiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\fRuntimeState\x12'\n" +
	"\x0fprevious_output\x18\x01 \x01(\fR\x0epreviousOutput\x12\x12\n" +
	"\x04vars\x18\x02 \x01(\fR\x04vars\x128\n" +
	"\x03env\x18\x03 \x03(\v2&.blok.runtime.v1.RuntimeState.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\fWorkflowInfo\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xf7\x01\n" +
	"\x0eExecuteOptions\x12\x1f\n" +
	"\vdeadline_ms\x18\x01 \x01(\x03R\n" +
	"deadlineMs\x12\x1f\n" +
	"\vstream_logs\x18\x02 \x01(\bR\n" +
	"streamLogs\x12'\n" +
	"\x0fcapture_metrics\x18\x03 \x01(\bR\x0ecaptureMetrics\x12@\n" +
	"\x05hints\x18\x0f \x03(\v2*.blok.runtime.v1.ExecuteOptions.HintsEntryR\x05hints\x1a8\n" +
	"\n" +
	"HintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x02\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x120\n" +
	"\x05error\x18\x04 \x01(\v2\x1a.blok.runtime.v1.NodeErrorR\x05error\x12\x1d\n" +
	"\n" +
	"vars_delta\x18\x05 \x01(\fR\tvarsDelta\x12,\n" +
	"\x04logs\x18\x06 \x03(\v2\x18.blok.runtime.v1.LogLineR\x04logs\x122\n" +
	"\ametrics\x18\a \x01(\v2\x18.blok.runtime.v1.MetricsR\ametrics\"\xae\x02\n" +
	"\fExecuteEvent\x128\n" +
	"\astarted\x18\x01 \x01(\v2\x1c.blok.runtime.v1.NodeStartedH\x00R\astarted\x12,\n" +
	"\x03log\x18\x02 \x01(\v2\x18.blok.runtime.v1.LogLineH\x00R\x03log\x127\n" +
	"\bprogress\x18\x03 \x01(\v2\x19.blok.runtime.v1.ProgressH\x00R\bprogress\x12:\n" +
	"\apartial\x18\x04 \x01(\v2\x1e.blok.runtime.v1.PartialResultH\x00R\apartial\x128\n" +
	"\x05final\x18\x05 \x01(\v2 .blok.runtime.v1.ExecuteResponseH\x00R\x05finalB\a\n" +
	"\x05event\"9\n" +
	"\vNodeStarted\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\":\n" +
	"\bProgress\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x01R\apercent\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\"4\n" +
	"\rPartialResult\x12#\n" +
	"\rsnapshot_json\x18\x01 \x01(\fR\fsnapshotJson\"\xfc\x01\n" +
	"\aLogLine\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12H\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2(.blok.runtime.v1.LogLine.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x05\n" +
	"\tNodeError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12:\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1e.blok.runtime.v1.ErrorCategoryR\bcategory\x12:\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x1e.blok.runtime.v1.ErrorSeverityR\bseverity\x12\x12\n" +
	"\x04node\x18\x04 \x01(\tR\x04node\x12\x10\n" +
	"\x03sdk\x18\x05 \x01(\tR\x03sdk\x12\x1f\n" +
	"\vsdk_version\x18\x06 \x01(\tR\n" +
	"sdkVersion\x12!\n" +
	"\fruntime_kind\x18\a \x01(\tR\vruntimeKind\x12*\n" +
	"\x02at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12 \n" +
	"\vremediation\x18\v \x01(\tR\vremediation\x12\x17\n" +
	"\adoc_url\x18\f \x01(\tR\x06docUrl\x122\n" +
	"\x06causes\x18\r \x03(\v2\x1a.blok.runtime.v1.NodeErrorR\x06causes\x12\x14\n" +
	"\x05stack\x18\x0e \x01(\tR\x05stack\x122\n" +
	"\x15context_snapshot_json\x18\x0f \x01(\fR\x13contextSnapshotJson\x12\x1f\n" +
	"\vhttp_status\x18\x10 \x01(\x05R\n" +
	"httpStatus\x12\x1c\n" +
	"\tretryable\x18\x11 \x01(\bR\tretryable\x12$\n" +
	"\x0eretry_after_ms\x18\x12 \x01(\x03R\fretryAfterMs\x12!\n" +
	"\fdetails_json\x18\x13 \x01(\fR\vdetailsJson\"\x12\n" +
	"\x10ListNodesRequest\"\xab\x01\n" +
	"\x11ListNodesResponse\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.blok.runtime.v1.NodeDescriptorR\x05nodes\x12\x19\n" +
	"\bsdk_name\x18\x02 \x01(\tR\asdkName\x12\x1f\n" +
	"\vsdk_version\x18\x03 \x01(\tR\n" +
	"sdkVersion\x12#\n" +
	"\rproto_version\x18\x04 \x01(\tR\fprotoVersion\"\xb4\x01\n" +
	"\x0eNodeDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\fR\x0finputSchemaJson\x12,\n" +
	"\x12output_schema_json\x18\x04 \x01(\fR\x10outputSchemaJson\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xd1\x01\n" +
	"\x0eHealthResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.blok.runtime.v1.HealthResponse.StatusR\x06status\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12)\n" +
	"\x10registered_nodes\x18\x03 \x03(\tR\x0fregisteredNodes\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"\xb0\x01\n" +
	"\aMetrics\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x01R\n" +
	"durationMs\x12\x15\n" +
	"\x06cpu_ms\x18\x02 \x01(\x01R\x05cpuMs\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x12#\n" +
	"\rrequest_bytes\x18\x04 \x01(\x03R\frequestBytes\x12%\n" +
	"\x0eresponse_bytes\x18\x05 \x01(\x03R\rresponseBytes*\xdb\x01\n" +
	"\rErrorCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"VALIDATION\x10\x01\x12\x11\n" +
	"\rCONFIGURATION\x10\x02\x12\x0e\n" +
	"\n" +
	"DEPENDENCY\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\x0e\n" +
	"\n" +
	"PERMISSION\x10\x05\x12\x0e\n" +
	"\n" +
	"RATE_LIMIT\x10\x06\x12\r\n" +
	"\tNOT_FOUND\x10\a\x12\f\n" +
	"\bCONFLICT\x10\b\x12\r\n" +
	"\tCANCELLED\x10\t\x12\f\n" +
	"\bINTERNAL\x10\n" +
	"\x12\f\n" +
	"\bPROTOCOL\x10\v\x12\b\n" +
	"\x04DATA\x10\f*S\n" +
	"\rErrorSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\t\n" +
	"\x05FATAL\x10\x042\xcd\x02\n" +
	"\vNodeRuntime\x12L\n" +
	"\aExecute\x12\x1f.blok.runtime.v1.ExecuteRequest\x1a .blok.runtime.v1.ExecuteResponse\x12Q\n" +
	"\rExecuteStream\x12\x1f.blok.runtime.v1.ExecuteRequest\x1a\x1d.blok.runtime.v1.ExecuteEvent0\x01\x12I\n" +
	"\x06Health\x12\x1e.blok.runtime.v1.HealthRequest\x1a\x1f.blok.runtime.v1.HealthResponse\x12R\n" +
	"\tListNodes\x12!.blok.runtime.v1.ListNodesRequest\x1a\".blok.runtime.v1.ListNodesResponseB\x8f\x01\n" +
	"\x13com.blok.runtime.v1P\x01Z>github.com/nickincloud/blok-go/genpb/blok/runtime/v1;runtimev1\xaa\x02\x0fBlok.Runtime.V1\xca\x02\x0fBlok\\Runtime\\V1\xea\x02\x11Blok::Runtime::V1b\x06proto3"

var (
	file_blok_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_blok_runtime_v1_runtime_proto_rawDescData []byte
)

func file_blok_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_blok_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_blok_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blok_runtime_v1_runtime_proto_rawDesc), len(file_blok_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_blok_runtime_v1_runtime_proto_rawDescData
}

var file_blok_runtime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_blok_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_blok_runtime_v1_runtime_proto_goTypes = []any{
	(ErrorCategory)(0),            // 0: blok.runtime.v1.ErrorCategory
	(ErrorSeverity)(0),            // 1: blok.runtime.v1.ErrorSeverity
	(HealthResponse_Status)(0),    // 2: blok.runtime.v1.HealthResponse.Status
	(*ExecuteRequest)(nil),        // 3: blok.runtime.v1.ExecuteRequest
	(*NodeRef)(nil),               // 4: blok.runtime.v1.NodeRef
	(*StepInfo)(nil),              // 5: blok.runtime.v1.StepInfo
	(*TriggerInfo)(nil),           // 6: blok.runtime.v1.TriggerInfo
	(*RuntimeState)(nil),          // 7: blok.runtime.v1.RuntimeState
	(*WorkflowInfo)(nil),          // 8: blok.runtime.v1.WorkflowInfo
	(*ExecuteOptions)(nil),        // 9: blok.runtime.v1.ExecuteOptions
	(*ExecuteResponse)(nil),       // 10: blok.runtime.v1.ExecuteResponse
	(*ExecuteEvent)(nil),          // 11: blok.runtime.v1.ExecuteEvent
	(*NodeStarted)(nil),           // 12: blok.runtime.v1.NodeStarted
	(*Progress)(nil),              // 13: blok.runtime.v1.Progress
	(*PartialResult)(nil),         // 14: blok.runtime.v1.PartialResult
	(*LogLine)(nil),               // 15: blok.runtime.v1.LogLine
	(*NodeError)(nil),             // 16: blok.runtime.v1.NodeError
	(*ListNodesRequest)(nil),      // 17: blok.runtime.v1.ListNodesRequest
	(*ListNodesResponse)(nil),     // 18: blok.runtime.v1.ListNodesResponse
	(*NodeDescriptor)(nil),        // 19: blok.runtime.v1.NodeDescriptor
	(*HealthRequest)(nil),         // 20: blok.runtime.v1.HealthRequest
	(*HealthResponse)(nil),        // 21: blok.runtime.v1.HealthResponse
	(*Metrics)(nil),               // 22: blok.runtime.v1.Metrics
	nil,                           // 23: blok.runtime.v1.TriggerInfo.HeadersEntry
	nil,                           // 24: blok.runtime.v1.TriggerInfo.ParamsEntry
	nil,                           // 25: blok.runtime.v1.TriggerInfo.QueryEntry
	nil,                           // 26: blok.runtime.v1.TriggerInfo.CookiesEntry
	nil,                           // 27: blok.runtime.v1.RuntimeState.EnvEntry
	nil,                           // 28: blok.runtime.v1.ExecuteOptions.HintsEntry
	nil,                           // 29: blok.runtime.v1.LogLine.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_blok_runtime_v1_runtime_proto_depIdxs = []int32{
	4,  // 0: blok.runtime.v1.ExecuteRequest.node:type_name -> blok.runtime.v1.NodeRef
	5,  // 1: blok.runtime.v1.ExecuteRequest.step:type_name -> blok.runtime.v1.StepInfo
	6,  // 2: blok.runtime.v1.ExecuteRequest.trigger:type_name -> blok.runtime.v1.TriggerInfo
	7,  // 3: blok.runtime.v1.ExecuteRequest.state:type_name -> blok.runtime.v1.RuntimeState
	8,  // 4: blok.runtime.v1.ExecuteRequest.workflow:type_name -> blok.runtime.v1.WorkflowInfo
	9,  // 5: blok.runtime.v1.ExecuteRequest.options:type_name -> blok.runtime.v1.ExecuteOptions
	23, // 6: blok.runtime.v1.TriggerInfo.headers:type_name -> blok.runtime.v1.TriggerInfo.HeadersEntry
	24, // 7: blok.runtime.v1.TriggerInfo.params:type_name -> blok.runtime.v1.TriggerInfo.ParamsEntry
	25, // 8: blok.runtime.v1.TriggerInfo.query:type_name -> blok.runtime.v1.TriggerInfo.QueryEntry
	26, // 9: blok.runtime.v1.TriggerInfo.cookies:type_name -> blok.runtime.v1.TriggerInfo.CookiesEntry
	27, // 10: blok.runtime.v1.RuntimeState.env:type_name -> blok.runtime.v1.RuntimeState.EnvEntry
	30, // 11: blok.runtime.v1.WorkflowInfo.started_at:type_name -> google.protobuf.Timestamp
	28, // 12: blok.runtime.v1.ExecuteOptions.hints:type_name -> blok.runtime.v1.ExecuteOptions.HintsEntry
	16, // 13: blok.runtime.v1.ExecuteResponse.error:type_name -> blok.runtime.v1.NodeError
	15, // 14: blok.runtime.v1.ExecuteResponse.logs:type_name -> blok.runtime.v1.LogLine
	22, // 15: blok.runtime.v1.ExecuteResponse.metrics:type_name -> blok.runtime.v1.Metrics
	12, // 16: blok.runtime.v1.ExecuteEvent.started:type_name -> blok.runtime.v1.NodeStarted
	15, // 17: blok.runtime.v1.ExecuteEvent.log:type_name -> blok.runtime.v1.LogLine
	13, // 18: blok.runtime.v1.ExecuteEvent.progress:type_name -> blok.runtime.v1.Progress
	14, // 19: blok.runtime.v1.ExecuteEvent.partial:type_name -> blok.runtime.v1.PartialResult
	10, // 20: blok.runtime.v1.ExecuteEvent.final:type_name -> blok.runtime.v1.ExecuteResponse
	30, // 21: blok.runtime.v1.NodeStarted.at:type_name -> google.protobuf.Timestamp
	30, // 22: blok.runtime.v1.LogLine.timestamp:type_name -> google.protobuf.Timestamp
	29, // 23: blok.runtime.v1.LogLine.attributes:type_name -> blok.runtime.v1.LogLine.AttributesEntry
	0,  // 24: blok.runtime.v1.NodeError.category:type_name -> blok.runtime.v1.ErrorCategory
	1,  // 25: blok.runtime.v1.NodeError.severity:type_name -> blok.runtime.v1.ErrorSeverity
	30, // 26: blok.runtime.v1.NodeError.at:type_name -> google.protobuf.Timestamp
	16, // 27: blok.runtime.v1.NodeError.causes:type_name -> blok.runtime.v1.NodeError
	19, // 28: blok.runtime.v1.ListNodesResponse.nodes:type_name -> blok.runtime.v1.NodeDescriptor
	2,  // 29: blok.runtime.v1.HealthResponse.status:type_name -> blok.runtime.v1.HealthResponse.Status
	3,  // 30: blok.runtime.v1.NodeRuntime.Execute:input_type -> blok.runtime.v1.ExecuteRequest
	3,  // 31: blok.runtime.v1.NodeRuntime.ExecuteStream:input_type -> blok.runtime.v1.ExecuteRequest
	20, // 32: blok.runtime.v1.NodeRuntime.Health:input_type -> blok.runtime.v1.HealthRequest
	17, // 33: blok.runtime.v1.NodeRuntime.ListNodes:input_type -> blok.runtime.v1.ListNodesRequest
	10, // 34: blok.runtime.v1.NodeRuntime.Execute:output_type -> blok.runtime.v1.ExecuteResponse
	11, // 35: blok.runtime.v1.NodeRuntime.ExecuteStream:output_type -> blok.runtime.v1.ExecuteEvent
	21, // 36: blok.runtime.v1.NodeRuntime.Health:output_type -> blok.runtime.v1.HealthResponse
	18, // 37: blok.runtime.v1.NodeRuntime.ListNodes:output_type -> blok.runtime.v1.ListNodesResponse
	34, // [34:38] is the sub-list for method output_type
	30, // [30:34] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_blok_runtime_v1_runtime_proto_init() }
func file_blok_runtime_v1_runtime_proto_init() {
	if File_blok_runtime_v1_runtime_proto != nil {
		return
	}
	file_blok_runtime_v1_runtime_proto_msgTypes[8].OneofWrappers = []any{
		(*ExecuteEvent_Started)(nil),
		(*ExecuteEvent_Log)(nil),
		(*ExecuteEvent_Progress)(nil),
		(*ExecuteEvent_Partial)(nil),
		(*ExecuteEvent_Final)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blok_runtime_v1_runtime_proto_rawDesc), len(file_blok_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blok_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_blok_runtime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_blok_runtime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_blok_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_blok_runtime_v1_runtime_proto = out.File
	file_blok_runtime_v1_runtime_proto_goTypes = nil
	file_blok_runtime_v1_runtime_proto_depIdxs = nil
}
