/**
 * Overlay the conformance fixture onto a project `blokctl` just scaffolded.
 *
 * The APP is always generated by the real CLI (`create project` + `add spa`, or
 * `create spa` for the standalone client). This script only adds the surface the
 * 45 scenarios drive: fixture nodes, page workflows, the workflow registry, the
 * Python node, and the client pages. Everything it copies is a real source file
 * under `tests/e2e/inertia/fixture/` — nothing is generated from a string, so
 * the fixture is lintable, type-checkable and reviewable like any other code.
 *
 *   bun tests/e2e/inertia/fixture.ts <projectDir> <framework> [--standalone-client --backend <url>]
 */

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = process.argv[2];
const framework = process.argv[3] ?? "react";
if (!root) throw new Error("fixture root is required");
const clientOnly = process.argv.includes("--standalone-client");
const backendIndex = process.argv.indexOf("--backend");
const backend = backendIndex === -1 ? "" : (process.argv[backendIndex + 1] ?? "");

const here = dirname(fileURLToPath(import.meta.url));
const fixture = join(here, "fixture");
const clientRoot = clientOnly ? root : join(root, "client");

// --- the client half (both modes) -------------------------------------------
const clientSource = join(fixture, "client", framework);
if (!existsSync(clientSource)) throw new Error(`no fixture client for framework "${framework}" at ${clientSource}`);
// The scaffold's own example page is replaced, not merged: `Home` is one of the
// 45 scenarios' pages and two components cannot own one name.
rmSync(join(clientRoot, "src", "pages"), { recursive: true, force: true });
cpSync(clientSource, join(clientRoot, "src"), { recursive: true, force: true });

/**
 * In-project and standalone boot DIFFERENTLY, and both are under test: the
 * scaffold's entry reads the page object out of the shell Blok rendered, while a
 * standalone SPA owns the HTML and has to fetch the first page cross-origin. The
 * fixture ships both and installs the right one.
 */
const standaloneDir = join(clientRoot, "src", "standalone");
if (existsSync(standaloneDir)) {
	if (clientOnly) {
		for (const entry of readdirSync(standaloneDir)) {
			// `vite.config.ts` belongs to the project root; everything else is an
			// entry module and belongs beside the pages it boots.
			const destination = entry === "vite.config.ts" ? join(clientRoot, entry) : join(clientRoot, "src", entry);
			renameSync(join(standaloneDir, entry), destination);
		}
	}
	rmSync(standaloneDir, { recursive: true, force: true });
}

if (clientOnly) {
	// `blokctl create spa --blok-url` wrote the DEV proxy target; a production
	// build needs the absolute backend origin baked into the bundle instead.
	writeFileSync(join(root, ".env.production"), `VITE_BLOK_URL=${backend}\n`);
	// The standalone entry points the protocol at the other origin with the
	// stock Axios adapter (`http.setClient`), which is where `withCredentials`
	// comes from. `axios` is an OPTIONAL peer of `@inertiajs/core`, so both have
	// to be declared for a standalone app that uses it.
	const clientManifest = join(root, "package.json");
	const parsed = JSON.parse(readFileSync(clientManifest, "utf8")) as {
		dependencies?: Record<string, string>;
	};
	parsed.dependencies = {
		...parsed.dependencies,
		"@inertiajs/core": "^3.7.1",
		axios: "^1.19.0",
		"laravel-precognition": "^2.0.0",
	};
	writeFileSync(clientManifest, `${JSON.stringify(parsed, null, "\t")}\n`);
	process.exit(0);
}

// --- the server half (in-project backend) -----------------------------------
const src = join(root, "src");

// One barrel owns every fixture node, so the scaffold's example nodes go: a
// second `current-user` registration is a duplicate node ref and throws at boot.
rmSync(join(src, "nodes", "current-user"), { recursive: true, force: true });
rmSync(join(src, "nodes", "home-greeting"), { recursive: true, force: true });
cpSync(join(fixture, "server", "nodes"), join(src, "nodes"), { recursive: true, force: true });

// `home.ts` is REPLACED (scenario 19 rewrites the fixture's copy of it).
rmSync(join(src, "workflows", "home.ts"), { force: true });
cpSync(join(fixture, "server", "workflows"), join(src, "workflows"), { recursive: true, force: true });
cpSync(join(fixture, "server", "Workflows.ts"), join(src, "Workflows.ts"), { force: true });

// The Python node the Dashboard's deferred `stats` prop resolves through.
mkdirSync(join(root, "runtimes", "python3"), { recursive: true });
cpSync(join(fixture, "server", "python", "nodes"), join(root, "runtimes", "python3", "nodes"), {
	recursive: true,
	force: true,
});

// `@blokjs/helpers` ships `ValidateNode` (the Precognition boundary) and the
// `@blokjs/csrf` node the CSRF middleware runs. `create project` already
// installs it; fail loudly rather than at the first 500 if that ever changes.
const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
	dependencies?: Record<string, string>;
};
if (!manifest.dependencies?.["@blokjs/helpers"]) {
	throw new Error("the scaffolded project has no @blokjs/helpers dependency — the fixture needs ValidateNode");
}

console.log(`[fixture] overlaid the ${framework} conformance fixture on ${resolve(root)}`);
