#!/usr/bin/env bash
#
# #1003 — the real-browser Inertia conformance matrix.
#
# One cell = one DISPOSABLE project, generated by the real CLI, built with the
# real Vite, served by the real HTTP trigger and driven by a real Chromium
# against the stock `@inertiajs/*` client. Nothing here is mocked.
#
#   bun run e2e:inertia -- --framework react --mode in-project --host node
#   bun run e2e:inertia -- --framework vue   --mode standalone
#   bun run e2e:inertia -- --framework react --ssr --repeat 3
#   bun run e2e:inertia -- --self-check
#
# Ports are deliberately NOT the framework defaults: 4321 and 10007 belong to a
# developer's own running example, and a suite that stole them would test it.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
CLI="$ROOT/packages/cli/dist/index.js"
FRAMEWORK="${E2E_FRAMEWORK:-react}"
MODE="${E2E_MODE:-in-project}"
HOST="${E2E_HOST:-node}"
SSR="${E2E_SSR:-0}"
PUBLISHED="${E2E_PUBLISHED_VERSION:-}"
HTTP_PORT="${E2E_HTTP_PORT:-4600}"
PREVIEW_PORT="${E2E_PREVIEW_PORT:-4673}"
PROXY_PORT="${E2E_PROXY_PORT:-4690}"
PY_GRPC_PORT="${E2E_PY_GRPC_PORT:-10307}"
SSR_PORT="${E2E_SSR_PORT:-13814}"
KIT_PORT="${E2E_KIT_PORT:-4601}"
WORKDIR=""
SERVER_PID=""
PREVIEW_PID=""
PROXY_PID=""
PYTHON_PID=""
SSR_PID=""
KIT_PID=""
REPEAT=1
ORIGINAL_ARGS=("$@")

resolve_node() {
	if command -v node >/dev/null 2>&1; then
		local path_node
		path_node="$(command -v node)"
		case "$path_node" in
			*/bun-node-*/node) ;;
			*)
				if "$path_node" --version 2>/dev/null | grep -Eq '^v[0-9]+'; then
					printf '%s\n' "$path_node"
					return
				fi
				;;
		esac
	fi
	local nvm_root="${NVM_DIR:-${HOME:-}/.nvm}"
	local candidate=""
	for candidate in "$nvm_root"/versions/node/*/bin/node; do
		[ -x "$candidate" ] || continue
		NODE_CANDIDATE="$candidate"
	done
	[ -n "${NODE_CANDIDATE:-}" ] && printf '%s\n' "$NODE_CANDIDATE"
}

while [ "$#" -gt 0 ]; do
	case "$1" in
		--framework) FRAMEWORK="$2"; shift 2 ;;
		--mode) MODE="$2"; shift 2 ;;
		--host) HOST="$2"; shift 2 ;;
		--ssr) SSR=1; shift ;;
		--published-version) PUBLISHED="$2"; shift 2 ;;
		--repeat) REPEAT="$2"; shift 2 ;;
		--self-check) exec "$ROOT/tests/e2e/inertia/self-check.sh" ;;
		*) break ;;
	esac
done

if ! [[ "$REPEAT" =~ ^[1-9][0-9]*$ ]]; then
	echo "--repeat must be a positive integer" >&2
	exit 2
fi

NODE_BIN="$(resolve_node)"
if [ -z "$NODE_BIN" ]; then
	echo "Node.js 20+ is required to run Playwright (the selected --host only controls the Blok server)." >&2
	exit 2
fi
NODE_MAJOR="$($NODE_BIN -p 'Number(process.versions.node.split(".")[0])')"
if [ "$NODE_MAJOR" -lt 20 ]; then
	echo "Node.js 20+ is required to run Playwright; found $($NODE_BIN --version)." >&2
	exit 2
fi

if [ "${E2E_USE_PUBLISHED:-0}" = 1 ] && [ -z "$PUBLISHED" ]; then
	echo "E2E_USE_PUBLISHED=1 requires E2E_PUBLISHED_VERSION (@blokjs/inertia and @blokjs/inertia-client are not on npm yet)." >&2
	exit 2
fi

case "$FRAMEWORK" in react|vue|svelte) ;; *) echo "Unsupported --framework: $FRAMEWORK" >&2; exit 2 ;; esac
case "$MODE" in in-project|standalone) ;; *) echo "Unsupported --mode: $MODE" >&2; exit 2 ;; esac
case "$HOST" in node|bun) ;; *) echo "Unsupported --host: $HOST" >&2; exit 2 ;; esac
if [ "$MODE" = standalone ] && [ "$HOST" = bun ]; then
	echo "Bun is an in-project-only conformance host" >&2; exit 2
fi
if [ "$SSR" = 1 ] && { [ "$MODE" = standalone ] || [ "$FRAMEWORK" = svelte ]; }; then
	echo "SSR cells are React/Vue, in-project only" >&2; exit 2
fi

SOURCE=workspace
[ -n "$PUBLISHED" ] && SOURCE=published
CELL_ID="${FRAMEWORK}-${MODE}-${HOST}-ssr${SSR}-${SOURCE}"
if [ "${E2E_BREAK_VARY:-}" = 1 ]; then CELL_ID="$CELL_ID-break-vary"; fi
if [ "${E2E_BREAK_303:-}" = 1 ]; then CELL_ID="$CELL_ID-break-303"; fi
if [ "${E2E_BREAK_ESCAPE:-}" = 1 ]; then CELL_ID="$CELL_ID-break-escape"; fi
export E2E_CELL_ID="$CELL_ID"

cleanup() {
	for pid in "$PROXY_PID" "$SSR_PID" "$PREVIEW_PID" "$SERVER_PID" "$KIT_PID" "$PYTHON_PID"; do
		[ -n "$pid" ] || continue
		pkill -P "$pid" 2>/dev/null || true
		kill "$pid" 2>/dev/null || true
	done
	for pid in "$PROXY_PID" "$SSR_PID" "$PREVIEW_PID" "$SERVER_PID" "$KIT_PID" "$PYTHON_PID"; do
		[ -n "$pid" ] && wait "$pid" 2>/dev/null || true
	done
	# Logs BEFORE the workdir goes: a failed cell is only debuggable from these.
	if [ -n "$WORKDIR" ]; then
		local log_dir="$ROOT/test-results/inertia-logs/$CELL_ID/run-${E2E_RUN_NUMBER:-1}"
		mkdir -p "$log_dir"
		find "$WORKDIR" -maxdepth 1 -name '*.log' -exec cp {} "$log_dir/" \; 2>/dev/null || true
		[ -n "${E2E_KEEP:-}" ] || rm -rf "$WORKDIR"
	fi
}

# A repeat is N INDEPENDENT scaffolds, builds, servers and browser sessions.
# Reusing one fixture would hide state that leaks between runs.
if [ "$REPEAT" -gt 1 ] && [ "${E2E_REPEAT_CHILD:-0}" != 1 ]; then
	for run in $(seq 1 "$REPEAT"); do
		echo "── run $run/$REPEAT ──────────────────────────────────────────────"
		E2E_REPEAT_CHILD=1 E2E_RUN_NUMBER="$run" "$0" "${ORIGINAL_ARGS[@]}"
	done
	exit 0
fi

trap cleanup EXIT

wait_for() { # url, seconds, pid, logfile
	for _ in $(seq 1 "$2"); do
		[ -z "$3" ] || kill -0 "$3" 2>/dev/null || { tail -60 "$4" >&2; return 1; }
		curl -fsS -o /dev/null "$1" 2>/dev/null && return 0
		sleep 1
	done
	[ -z "$4" ] || tail -60 "$4" >&2
	return 1
}

if [ -z "${E2E_BASE_URL:-}" ]; then
	bind_ports=("$HTTP_PORT" "$PREVIEW_PORT" "$PROXY_PORT" "$PY_GRPC_PORT" "$SSR_PORT" "$KIT_PORT")
	for port in "${bind_ports[@]}"; do
		case "$port" in 4321|10007)
			echo "Refusing to bind protected demo port $port." >&2
			exit 2
			;;
		esac
		if ! [[ "$port" =~ ^[0-9]+$ ]] || [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
			echo "Invalid E2E port: $port" >&2
			exit 2
		fi
	done
	if [ "$(printf '%s\n' "${bind_ports[@]}" | sort -u | wc -l | tr -d ' ')" -ne "${#bind_ports[@]}" ]; then
		echo "Every E2E service must use a distinct port." >&2
		exit 2
	fi
	if command -v lsof >/dev/null 2>&1; then
		for port in "${bind_ports[@]}"; do
			if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
				echo "E2E port $port is already in use; refusing to attach to another process." >&2
				exit 2
			fi
		done
	fi

	WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/blok-inertia-e2e.XXXXXX")"

	if [ -n "$PUBLISHED" ]; then
		CLI_CMD=(bunx --yes "blokctl@$PUBLISHED")
		LOCAL_ARGS=()
	else
		[ -f "$CLI" ] || { echo "Missing $CLI; run bun run build first" >&2; exit 1; }
		CLI_CMD=(bun "$CLI")
		LOCAL_ARGS=(--local "$ROOT")
	fi

	# `blokctl runtime add python3` builds its venv with whatever `python3` is on
	# PATH, and the SDK's typed nodes need 3.11+. BLOK_PYTHON names a newer one;
	# a shim directory in front of PATH is how it reaches the CLI unchanged.
	if [ -n "${BLOK_PYTHON:-}" ]; then
		mkdir -p "$WORKDIR/pybin"
		ln -sf "$BLOK_PYTHON" "$WORKDIR/pybin/python3"
		PATH="$WORKDIR/pybin:$PATH"
		export PATH
	fi

	(cd "$WORKDIR" && "${CLI_CMD[@]}" create project --name app "${LOCAL_ARGS[@]}" \
		--triggers http,mcp --runtimes python3 --package-manager bun --runtime "$HOST" --non-interactive </dev/null)
	PROJECT="$WORKDIR/app"
	SPA_ARGS=(--framework "$FRAMEWORK" --pm bun)
	[ "$SSR" = 1 ] && SPA_ARGS+=(--ssr)
	(cd "$PROJECT" && "${CLI_CMD[@]}" add spa "${SPA_ARGS[@]}" "${LOCAL_ARGS[@]}" --non-interactive </dev/null)

	bun "$ROOT/tests/e2e/inertia/fixture.ts" "$PROJECT" "$FRAMEWORK"
	(cd "$PROJECT" && bun install)
	# Typed pages/routes for the client BEFORE it is built: `Home.tsx` reads its
	# props through the generated `PageProps<"Home">` (the scenario-19 gate).
	(cd "$PROJECT" && bun run gen:types)
	(cd "$PROJECT" && bun run build)
	[ "$SSR" = 1 ] && (cd "$PROJECT/client" && bun run build:ssr)

	PY_COUNTER="$WORKDIR/python-calls"
	echo 0 >"$PY_COUNTER"

	# The `runtime.python3` sidecar — what `blokctl dev` spawns from
	# `.blok/config.json`. `bun run start` does not, so the suite does it here.
	PY_CWD="$PROJECT/.blok/runtimes/python3"
	if [ -x "$PY_CWD/python3_runtime/bin/python3" ]; then
		(cd "$PY_CWD" && exec env GRPC_PORT="$PY_GRPC_PORT" PORT=9107 HOST=127.0.0.1 BLOK_TRANSPORT=grpc \
			BLOK_NODES_DIR="$PROJECT/runtimes/python3/nodes" BLOK_E2E_PY_COUNTER="$PY_COUNTER" PYTHONUNBUFFERED=1 \
			./python3_runtime/bin/python3 bin/serve.py) >"$WORKDIR/python.log" 2>&1 &
		PYTHON_PID=$!
	fi
	for _ in $(seq 1 30); do
		kill -0 "$PYTHON_PID" 2>/dev/null || break
		(exec 3<>"/dev/tcp/127.0.0.1/$PY_GRPC_PORT") 2>/dev/null && break
		sleep 1
	done
	if ! (exec 3<>"/dev/tcp/127.0.0.1/$PY_GRPC_PORT") 2>/dev/null; then
		echo "the runtime.python3 sidecar never listened on $PY_GRPC_PORT — scenario 8 needs it." >&2
		echo "Set BLOK_PYTHON to a python3 >= 3.11 with grpcio + pydantic (CI: actions/setup-python)." >&2
		[ -f "$WORKDIR/python.log" ] && tail -40 "$WORKDIR/python.log" >&2
		exit 1
	fi

	if [ "$SSR" = 1 ]; then
		(cd "$PROJECT" && exec "${CLI_CMD[@]}" inertia start-ssr --port "$SSR_PORT") >"$WORKDIR/ssr.log" 2>&1 &
		SSR_PID=$!
		wait_for "http://127.0.0.1:$SSR_PORT/health" 60 "$SSR_PID" "$WORKDIR/ssr.log" \
			|| { echo "the Inertia SSR server never became ready" >&2; exit 1; }
	fi

	START_SCRIPT=start
	[ "$HOST" = bun ] && START_SCRIPT=start:http
	server_env=(
		PORT="$HTTP_PORT"
		TRIGGER_HTTP_PORT="$HTTP_PORT"
		TRIGGER_MCP_PORT="$HTTP_PORT"
		BLOK_STATIC_DIR=client/dist
		BLOK_CORS_ORIGIN="http://127.0.0.1:$PREVIEW_PORT"
		RUNTIME_PYTHON3_GRPC_PORT="$PY_GRPC_PORT"
		BLOK_E2E_PY_COUNTER="$PY_COUNTER"
		BLOK_INERTIA_ERROR_PAGES=1
		BLOK_INERTIA_DEVTOOLS_ENABLED=1
		BLOK_INERTIA_DEVTOOLS_PATH="$WORKDIR/devtools"
		BLOK_TRACING_DISABLED=1
	)
	[ "$SSR" = 1 ] && server_env+=(BLOK_SSR_URL="http://127.0.0.1:$SSR_PORT")
	(cd "$PROJECT" && exec env "${server_env[@]}" bun run "$START_SCRIPT") >"$WORKDIR/blok.log" 2>&1 &
	SERVER_PID=$!
	wait_for "http://127.0.0.1:$HTTP_PORT/health-check" 90 "$SERVER_PID" "$WORKDIR/blok.log" \
		|| { echo "the Blok server never became ready" >&2; exit 1; }

	E2E_BASE_URL="http://127.0.0.1:$HTTP_PORT"
	export E2E_PROJECT_DIR="$PROJECT" E2E_SERVER_URL="http://127.0.0.1:$HTTP_PORT"

	if [ "${E2E_BREAK_VARY:-}" = 1 ] || [ "${E2E_BREAK_303:-}" = 1 ] || [ "${E2E_BREAK_ESCAPE:-}" = 1 ]; then
		(exec env E2E_TARGET_URL="$E2E_BASE_URL" E2E_PROXY_PORT="$PROXY_PORT" \
			bun "$ROOT/tests/e2e/inertia/break-proxy.ts") >"$WORKDIR/proxy.log" 2>&1 &
		PROXY_PID=$!
		wait_for "http://127.0.0.1:$PROXY_PORT/health-check" 30 "$PROXY_PID" "$WORKDIR/proxy.log" \
			|| { echo "the E2E break proxy never became ready" >&2; exit 1; }
		E2E_BASE_URL="http://127.0.0.1:$PROXY_PORT"
	fi

	# ── the auth starter kit (#1018), scenario 44 ────────────────────────────
	# Its pages and routes ARE the product under test, so it gets its own
	# scaffold rather than being merged into the conformance fixture (two
	# `/login` workflows and two `Dashboard` components cannot coexist). One
	# representative cell per framework builds it; the other cells of the same
	# framework would only re-prove the same scaffold.
	if [ "$MODE" = in-project ] && [ "$HOST" = node ] && [ "$SSR" = 0 ]; then
		(cd "$WORKDIR" && "${CLI_CMD[@]}" create project --name kit "${LOCAL_ARGS[@]}" \
			--triggers http --package-manager bun --runtime node --non-interactive </dev/null)
		(cd "$WORKDIR/kit" && "${CLI_CMD[@]}" add spa --framework "$FRAMEWORK" --pm bun --kit auth \
			"${LOCAL_ARGS[@]}" --non-interactive </dev/null)
		(cd "$WORKDIR/kit" && bun install && bun run build)
		(cd "$WORKDIR/kit" && exec env PORT="$KIT_PORT" TRIGGER_HTTP_PORT="$KIT_PORT" BLOK_STATIC_DIR=client/dist \
			BLOK_TRACING_DISABLED=1 bun run start) >"$WORKDIR/kit.log" 2>&1 &
		KIT_PID=$!
		wait_for "http://127.0.0.1:$KIT_PORT/health-check" 90 "$KIT_PID" "$WORKDIR/kit.log" \
			|| { echo "the auth-kit server never became ready" >&2; exit 1; }
		export E2E_KIT_URL="http://127.0.0.1:$KIT_PORT"
	fi

	if [ "$MODE" = standalone ]; then
		(cd "$WORKDIR" && "${CLI_CMD[@]}" create spa client --framework "$FRAMEWORK" --pm bun \
			--blok-url "$E2E_BASE_URL" "${LOCAL_ARGS[@]}" --non-interactive </dev/null)
		bun "$ROOT/tests/e2e/inertia/fixture.ts" "$WORKDIR/client" "$FRAMEWORK" --standalone-client --backend "$E2E_BASE_URL"
		(cd "$WORKDIR/client" && bun install && bun run build)
		(cd "$WORKDIR/client" && exec bunx vite preview --host 127.0.0.1 --port "$PREVIEW_PORT" --strictPort) \
			>"$WORKDIR/vite.log" 2>&1 &
		PREVIEW_PID=$!
		wait_for "http://127.0.0.1:$PREVIEW_PORT/" 60 "$PREVIEW_PID" "$WORKDIR/vite.log" \
			|| { echo "the Vite preview never became ready" >&2; exit 1; }
		export E2E_CLIENT_URL="http://127.0.0.1:$PREVIEW_PORT"
		E2E_BASE_URL="http://127.0.0.1:$PREVIEW_PORT"
	fi
fi

export E2E_FRAMEWORK="$FRAMEWORK" E2E_MODE="$MODE" E2E_HOST="$HOST" E2E_SSR="$SSR" E2E_BASE_URL
export E2E_SERVER_URL="${E2E_SERVER_URL:-$E2E_BASE_URL}"
export E2E_USE_PUBLISHED="$([ -n "$PUBLISHED" ] && echo 1 || echo 0)"
"$NODE_BIN" "$ROOT/node_modules/playwright/cli.js" test --config "$ROOT/tests/e2e/inertia/playwright.config.ts" "$@"
