/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CatalogRouteRouteImport } from "./routes/catalog/route"
import { Route as DashboardsRouteImport } from "./routes/dashboards"
import { Route as DeploymentsRouteImport } from "./routes/deployments"
import { Route as LogsRouteImport } from "./routes/logs"
import { Route as MetricsRouteImport } from "./routes/metrics"
import { Route as QueuesRouteImport } from "./routes/queues"
import { Route as ScheduledRouteImport } from "./routes/scheduled"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as StorybookRouteImport } from "./routes/storybook"
import { Route as WebhooksRouteImport } from "./routes/webhooks"
import { Route as CatalogIndexRouteImport } from "./routes/catalog/index"
import { Route as CatalogPageRouteImport } from "./routes/catalog/$page"
import { Route as RunsIndexRouteImport } from "./routes/runs/index"
import { Route as RunsRunIdRouteImport } from "./routes/runs/$runId"
import { Route as RunsDiffRouteImport } from "./routes/runs/diff"
import { Route as WorkflowsNameRouteImport } from "./routes/workflows/$name"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRouteRoute = CatalogRouteRouteImport.update({
  id: "/catalog",
  path: "/catalog",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: "/dashboards",
  path: "/dashboards",
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: "/deployments",
  path: "/deployments",
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: "/logs",
  path: "/logs",
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: "/metrics",
  path: "/metrics",
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: "/queues",
  path: "/queues",
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: "/scheduled",
  path: "/scheduled",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookRoute = StorybookRouteImport.update({
  id: "/storybook",
  path: "/storybook",
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: "/webhooks",
  path: "/webhooks",
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CatalogRouteRoute,
} as any)
const CatalogPageRoute = CatalogPageRouteImport.update({
  id: "/$page",
  path: "/$page",
  getParentRoute: () => CatalogRouteRoute,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: "/runs/",
  path: "/runs/",
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: "/runs/$runId",
  path: "/runs/$runId",
  getParentRoute: () => rootRouteImport,
} as any)
const RunsDiffRoute = RunsDiffRouteImport.update({
  id: "/runs/diff",
  path: "/runs/diff",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNameRoute = WorkflowsNameRouteImport.update({
  id: "/workflows/$name",
  path: "/workflows/$name",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/catalog": typeof CatalogRouteRouteWithChildren
  "/dashboards": typeof DashboardsRoute
  "/deployments": typeof DeploymentsRoute
  "/logs": typeof LogsRoute
  "/metrics": typeof MetricsRoute
  "/queues": typeof QueuesRoute
  "/scheduled": typeof ScheduledRoute
  "/settings": typeof SettingsRoute
  "/storybook": typeof StorybookRoute
  "/webhooks": typeof WebhooksRoute
  "/catalog/$page": typeof CatalogPageRoute
  "/runs/$runId": typeof RunsRunIdRoute
  "/runs/diff": typeof RunsDiffRoute
  "/workflows/$name": typeof WorkflowsNameRoute
  "/catalog/": typeof CatalogIndexRoute
  "/runs/": typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/dashboards": typeof DashboardsRoute
  "/deployments": typeof DeploymentsRoute
  "/logs": typeof LogsRoute
  "/metrics": typeof MetricsRoute
  "/queues": typeof QueuesRoute
  "/scheduled": typeof ScheduledRoute
  "/settings": typeof SettingsRoute
  "/storybook": typeof StorybookRoute
  "/webhooks": typeof WebhooksRoute
  "/catalog/$page": typeof CatalogPageRoute
  "/runs/$runId": typeof RunsRunIdRoute
  "/runs/diff": typeof RunsDiffRoute
  "/workflows/$name": typeof WorkflowsNameRoute
  "/catalog": typeof CatalogIndexRoute
  "/runs": typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/catalog": typeof CatalogRouteRouteWithChildren
  "/dashboards": typeof DashboardsRoute
  "/deployments": typeof DeploymentsRoute
  "/logs": typeof LogsRoute
  "/metrics": typeof MetricsRoute
  "/queues": typeof QueuesRoute
  "/scheduled": typeof ScheduledRoute
  "/settings": typeof SettingsRoute
  "/storybook": typeof StorybookRoute
  "/webhooks": typeof WebhooksRoute
  "/catalog/$page": typeof CatalogPageRoute
  "/runs/$runId": typeof RunsRunIdRoute
  "/runs/diff": typeof RunsDiffRoute
  "/workflows/$name": typeof WorkflowsNameRoute
  "/catalog/": typeof CatalogIndexRoute
  "/runs/": typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/catalog"
    | "/dashboards"
    | "/deployments"
    | "/logs"
    | "/metrics"
    | "/queues"
    | "/scheduled"
    | "/settings"
    | "/storybook"
    | "/webhooks"
    | "/catalog/$page"
    | "/runs/$runId"
    | "/runs/diff"
    | "/workflows/$name"
    | "/catalog/"
    | "/runs/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dashboards"
    | "/deployments"
    | "/logs"
    | "/metrics"
    | "/queues"
    | "/scheduled"
    | "/settings"
    | "/storybook"
    | "/webhooks"
    | "/catalog/$page"
    | "/runs/$runId"
    | "/runs/diff"
    | "/workflows/$name"
    | "/catalog"
    | "/runs"
  id:
    | "__root__"
    | "/"
    | "/catalog"
    | "/dashboards"
    | "/deployments"
    | "/logs"
    | "/metrics"
    | "/queues"
    | "/scheduled"
    | "/settings"
    | "/storybook"
    | "/webhooks"
    | "/catalog/$page"
    | "/runs/$runId"
    | "/runs/diff"
    | "/workflows/$name"
    | "/catalog/"
    | "/runs/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRouteRoute: typeof CatalogRouteRouteWithChildren
  DashboardsRoute: typeof DashboardsRoute
  DeploymentsRoute: typeof DeploymentsRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  QueuesRoute: typeof QueuesRoute
  ScheduledRoute: typeof ScheduledRoute
  SettingsRoute: typeof SettingsRoute
  StorybookRoute: typeof StorybookRoute
  WebhooksRoute: typeof WebhooksRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsDiffRoute: typeof RunsDiffRoute
  WorkflowsNameRoute: typeof WorkflowsNameRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/catalog": {
      id: "/catalog"
      path: "/catalog"
      fullPath: "/catalog"
      preLoaderRoute: typeof CatalogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboards": {
      id: "/dashboards"
      path: "/dashboards"
      fullPath: "/dashboards"
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deployments": {
      id: "/deployments"
      path: "/deployments"
      fullPath: "/deployments"
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/logs": {
      id: "/logs"
      path: "/logs"
      fullPath: "/logs"
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/metrics": {
      id: "/metrics"
      path: "/metrics"
      fullPath: "/metrics"
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/queues": {
      id: "/queues"
      path: "/queues"
      fullPath: "/queues"
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/scheduled": {
      id: "/scheduled"
      path: "/scheduled"
      fullPath: "/scheduled"
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/storybook": {
      id: "/storybook"
      path: "/storybook"
      fullPath: "/storybook"
      preLoaderRoute: typeof StorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/webhooks": {
      id: "/webhooks"
      path: "/webhooks"
      fullPath: "/webhooks"
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/catalog/": {
      id: "/catalog/"
      path: "/"
      fullPath: "/catalog/"
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    "/catalog/$page": {
      id: "/catalog/$page"
      path: "/$page"
      fullPath: "/catalog/$page"
      preLoaderRoute: typeof CatalogPageRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    "/runs/": {
      id: "/runs/"
      path: "/runs"
      fullPath: "/runs/"
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/runs/$runId": {
      id: "/runs/$runId"
      path: "/runs/$runId"
      fullPath: "/runs/$runId"
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/runs/diff": {
      id: "/runs/diff"
      path: "/runs/diff"
      fullPath: "/runs/diff"
      preLoaderRoute: typeof RunsDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workflows/$name": {
      id: "/workflows/$name"
      path: "/workflows/$name"
      fullPath: "/workflows/$name"
      preLoaderRoute: typeof WorkflowsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CatalogRouteRouteChildren {
  CatalogPageRoute: typeof CatalogPageRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteRouteChildren: CatalogRouteRouteChildren = {
  CatalogPageRoute: CatalogPageRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteRouteWithChildren = CatalogRouteRoute._addFileChildren(
  CatalogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRouteRoute: CatalogRouteRouteWithChildren,
  DashboardsRoute: DashboardsRoute,
  DeploymentsRoute: DeploymentsRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  QueuesRoute: QueuesRoute,
  ScheduledRoute: ScheduledRoute,
  SettingsRoute: SettingsRoute,
  StorybookRoute: StorybookRoute,
  WebhooksRoute: WebhooksRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  RunsDiffRoute: RunsDiffRoute,
  WorkflowsNameRoute: WorkflowsNameRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
