/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as RunsIndexRouteImport } from "./routes/runs/index"
import { Route as WorkflowsNameRouteImport } from "./routes/workflows/$name"
import { Route as RunsRunIdRouteImport } from "./routes/runs/$runId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: "/runs/",
  path: "/runs/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNameRoute = WorkflowsNameRouteImport.update({
  id: "/workflows/$name",
  path: "/workflows/$name",
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: "/runs/$runId",
  path: "/runs/$runId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/runs/$runId": typeof RunsRunIdRoute
  "/workflows/$name": typeof WorkflowsNameRoute
  "/runs/": typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/runs/$runId": typeof RunsRunIdRoute
  "/workflows/$name": typeof WorkflowsNameRoute
  "/runs": typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/runs/$runId": typeof RunsRunIdRoute
  "/workflows/$name": typeof WorkflowsNameRoute
  "/runs/": typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/runs/$runId" | "/workflows/$name" | "/runs/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/runs/$runId" | "/workflows/$name" | "/runs"
  id: "__root__" | "/" | "/runs/$runId" | "/workflows/$name" | "/runs/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  WorkflowsNameRoute: typeof WorkflowsNameRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/runs/": {
      id: "/runs/"
      path: "/runs"
      fullPath: "/runs/"
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workflows/$name": {
      id: "/workflows/$name"
      path: "/workflows/$name"
      fullPath: "/workflows/$name"
      preLoaderRoute: typeof WorkflowsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/runs/$runId": {
      id: "/runs/$runId"
      path: "/runs/$runId"
      fullPath: "/runs/$runId"
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  WorkflowsNameRoute: WorkflowsNameRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
