import { promises as fsp } from "node:fs";
import path from "node:path";
import type { OptionValues } from "commander";
import color from "picocolors";
import { nameToIdentifier } from "../gen/appTypes.js";
import { type NodeEntry, fetchCatalog } from "./listNodes.js";

/**
 * `blokctl nodes sync` (#358) — generate the cross-runtime `runtimeNode` stubs
 * the typed-handle DSL imports, straight from a running server's node catalog
 * (`GET /__blok/nodes`). One stub file per runtime kind (e.g.
 * `nodes-gen/runtime.python3.ts`), each exporting named
 * `runtimeNode<In, Out>(name, ref)` factories keyed by the catalog's `ref`.
 *
 * Degrade gracefully — the common case: a node whose manifest carries a JSON
 * Schema gets a typed factory; a null-schema node falls back to
 * `runtimeNode<unknown, unknown>(...)` (never a failure). Module nodes are
 * skipped — they are imported directly from their package, not stubbed.
 */

const BANNER = "// AUTO-GENERATED by `blokctl nodes sync` — do not edit by hand.";

/**
 * Render a parsed JSON Schema as a TypeScript type literal. Covers the shapes a
 * node manifest realistically carries (object/array/string/number/boolean/enum)
 * and degrades ANY unrecognized construct to `unknown` — never throws, never
 * emits invalid TS. `null`/empty schema → `unknown` so the factory stays usable.
 */
export function jsonSchemaToTs(schema: unknown): string {
	if (!schema || typeof schema !== "object") return "unknown";
	const s = schema as Record<string, unknown>;

	if (Array.isArray(s.enum)) {
		return s.enum.map((v) => JSON.stringify(v)).join(" | ") || "unknown";
	}

	switch (s.type) {
		case "string":
			return "string";
		case "number":
		case "integer":
			return "number";
		case "boolean":
			return "boolean";
		case "null":
			return "null";
		case "array":
			return `Array<${jsonSchemaToTs(s.items)}>`;
		case "object":
		case undefined: {
			const props = s.properties;
			if (!props || typeof props !== "object") return "Record<string, unknown>";
			const required = new Set(Array.isArray(s.required) ? (s.required as string[]) : []);
			const fields = Object.entries(props as Record<string, unknown>).map(([key, value]) => {
				const k = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
				const opt = required.has(key) ? "" : "?";
				return `${k}${opt}: ${jsonSchemaToTs(value)}`;
			});
			return fields.length === 0 ? "Record<string, unknown>" : `{ ${fields.join("; ")} }`;
		}
		default:
			return "unknown";
	}
}

/**
 * Build one stub-file source per runtime kind from the catalog. Pure (no IO) so
 * it's unit-testable. Returns a map keyed by filename (e.g.
 * `runtime.python3.ts`). Module nodes are excluded — they aren't stubbed.
 */
export function generateRuntimeStubs(nodes: readonly NodeEntry[]): Map<string, string> {
	const byRuntime = new Map<string, NodeEntry[]>();
	for (const n of nodes) {
		if (n.runtime === "module") continue; // module nodes are imported, not stubbed
		const list = byRuntime.get(n.runtime) ?? [];
		list.push(n);
		byRuntime.set(n.runtime, list);
	}

	const files = new Map<string, string>();
	for (const [runtime, entries] of [...byRuntime].sort(([a], [b]) => a.localeCompare(b))) {
		entries.sort((a, b) => a.name.localeCompare(b.name));
		const used = new Map<string, string>(); // ident -> name (disambiguate collisions)
		const lines: string[] = [BANNER, `// Runtime: ${runtime}.`, "", 'import { runtimeNode } from "@blokjs/core";', ""];
		for (const n of entries) {
			let ident = nameToIdentifier(n.name);
			if (used.has(ident) && used.get(ident) !== n.name) {
				let i = 2;
				while (used.has(`${ident}${i}`)) i++;
				ident = `${ident}${i}`;
			}
			used.set(ident, n.name);
			const inT = jsonSchemaToTs(n.inputSchema);
			const outT = jsonSchemaToTs(n.outputSchema);
			const ref = n.ref ?? `${runtime}:${n.name}`; // catalog always carries ref; derive as a fallback
			lines.push(
				`export const ${ident} = runtimeNode<${inT}, ${outT}>(${JSON.stringify(n.name)}, ${JSON.stringify(ref)});`,
			);
		}
		files.set(`${runtime}.ts`, `${lines.join("\n")}\n`);
	}
	return files;
}

/**
 * Fetch the catalog and write the runtime stubs to `outDir`. Shared by the
 * `nodes sync` CLI and `blokctl dev`'s post-SERVING regen hook. Returns the
 * number of stub files written (0 when the catalog has no runtime nodes).
 *
 * Throws on an unreachable / erroring server (`fetchCatalog` returns null) so
 * callers choose their own failure policy — `dev` warns and keeps running, the
 * CLI exits non-zero.
 */
export async function regenRuntimeStubs(baseUrl: string | undefined, outDir: string): Promise<number> {
	const nodes = await fetchCatalog(baseUrl);
	if (nodes === null) throw new Error("catalog fetch failed");

	const files = generateRuntimeStubs(nodes);
	if (files.size === 0) return 0;

	await fsp.mkdir(outDir, { recursive: true });
	for (const [filename, source] of files) {
		await fsp.writeFile(path.join(outDir, filename), source, "utf8");
	}
	return files.size;
}

/** CLI entrypoint for `blokctl nodes sync`. */
export async function syncNodes(opts: OptionValues): Promise<void> {
	const cwd = process.cwd();
	const outDir = path.isAbsolute(opts.out ?? "")
		? (opts.out as string)
		: path.join(cwd, (opts.out as string | undefined) ?? "nodes-gen");

	const nodes = await fetchCatalog(opts.url as string | undefined);
	if (nodes === null) {
		process.exit(1);
		return;
	}

	const files = generateRuntimeStubs(nodes);
	if (files.size === 0) {
		console.log(color.yellow("No runtime nodes found — nothing to generate (module nodes are imported directly)."));
		return;
	}

	await fsp.mkdir(outDir, { recursive: true });
	for (const [filename, source] of files) {
		await fsp.writeFile(path.join(outDir, filename), source, "utf8");
		console.log(color.green(`✅ ${color.cyan(path.join(path.relative(cwd, outDir), filename))}`));
	}
	console.log(color.dim(`\nGenerated ${files.size} stub file(s). Import the named factories into your workflows.\n`));
}
