import { describe, expect, it } from "vitest";
import type { NodeEntry } from "./listNodes.js";
import { generateRuntimeStubs, jsonSchemaToTs } from "./syncNodes.js";

describe("jsonSchemaToTs", () => {
	it("degrades null / empty / unknown schema to unknown", () => {
		expect(jsonSchemaToTs(null)).toBe("unknown");
		expect(jsonSchemaToTs(undefined)).toBe("unknown");
		expect(jsonSchemaToTs({ type: "weird-future-type" })).toBe("unknown");
	});

	it("renders an object schema with required/optional fields", () => {
		const schema = {
			type: "object",
			properties: { prompt: { type: "string" }, count: { type: "integer" } },
			required: ["prompt"],
		};
		expect(jsonSchemaToTs(schema)).toBe("{ prompt: string; count?: number }");
	});

	it("renders arrays and enums", () => {
		expect(jsonSchemaToTs({ type: "array", items: { type: "string" } })).toBe("Array<string>");
		expect(jsonSchemaToTs({ enum: ["a", "b"] })).toBe('"a" | "b"');
	});
});

describe("generateRuntimeStubs", () => {
	const fixture: NodeEntry[] = [
		// typed node
		{
			name: "ask",
			ref: "runtime.python3:ask",
			runtime: "runtime.python3",
			inputSchema: { type: "object", properties: { prompt: { type: "string" } }, required: ["prompt"] },
			outputSchema: { type: "object", properties: { answer: { type: "string" } }, required: ["answer"] },
		},
		// null-schema node → must degrade to unknown, NOT fail
		{ name: "embed", ref: "runtime.python3:embed", runtime: "runtime.python3", inputSchema: null, outputSchema: null },
		// a module node → must be excluded from stubs
		{ name: "@blokjs/respond", ref: "@blokjs/respond", runtime: "module", inputSchema: {}, outputSchema: null },
		// a second runtime → separate file
		{ name: "fast", ref: "runtime.rust:fast", runtime: "runtime.rust", inputSchema: null, outputSchema: null },
	];

	it("emits one file per runtime kind, skipping module nodes", () => {
		const files = generateRuntimeStubs(fixture);
		expect([...files.keys()].sort()).toEqual(["runtime.python3.ts", "runtime.rust.ts"]);
	});

	it("emits the banner, the import, a typed factory, and an unknown fallback factory", () => {
		const py = generateRuntimeStubs(fixture).get("runtime.python3.ts");
		if (!py) throw new Error("expected runtime.python3.ts");

		expect(py).toContain("// AUTO-GENERATED by `blokctl nodes sync` — do not edit by hand.");
		expect(py).toContain('import { runtimeNode } from "@blokjs/core";');
		// typed factory: schema → TS types + the catalog ref
		expect(py).toContain(
			'export const ask = runtimeNode<{ prompt: string }, { answer: string }>("ask", "runtime.python3:ask");',
		);
		// null-schema degrades to unknown — present, not skipped
		expect(py).toContain('export const embed = runtimeNode<unknown, unknown>("embed", "runtime.python3:embed");');
	});

	it("disambiguates identical identifiers across nodes", () => {
		const files = generateRuntimeStubs([
			{ name: "do-thing", ref: "runtime.go:do-thing", runtime: "runtime.go", inputSchema: null, outputSchema: null },
			{ name: "do.thing", ref: "runtime.go:do.thing", runtime: "runtime.go", inputSchema: null, outputSchema: null },
		]);
		const go = files.get("runtime.go.ts") ?? "";
		expect(go).toContain('runtimeNode<unknown, unknown>("do-thing", "runtime.go:do-thing")');
		// second node camelCases to the same `doThing` → suffixed
		expect(go).toMatch(/export const doThing2 = runtimeNode<unknown, unknown>\("do\.thing"/);
	});
});
