[supervisord]
nodaemon=true

[program:worker_trigger]
command=bun run src/triggers/worker/index.ts
directory=/app
environment=PORT="4008",HOST="0.0.0.0"
autostart=true
autorestart=true
stderr_logfile=/var/log/worker_trigger.err.log
stdout_logfile=/var/log/worker_trigger.out.log
