// AUTO-GENERATED by `blokctl gen app-types` — do not edit by hand.
import { registerRoutes } from "@blokjs/inertia-client";

registerRoutes({
	"orders.export": { url: "/orders/export", method: "get" },
	"orders.index": { url: "/orders", method: "get", component: "Orders/Index" },
	"orders.line-edit": { url: "/orders/:id/lines/:lineId", method: "post", component: "Orders/LineEdit" },
	"orders.show": { url: "/orders/:id", method: "get", component: "Orders/Show" },
});
