// AUTO-GENERATED by `blokctl gen app-types` — do not edit by hand.
import "@blokjs/inertia-client";
import "@inertiajs/core";

declare module "@blokjs/inertia-client" {
	interface Pages {
		"Orders/Index": {
			auth: {
				id: string;
				email: string;
			};
			orders: {
				items: Array<{
					id: string;
					total: number;
					tags: Array<string>;
				}>;
				cursor: string | null;
			};
			status: {
				status: "open" | "closed" | number;
				source: "web" | "api";
				note?: string;
			};
			filters?: {
				open: boolean;
			};
			stats?: {
				revenue: number;
			};
			legacy: unknown;
		};
		"Orders/LineEdit": {
			order: {
				id: string;
				lines: Array<{
					sku: string;
					qty: number;
				}>;
			};
			events: {
				data: Array<string>;
				page: number;
			};
		};
		"Orders/Show": {
			order: {
				id: string;
				lines: Array<{
					sku: string;
					qty: number;
				}>;
			};
			events: {
				data: Array<string>;
				page: number;
			};
			form: {
				currencies: Array<string>;
			};
		};
	}

	interface Routes {
		"orders.export": { method: "get"; path: "/orders/export" };
		"orders.index": { method: "get"; path: "/orders"; component: "Orders/Index" };
		"orders.line-edit": {
			params: { id: string; lineId: string };
			method: "post";
			path: "/orders/:id/lines/:lineId";
			component: "Orders/LineEdit";
		};
		"orders.show": { params: { id: string }; method: "get"; path: "/orders/:id"; component: "Orders/Show" };
	}
}

declare module "@inertiajs/core" {
	interface InertiaConfig {
		// Shared props come from the shared-props registry (#1015), which this
		// project declares none of yet.
		sharedPageProps: Record<never, never>;
		// Flash keys are declared by the flash middleware (#996).
		flashDataType: Record<string, unknown>;
		errorValueType: string;
	}
}
