# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: blok/runtime/v1/runtime.proto for package 'Blok.Runtime.V1'
# Original file comments:
# Blok Runtime v1 — the wire contract between the TypeScript runner and SDK
# servers (Python, Go, Rust, Java, C#, PHP, Ruby).
#
# Single source of truth for cross-language interop. Generated stubs in each
# SDK are derived from this file via `make proto`.
#
# Stability: `blok.runtime.v1` is additive-only. CI runs `buf breaking` to
# reject backward-incompatible changes. Breaking changes go to `v2`, served
# alongside `v1` during migration.
#

require 'grpc'
require 'blok/runtime/v1/runtime_pb'

module Blok
  module Runtime
    module V1
      module NodeRuntime
        # =============================================================================
        # Service
        # =============================================================================
        #
        # NodeRuntime is the contract every Blok SDK exposes. One service handles
        # three responsibilities:
        #   1. Run a node (Execute / ExecuteStream)
        #   2. Tell the runner which nodes it can run (ListNodes)
        #   3. Tell the runner if it is alive (Health)
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'blok.runtime.v1.NodeRuntime'

          # Run a node and return its result. Unary, deadline-driven.
          rpc :Execute, ::Blok::Runtime::V1::ExecuteRequest, ::Blok::Runtime::V1::ExecuteResponse
          # Run a node and stream events back as it executes (logs, progress, partial
          # results, then a final ExecuteResponse). Optional capability — SDKs that
          # don't implement it should return UNIMPLEMENTED.
          rpc :ExecuteStream, ::Blok::Runtime::V1::ExecuteRequest, stream(::Blok::Runtime::V1::ExecuteEvent)
          # Health check (wire-compatible with grpc.health.v1.Health/Check).
          rpc :Health, ::Blok::Runtime::V1::HealthRequest, ::Blok::Runtime::V1::HealthResponse
          # Discover registered nodes and their schemas (drives Studio + OpenAPI gen).
          rpc :ListNodes, ::Blok::Runtime::V1::ListNodesRequest, ::Blok::Runtime::V1::ListNodesResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
