import { createInertiaApp } from "@inertiajs/react";
// The runtime route table behind `route()` — regenerated by `bun run gen:types`.
import "./blok-routes.js";
import { listenForFlash } from "./flash-toast.js";
// The Blok design system: tokens, layout and components in plain CSS.
import "./styles/blok.css";
import { initTheme, installFavicon } from "./styles/theme.js";

initTheme();
installFavicon();
listenForFlash();

// v3 `pages` shorthand: `@inertiajs/vite` compiles it into the `resolve` glob,
// and the adapter supplies `setup` (mount, or hydrate after SSR) itself.
createInertiaApp({
	pages: "./pages",
	title: (title) => (title ? `${title} — __BLOK_SPA_NAME__` : "__BLOK_SPA_NAME__"),
	progress: { color: "#2bcd71" },
});
